### ISSUE TITLE
Different temperatures for different parts of system?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#2910] opened 2020-10-31 23:27 UTC
I'd like to run simulations where different parts of the system are kept at different temperatures: essentially the same idea as Replica Exchange with Solute Tempering (REST), but not necessarily while doing replica exchange.  I'd like to select what is a "solute" based on providing a list of atoms to allow running more flexible experiments.

What is the right way to do that?  Can I use two different Langevin integrators in the same system?  Do I need to write a custom integrator?

P.S. It looks like `NoseHooverIntegrator` has an `addSubsystemThermostat()` method - is this a good way to do that?  Is there an example of a simple system using that?

**Comment by peastman** [comment] 2020-11-01 19:25
Yes, the NoseHooverIntegrator introduced in 7.5 handles this nicely.  I don't know that we have any examples of it yet, but the API docs should be fairly clear.  Just create an integrator using the constructor that doesn't add any thermostat, then call `addSubsystemThermostat()` for each part of the system that should be thermostated separately.  Let us know if you run into any problems.

**Comment by aizvorski** [comment] 2020-11-13 06:40
@peastman I tried to get it running.  It seems that calling `addSubsystemThermostat()` more than once always fails, regardless of what parameters are passed in.  Could you look this over and let me know what I'm doing wrong here?

```
from simtk.openmm import *
from simtk.unit import *
integrator = NoseHooverIntegrator(2.0*femtosecond)
integrator.addSubsystemThermostat([0], [], 300*kelvin, 1/picosecond, 300*kelvin, 1/picosecond, 3,3,3)
integrator.addSubsystemThermostat([1], [], 400*kelvin, 1/picosecond, 400*kelvin, 1/picosecond, 3,3,3)
```

Result:

```
---------------------------------------------------------------------------
OpenMMException                           Traceback (most recent call last)
<ipython-input-5-4a1c7d282de8> in <module>
      4 integrator = NoseHooverIntegrator(2.0*femtosecond)
      5 integrator.addSubsystemThermostat([0], [], 300*kelvin, 1/picosecond, 300*kelvin, 1/picosecond, 3,3,3)
----> 6 integrator.addSubsystemThermostat([1], [], 400*kelvin, 1/picosecond, 400*kelvin, 1/picosecond, 3,3,3)

~/anaconda3/lib/python3.8/site-packages/simtk/openmm/openmm.py in addSubsystemThermostat(self, thermostatedParticles, thermostatedPairs, temperature, collisionFrequency, relativeTemperature, relativeCollisionFrequency, chainLength, numMTS, numYoshidaSuzuki)
   5502 
   5503 
-> 5504         return _openmm.NoseHooverIntegrator_addSubsystemThermostat(self, thermostatedParticles, thermostatedPairs, temperature, collisionFrequency, relativeTemperature, relativeCollisionFrequency, chainLength, numMTS, numYoshidaSuzuki)
   5505 
   5506 

OpenMMException: Cannot add thermostat, since one of the thermostats already in the integrator applies to all particles. To manually add thermostats, use the constructor that takes only the step size as an input argument.
```

I'm on openmm 7.5
```
conda list | grep openmm
openmm                    7.5.0b1         cc3c4b5_py38_cuda102_0    omnia-dev/label/beta
```

> Yes, the NoseHooverIntegrator introduced in 7.5 handles this nicely. I don't know that we have any examples of it yet, but the API docs should be fairly clear. Just create an integrator using the constructor that doesn't add any thermostat, then call `addSubsystemThermostat()` for each part of the system that should be thermostated separately. Let us know if you run into any problems.

**Comment by aizvorski** [comment] 2020-11-13 06:49
Possibly useful additional info: the [docs](http://docs.openmm.org/development/api-c++/generated/OpenMM.NoseHooverIntegrator.html#_CPPv4N6OpenMM20NoseHooverIntegrator22addSubsystemThermostatERKNSt6vectorIiEERKNSt6vectorINSt4pairIiiEEEEddddiii) say "If both the list of thermostated particles and thermostated pairs are empty all particles will be thermostated."  However what seems to happen is if either list is empty in one call to `addSubsystemThermostat()`, the exception happens on the next call.  

So this works:
```
integrator.addSubsystemThermostat([0,1], [[0,1]], 300*kelvin, 1/picosecond, 300*kelvin, 1/picosecond, 3,3,3)
integrator.addSubsystemThermostat([2,3], [[2,3]], 400*kelvin, 1/picosecond, 400*kelvin, 1/picosecond, 3,3,3)
```
but this fails:
```
integrator.addSubsystemThermostat([0,1], [], 300*kelvin, 1/picosecond, 300*kelvin, 1/picosecond, 3,3,3)
integrator.addSubsystemThermostat([2,3], [[2,3]], 400*kelvin, 1/picosecond, 400*kelvin, 1/picosecond, 3,3,3)
```

**Comment by peastman** [comment] 2020-11-13 17:11
@andysim could you take a look at this?  I'm not entirely sure what's going on, but I suspect this line:

https://github.com/openmm/openmm/blob/83dcb4e2a40a612125a81a1459b246bc31cf49ba/openmmapi/src/NoseHooverIntegrator.cpp#L85

Should that be `+` rather than `*`?

**Comment by andysim** [comment] 2020-11-13 17:49
Yes, you're right @peastman.  The check is there to stop somebody from calling `addThermostat` (which is universal) and then calling `addSubsystemThermostat`.  In the case of `addThermostat` both lists are empty and the check works as intended for this bad use case.  However, it's perfectly valid to call `addSubsystemThermostat` with only atoms (or pairs) thermostated, so the check should only be that either is specified in the first NHC; changing the multiplication to addition will do this as you suggest.  Sorry for the confusion, and thanks for a very detailed bug report, @aizvorski .

**Comment by aizvorski** [comment] 2020-11-14 21:40
@andysim Thanks for the quick response!  Happy that was an easy one to figure out.

I added some dummy atoms so I can add a pair to each call and it works okay for now.  

A few more questions: 
- I tried running part of the system at 300K and part at 400K as above, but didn't see a huge difference in behavior over a few ns.  I'm guessing my collision frequency is low enough (1/picosecond) that the "hot" part equilibrates faster with the rest of the system than it does with the thermostat.  What would be a good ballpark value for the difference in temperature and especially the collision frequency if I want a hot molecule in cold solvent?  

- What should the last three parameters be set to?  chainLength, numMTS, numYoshidaSuzuki

- The speed of running with NoseHooverIntegrator is about 2/3 of the speed of LangevinIntegrator (everything else being the same, 75k atom system, explicit solvent, pme).  Is this expected?

I'd really like to make a full example of this using alanine dipeptide along the lines of this paper: https://www.pnas.org/content/102/39/13749  I think this is getting close :)

**Comment by peastman** [comment] 2020-11-16 00:15
The fix is in #2924.

**Closed** 2020-11-16 20:41 UTC

**Comment by andysim** [comment] 2020-11-18 20:05
I'm glad it's working @aizvorski.  I'm far from an expert in applying these things, I'm afraid; @Olllom and I wrote the code for somebody in our lab who needed it.  The implementation details came from [here](https://doi.org/10.1080/00268979600100761) and almost everything I know about the method came from [here](https://doi.org/10.1063/1.463940).

Here's my best attempt at answering your questions:
* @peastman and @Olllom looked at various autocorrelation functions to test the behavior of the thermostat with different `collisionFrequency` values.  For the `LanveginIntegrator` you'd generally use something around 1/ps to not screw up the kinetics, but for `NoseHoover` we found that higher values (around 25/ps) may be used safely.  In that case your subsystems would couple more strongly to their respective heat baths strongly enough to be separated in temperature, hopefully.  A lab member ran a lipid system that had been energy minimized with `NoseHoover` and 1/ps frequency, but it didn't get up to the target temperature in any reasonable time; the same system melted and equilibrated well using 25/ps.  I have no experience with REST methods, so I can't recommend a temperature difference I'm afraid.

* The chain length need only be set above 1 if you're running a really tiny system.  A chain of length 1 is just a regular Nosé-Hoover thermostat, which shows non-ergodic behavior for a single harmonic oscillator (see the 1992 paper linked above).  Adding some thermostat particles that interact with this thermostat particle (thus creating a chain of thermostats) fixes the problem.  For a system of 75k atoms, I think you can safely run with a chain length of 1.  The default is a little longer than that just because my benchmarks didn't show any slowdown when going from 1 to 3 for the chain length, and having the longer chain doesn't hurt the simulation at all.

* The thermostat degrees of freedom are propagated using a different timestep to the regular particles; for every step of dynamics there are `numMTS` x `numYoshidaSuzuki` steps taken by the auxiliary particles.  Just like with the timestep itself, choosing larger values for these parameters will shorten the integrator particles' timestep and increase the cost of the simulation as well as its stability.  I found that setting both parameters to 3 allowed me to conserve the overall energy pretty well in a [very simple waterbox test](https://github.com/openmm/openmm/blob/master/tests/TestNoseHooverIntegrator.h#L394-L448) so they're good ballpark values to try.

* I have also found that the NHC integrator is slower than Langevin, unfortunately.  My attempts to use the `nvprof` profiler to figure out why were unsuccessful because it completely choked on some unrelated code.  It's worth playing with the timestep settings for the thermostat to see how it impacts both timing and results for your system - if you have any enlightening data it'd be great to get any kind of feedback about best practices.

Good luck getting it working from here.  It's great to know that our decision to allow different parts of the system to couple to different heat baths is useful - @Olllom and I had a lot of headaches making the code work, primarily because of our decision to support that feature :)

**Comment by adw62** [comment] 2021-02-03 15:02
@aizvorski I'm interested in the idea of integrating the `SubsystemThermostat` into a REST like method. Did you have any luck making such a method work with an alanine dipeptide system?

**Comment by lgsmith** [comment] 2025-06-24 02:12
Hey folks, sorry to necro this. I'm trying to do something simpler than REST, but I cannot make the `addSubsystemThermostat` method work. I'm sure I'm making a simple mistake; hopefully you can spot it. I have shared the input I'm testing this with (it is just a water box, though that is not my longterm objective). Please find that attached.

The key lines producing the error are:
```
# create split thermostat

atoms =  list(topology.atoms())
half_a = atoms[:len(atoms)//2]
half_b = atoms[len(atoms)//2:]
prod_integrator = NoseHooverIntegrator(dt)
prod_integrator.addSubsystemThermostat(
    half_a,
    [],
    310 * kelvin,
    1/picosecond,
    310*kelvin,
    1/picosecond
)

prod_integrator.addSubsystemThermostat(
    half_b,
    [],
    temperature,  # defined above
    1/picosecond,
    temperature,
    1/picosecond
)
```
This fails with the following error (it's a no matching type signatures for overloaded function error):
```
Building system...
Traceback (most recent call last):
  File "/path/to/splittemp/run-splittemp.py", line 62, in <module>
    prod_integrator.addSubsystemThermostat(
  File "/path/to/miniconda3/envs/mmb/lib/python3.12/site-packages/openmm/openmm.py", line 7797, in addSubsystemThermostat
    return _openmm.NoseHooverIntegrator_addSubsystemThermostat(self, thermostatedParticles, thermostatedPairs, temperature, collisionFrequency, relativeTemperature, relativeCollisionFrequency, chainLength, numMTS, numYoshidaSuzuki)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'NoseHooverIntegrator_addSubsystemThermostat'.
  Possible C/C++ prototypes are:
    OpenMM::NoseHooverIntegrator::addSubsystemThermostat(std::vector< int,std::allocator< int > > const &,std::vector< std::pair< int,int >,std::allocator< std::pair< int,int > > > const &,double,double,double,double,int,int,int)
    OpenMM::NoseHooverIntegrator::addSubsystemThermostat(std::vector< int,std::allocator< int > > const &,std::vector< std::pair< int,int >,std::allocator< std::pair< int,int > > > const &,double,double,double,double,int,int)
    OpenMM::NoseHooverIntegrator::addSubsystemThermostat(std::vector< int,std::allocator< int > > const &,std::vector< std::pair< int,int >,std::allocator< std::pair< int,int > > > const &,double,double,double,double,int)
    OpenMM::NoseHooverIntegrator::addSubsystemThermostat(std::vector< int,std::allocator< int > > const &,std::vector< std::pair< int,int >,std::allocator< std::pair< int,int > > > const &,double,double,double,double)


```
I haven't been able to figure out what it wants from me, other than that it wants me to explicitly construct pairs lists, but the conversation in this thread implies to me that I should no longer need to do that.

In case it matters here's the output of `testInstallation` for me:
```
$ python -m openmm.testInstallation

OpenMM Version: 8.2
Git Revision: 53770948682c40bd460b39830d4e0f0fd3a4b868

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.32157e-06
Reference vs. CUDA: 6.74564e-06
CPU vs. CUDA: 7.11622e-07
Reference vs. OpenCL: 6.75018e-06
CPU vs. OpenCL: 7.34721e-07
CUDA vs. OpenCL: 1.77031e-07

All differences are within tolerance.
```
Thanks for your attention.
[splittemp.tar.gz](https://github.com/user-attachments/files/20874560/splittemp.tar.gz)

**Comment by peastman** [comment] 2025-06-24 16:05
The problem is the first argument.  It's supposed to be a list of particle indices, not a list of Atom objects.  Try this:

```python
atoms = list(range(topology.getNumAtoms()))
```

**Comment by lgsmith** [comment] 2025-06-24 16:48
Thanks for the quick response. I'd tried that earlier, but I must have had some other issue in the call signature (which I fixed before producing the example I sent) so I was getting the same error message. The docs say they're particle ids, but particle indexes make more sense. If it does actually need to be the `atom.id` attribute, not the `atom.index` attribute, that'd be good to know.

In case someone else runs across this, I had to change the above block to loop over residues:
```
residues = list(topology.residues())
half_a = [j.index for i in residues[:len(residues)//2] for j in i.atoms()]
half_b = [j.index for i in residues[len(residues)//2:] for j in i.atoms()]
prod_integrator = NoseHooverIntegrator(dt)
prod_integrator.addSubsystemThermostat(
    half_a,
    [],
    310 * kelvin,
    1/picosecond,
    310*kelvin,
    1/picosecond
)

prod_integrator.addSubsystemThermostat(
    half_b,
    [],
    temperature,
    1/picosecond,
    temperature,
    1/picosecond
)
```
This is because the integrator, sensibly, won't let you put atoms constrained to have some geometric relationship into two different subthermostats, and because my test system here is a box of constrained to be rigid waters, any 'splitting in half' that puts part of a water in one half and the other part in the other will run afoul of this restriction.
