### ISSUE TITLE
Drop python 2.7 support?

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#1912] opened 2017-10-05 17:16 UTC
This might be a good time to drop Python 2.7 support in the OpenMM 7.2 release.

**Comment by peastman** [comment] 2017-10-05 17:35
A lot of downstream projects that use OpenMM still support 2.7.  Dropping 2.7 support should be done in a coordinated way for all the Omnia projects, and we need to give people lots of notice for when it's going to happen.

Also, 7.2 is nearly done and all the code supports Python 2.7, so it's not like it would save us significant work to drop support at this point.

**Comment by Lnaden** [comment] 2017-10-05 17:42
I agree with Peter here. We have time until the official 2.7 EOL (April 2020), so I think its more a matter of getting the rest of Omnia on Python 3.6 first.  We can make it a requirement that all packages must support Python 3(.6?) before the Python 2.7 EOL. After that, we can then start winding down Python 2.7 support over all of Omnia. 

xref omnia-md/conda-recipes#702 and xref omnia-md/conda-recipes#551

**Comment by jchodera** [comment] 2017-10-05 17:49
@Lnaden : We would not be eliminating existing releases for Python 2.7---we would stop creating *new* OpenMM releases for Python 2.7. 

I believe all packages support Python 3.x a this point. [This PR](https://github.com/omnia-md/conda-recipes/pull/652) had flagged only the following failures:
* `assaytools` - supports Python 3 now
* `pymol` - deprecated
* `lomap` - belongs to @davidlmobley and does not depend on OpenMM
* `openpathsampling` - supports Python 3 now

**Comment by jchodera** [comment] 2017-10-05 17:50
> Also, 7.2 is nearly done and all the code supports Python 2.7, so it's not like it would save us significant work to drop support at this point.

How about we announce that this may be the last new release to support Python 2.7---that way we are not obligated to release new OpenMM versions to support it in the future?

**Comment by peastman** [comment] 2017-10-05 18:12
I think it's premature to do that.  We need to discuss it with the developers of all the other packages and make a coordinated decision about when Omnia as a whole will stop supporting 2.7.

**Comment by leeping** [comment] 2017-10-05 18:56
I agree with Peter on this; at some point I will transition to Python 3 (that's the version that my students are learning in classes, so it's hard to avoid) - but it will take time to verify that all of my research codes are behaving the same and that there isn't any unexpected behavior.

**Comment by jchodera** [comment] 2017-10-05 19:09
It's not premature to say this *may* be the last new release of OpenMM that supports Python 2.7. We've been discussing this [for over a year](https://github.com/omnia-md/conda-recipes/issues/551) and essentially every other group in Omnia has moved to Python 3, and most to Python 3 only. Releasing new OpenMM versions for Python 3.x only will not break their packages---it will only incentivize their transition to Python 3-only if they want to take advantage of new features.

Take a look at [this support timeline](http://www.python3statement.org/):
![image](https://user-images.githubusercontent.com/3656088/31247556-f2cc137a-a9de-11e7-8059-976e23e43d69.png)
From this, you can see how many scientific Python packages will have a new Python 2.7 feature release past today's date: ZERO. 

This doesn't mean we wouldn't backport a critical bugfix to Python 2.7---that's still something we can support all the way up through EOL if we want to. But we don't want to incentivize bad behavior by continuing to promise to support Python 2.7 for feature releases past OpenMM 7.2.

(Sorry, @leeping, but you're engaging in bad behavior.)

**Comment by rmcgibbo** [comment] 2017-10-05 19:11
Our team is starting our transition to Python 3 nowish, and would be negatively impacted by OpenMM dropping support for Python 2.7 at this point.

**Comment by jchodera** [comment] 2017-10-05 19:12
@rmcgibbo : Can you clarify whether you mean OpenMM 7.2 or post-OpenMM 7.2 releases?

**Comment by rmcgibbo** [comment] 2017-10-05 19:12
Both the current release and upcoming releases.

**Comment by jchodera** [comment] 2017-10-05 19:13
Also, can you specify a date through which it would be desirable to have new OpenMM feature releases support Python 2.7 for DESRES?

**Comment by rmcgibbo** [comment] 2017-10-05 19:14
I'm not sure on the date, or if there's one specific date. Different individuals and subgroups have different timelines.

**Comment by jchodera** [comment] 2017-10-05 19:14
Are you suggesting that DESRES would like indefinite support of Python 2.7?

**Comment by swails** [comment] 2017-10-05 19:16
> How about we announce that this may be the last new release to support Python 2.7---that way we are not obligated to release new OpenMM versions to support it in the future?

Not announcing this doesn't obligate the next release to support Python 2.7 if a strong justification arises not to.

What's harder to do because OpenMM still supports Python 2.7?  There are quite a few things that should make it reasonably easy:

1. It already does
1. CI framework can test it automatically so developers don't have to bother with it
1. Last time I checked we don't use features that make supporting Python 2.7 either very challenging or limits what we can do with Python 3

The other packages I know of that plan to drop 2.7 support do so because they use features that are far more expressive in Python 3 than their Python 2 counterparts.  For example, metaclasses are used heavily in Django, and Django has a bunch of hacky decorators in place to support Python 2.7.  Dropping 2.7 support significantly simplifies their code base.  I see no analogous simplification to OpenMM.

**Comment by jchodera** [comment] 2017-10-05 19:21
I'm mainly concerned with the build framework tooling. We already have a bunch of technical debt we need to address by still clinging to a build framework based on `conda-build 2.x` that will cost us time when upgrading to `conda-build 3.x`. I'm hoping to avoid unnecessary pain in continuing to support Python 2.7, especially if our lab and our collaborators have already dropped support for it.

The big transition we'll have to make soon is still moving `openmm` to `conda-forge`, so we can in principle hold onto Python 2.7 support as long as they do, but no longer.

**Comment by rmcgibbo** [comment] 2017-10-05 19:25
@jchodera: I am not suggesting that, no. We *are* moving to py3, we're just not there yet.

**Comment by jchodera** [comment] 2017-10-09 15:35
OK, I'm happy to do what we can to support the folks at DESRES with their transition away from Python 2.7, but it would be enormously helpful if @rmcgibbo could keep us abreast of any anticipated timelines that emerge.

I think we should also at least suggest in the release we will drop Python 2.7 support in new releases at some point in the future, and note that much of scientific python has already done so.

**Comment by rmcgibbo** [comment] 2017-10-09 15:42
We have the bandwidth to get by with whatever is best for the project, so I don't want to erroneously give the impression that I'm making any demands here. That's not my intent. As both @peastman and @leeping have mentioned, there are many downstream projects, and thus a lot of stakeholders here.

**Comment by jchodera** [comment] 2017-10-09 15:49
> As both @peastman and @leeping have mentioned, there are many downstream projects, and thus a lot of stakeholders here.

Communication/feedback is key, then. Let's make a point of being very clear that we'll drop Python 2.7 at some point in the future and that we want to hear back from stakeholders where this might cause a problem for them.

**Comment by rmcgibbo** [comment] 2017-10-09 15:53
@jchodera: Of course. Setting up a timeline, discussing and coordinating with the broader OpenMM community is exactly what @peastman was saying in his [first](https://github.com/pandegroup/openmm/issues/1912#issuecomment-334537402) [two](https://github.com/pandegroup/openmm/issues/1912#issuecomment-334547749) comments.

**Comment by jchodera** [comment] 2017-10-09 16:18
How do we reach all the users of OpenMM and Omnia package maintainers that depend on OpenMM? We can just tag the ones we know about, of course, but is there a mailing list we can use, or should we be putting a deprecation warning into the Python 2.7 package builds?

**Comment by peastman** [comment] 2017-10-09 16:24
How about we start by raising the issue at the next Omnia conference call and see what the other package maintainers think about it?

**Comment by jchodera** [comment] 2017-10-09 16:48
I don't believe we've had Omnia conference calls in over a year, and there are none scheduled, from what I understand. 

We can certainly rope the [Omnia participant groups](http://www.omnia.md/members/) into a new call where the first topic is Python 2.7 support, but that won't help us reach the folks we don't know about.

I'll send out an doodle poll to set up a call.

**Closed** 2020-12-01 21:08 UTC
