### ISSUE TITLE
Custom integrator for DPD simulations

### ISSUE THREAD

**Issue by bbye98** [openmm/openmm#3807] opened 2022-10-17 03:01 UTC
Hello!

I would like to run coarse-grained DPD simulations to capture the hydrodynamic effects of a polymeric system. However, while it appears that there are [plans for supporting DPD](https://github.com/openmm/openmm/issues/1435), there isn't a modified velocity-Verlet (MVV) integrator for DPD simulations.

Taking the [1997 Groot and Warren paper](https://aip.scitation.org/doi/10.1063/1.474784) as reference (and also taking a look at [LAMMPS's implementation](https://docs.lammps.org/fix_mvv_dpd.html)), this is what I came up with:

    def DPDIntegrator(dt: Union[float, unit.Quantity], lambda_: float = 0.5):

        integrator = openmm.CustomIntegrator(dt)
        integrator.addGlobalVariable("lambda", lambda_)
        integrator.addPerDofVariable("v1", 0)
        integrator.addPerDofVariable("x1", 0)
        integrator.addUpdateContextState()
        integrator.addComputePerDof("v1", "v+dt/2*f/m")
        integrator.addComputePerDof("x", "x+dt*v1")
        integrator.addComputePerDof("x1", "x")
        integrator.addConstrainPositions()
        integrator.addComputePerDof("v", "v+lambda*dt*f/m")
        integrator.addUpdateContextState()
        integrator.addComputePerDof("v", "v1+dt/2*f/m+(x-x1)/dt")
        integrator.addConstrainVelocities()

        return integrator

I wanted to make sure that I am understanding the various methods of the `CustomIntegrator` class correctly. I believe the steps above:

1. Creates a `CustomIntegrator` with timestep `dt` with global (constant) variable `lambda` and empty per-DOF variables `v1` and `x1`.
2. Updates the context, which reevaluates all forces using the `v` and `x` values currently at the previous time `t`.
3. Computes the half-step velocities `v1` from the standard velocity-Verlet algorithm.
4. Updates the particle positions `x` using the velocities from Step 3.
5. Stores a copy of `x` in `x1`.
6. Satisfy position constraints, if any.
7. Computes the intermediate velocities from the MVV algorithm and overwrites the current velocities `v`.
8. Updates the context, which reevaluates all forces using the `v` and `x` values currently at the new time `t + dt`.
9. Evaluates the final velocities using the new forces from Step 8.
10. Satisfy velocity constraints, if any.

I wanted to ensure the following:

1. Does Step 9 update the forces using the new `v` and `x` values, as this is a crucial piece of the MVV algorithm?
2. Is my placement of `addConstrainPositions` and `addConstrainVelocities` reasonable? I do not plan on using any constraints (SHAKE, Lincs, etc.) in my system, so it's not evidently clear to me if these are necessarily or correctly placed after reading the documentation.

Additionally, what would be the easiest way to implement the drag and random forces? I was thinking of implementing them as `CustomNonbondedForce`s, but then I would need the energy function, which is not trivial to acquire from the force expression. There also doesn't appear to be a number random generator for `CustomNonbondedForce`, so I assume I would actually need to do those calculations in the `CustomIntegrator` instead. However, if done in `CustomIntegrator`, how would I, for instance, evaluate the pairwise force?

Thank you in advance!

**Comment by peastman** [comment] 2022-10-17 15:11
`addUpdateContextState()` does something a bit different.  Force objects have the ability to directly modify the context instead of (or in addition to) computing forces and energy.  Some examples are AndersenThermostat, which modifies the velocities, and MonteCarloBarostat, which scales the coordinates and box vectors.  This should generally be done once per time step.  It's up to the integrator to decide when exactly during the step it should be done, at a point when arbitrary changes to positions and velocities won't interfere with its algorithm.

Recalculating forces is different.  It happens automatically.  If you modify the positions, it will recognize that any previously calculated forces are invalid and recalculate them before the next time they're needed.

If you don't plan to use any constraints, it's fine to omit the constraint steps.  Just remember that you've omitted them, since if you decide to use constraints in the future, you'll need to add them back.

As for how to implement DPD, I'm not certain it's possible with a CustomIntegrator.  We have an open issue #1435 to implement it using an algorithm that integrates each pairwise distance separately.  I don't think that would be possible with CustomIntegrator.  But maybe you know of an alternate implementation I'm not familiar with?

**Comment by bbye98** [comment] 2022-10-17 17:28
Thanks for the explanation about the constraints and force updates. 

Unfortunately, I’m not aware of any alternate implementations that do not involve computing the pairwise drag and random forces. 

For instance, the algorithm in LAMMPS, hoomd-blue, and the Groot and Warren paper is different than the one cited in issue #1435 (and I can’t be certain which one is more performant), but it still requires having a neighbor list to evaluate the drag and random forces.

A CustomIntegrator doesn’t have access to information about neighbor pairs, while a CustomNonbondedForce doesn’t have access to the distance vectors between pairs or a Gaussian random number generator. I suppose the only way is to write a new integrator kernel to do this, but this would be well over the programming skill level I am at so I will leave it to the experts. Hopefully by showing interest in DPD in OpenMM, this will get implemented soon!

**Comment by peastman** [comment] 2022-10-17 21:09
That's about what I expected.  Let's close this as a duplicate of #1435 and move any further discussion there.  If you have suggestions about the best way of implementing it, that would be great.

**Closed by peastman** 2022-10-17 21:09 UTC
