### ISSUE TITLE
CUDA tests failed - How to get more error messages from the tests?

### ISSUE THREAD

**Issue by jarunan** [openmm/openmm#3518] opened 2022-03-16 09:11 UTC
Hi there,

I am trying to setup OpenMM on an HPC cluster running with CentOS 7.9. Here is what I have done:

- I have compiled OpenMM 7.5.1 from source code with Python 3.8.5, CUDA toolkit version 11.0.3, CUDA driver version 495.29.05. 
- After the compilation, I performed `make test` and all TestCuda failed. 
- I set the environment variable `OPENMM_CUDA_COMPILER` to the `nvcc` executable I wanted to use. Then, some tests passed, some failed. 
- I ran some tests separately:
```
$ ./TestCudaVerletIntegrator
Done
$ ./TestCudaNonbondedForce 
exception: The requested CUDA device could not be loaded
$ ./TestCudaEwald 
exception: No compatible CUDA device is available
$ ./TestCudaHarmonicBondForce
exception: The requested CUDA device could not be loaded
$ ./TestCudaCustomAngleForce
exception: No compatible CUDA device is available
```
Is it possible to get more errors or warning messages?
Thanks for any hints and suggestions for how to further investigate the issue.

Best,
Jarunan

**Comment by jarunan** [comment] 2022-03-17 08:02
Hi Peter, 

Thank you for your reply.

I followed the installation in AlphaFold (2.1.2)'s Dockerfile which used OpenMM 7.5.1. The exception was thrown during amber minimization. 
```
I0316 09:19:43.077066 47909425217600 amber_minimize.py:417] No compatible CUDA device is available
I0316 09:19:43.084599 47909425217600 amber_minimize.py:407] Minimizing protein, attempt 100 of 100.
I0316 09:19:43.328804 47909425217600 amber_minimize.py:68] Restraining 604 / 1233 particles.
```
I will try the latest release of OpenMM.

I am checking with the cluster admin regarding the default setting of the GPU. 
Is it possible to disable creating multi-contexts on GPU in OpenMM?

Best,
Jarunan

**Comment by jarunan** [comment] 2022-03-17 15:58
I see. Thanks a lot for your help.

**Comment by peastman** [comment] 2022-03-21 16:21
Closing this issue since the question was answered.

The AlphaFold developers are unwilling to update OpenMM. :(  They say they validated it with 7.5.1 and don't plan to ever support any other version.

**Closed by peastman** 2022-03-21 16:21 UTC

**Comment by cschle** [comment] 2022-03-28 10:58
Hi @jarunan and @peastman, 
I ran into exactly the same issue with AF2 using OpenMM in GPU mode on a HPC. The root cause is the GPUs being set to exclusive mode and the JAX lib reserving the GPU without releasing it for the OpenMM step. 
This can be solved by starting MPS before launching the AF2 job. This will allow again to open more than one context on an GPU in exclusive mode. 
[https://docs.nvidia.com/deploy/mps/index.html  ](url)

**Comment by jarunan** [comment] 2022-03-31 07:02
Hi @cschle,
Thanks a lot for the hint. Starting MPS helps. It works now!
