### ISSUE TITLE
Mistakes in tutorial input script (OpenMM 7)

### ISSUE THREAD

**Issue by eldernah** [openmm/openmm#2343] opened 2019-07-11 12:56 UTC
The input script for the [Beta-2-adrenergic receptor (B2AR) membrane protein simulation with CHARMM](http://openmm.org/tutorials/b2ar_membrane/) tutorial apparently contains several errors:

`# Load CHARMM files`
`psf = CharmmPsfFile('step5_charmm2omm.psf')`
`pdb = PDBFile('step5_charmm2omm.pdb')`
`params = CharmmPsfFile('par_all36_prot.rtf', 'top_all36_prot.prm',
                       'par_all36_lipid.rtf', 'top_all36_lipid.prm',
                       'toppar_water_ion.str')`

Here the second time `CharmmPsfFile()` is called it should probably be `CharmmParameterSet()`.
Also, all force field files starting with `par_` are `*.prm` instead of `*.rtf`. On the other hand `top_all36_lipid.prm` should probably be `top_all36_lipid.rtf` and `toppar_water_ion.str` is missing an 's': `toppar_water_ions.str`.

Finally, there is another typo further down the script:
`simulaiton.reporters.append(PDBReporter('output.pdb', 1000))`
should be 
`simulation.reporters.append(PDBReporter('output.pdb', 1000))`

**Comment by jchodera** [comment] 2019-07-11 19:46
@ChayaSt : Can you take a look at this?

**Comment by peastman** [comment] 2020-12-03 18:04
Did this ever get fixed?

**Comment by apayne97** [comment] 2021-06-29 19:03
This didn't get fixed, documented here:
#3114 
and here:
#3152

**Comment by jchodera** [comment] 2021-07-01 09:12
@Yoshanuikabundi : Would you be able to help us correct these errors in the existing tutorials?

**Comment by peastman** [comment] 2024-12-03 00:53
Duplicate of #3114.  It seems to have gotten fixed at some point.

**Closed by peastman** 2024-12-03 00:53 UTC
Labels: bug, documentation, low effort, low priority
