### ISSUE TITLE
[8.0 Beta] ANI model JIT fails with CUDA platform

### ISSUE THREAD

**Issue by scal444** [openmm/openmm#3812] opened 2022-10-21 16:52 UTC
## Bug details
With the CPU platform, the attached script runs fine. Switching to the `CUDA` platform yields the following error:
```
Traceback (most recent call last):
  File "/home/kevin/benchmarks/openmm8/run.py", line 33, in <module>
    sim.step(5)
  File "/home/kevin/programs/conda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmm/app/simulation.py", line 141, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/kevin/programs/conda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmm/app/simulation.py", line 243, in _simulate
    self._generate_reports(unwrapped, False)
  File "/home/kevin/programs/conda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmm/app/simulation.py", line 259, in _generate_reports
    state = self.context.getState(getPositions=getPositions, getVelocities=getVelocities, getForces=getForces,
  File "/home/kevin/programs/conda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmm/openmm.py", line 3470, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
openmm.OpenMMException: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<string>", line 57, in <backward op>
            self_scalar_type = self.dtype
            def backward(grad_output):
                grad_self = AD_sum_backward(grad_output, self_size, dim, keepdim).to(self_scalar_type) / AD_safe_size(self_size, dim)
                            ~~~~~~~~~~~~~~~ <--- HERE
                return grad_self, None, None, None
  File "<string>", line 24, in AD_sum_backward
            if not keepdim and len(sizes) > 0:
                if len(dims) == 1:
                    return grad.unsqueeze(dims[0]).expand(sizes)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                else:
                    res = AD_unsqueeze_multiple(grad, dims, len(sizes))
RuntimeError: expand(CUDADoubleType{[1, 1]}, size=[1]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
```

Script is here, input PDB is in the attached zip. 
```
import sys
import time


from openmm.app.pdbfile import PDBFile
from openmmml import MLPotential
from openmm.app.simulation import Simulation
from openmm.app.statedatareporter import StateDataReporter
from openmm.openmm import LangevinIntegrator, Platform



potential = MLPotential('ani2x')
pdb = PDBFile("water_2nm.pdb")
system = potential.createSystem(pdb.getTopology())

integrator = LangevinIntegrator(300, 1.0, 0.001)

platform = Platform.getPlatformByName('CUDA')
#platform = Platform.getPlatformByName('CPU')
sim = Simulation(pdb.getTopology(), system, integrator, platform)

sim.context.setPositions(pdb.positions)
sim.context.setVelocitiesToTemperature(300)
sim.context.setPeriodicBoxVectors(*pdb.topology.getPeriodicBoxVectors())

sim.reporters.append(StateDataReporter(sys.stdout,
                                       1,
                                       step=True,
                                       potentialEnergy=True,
                                       temperature=True))
print("Running warmup")
sim.step(5)
print("Running timed run")
steps = 20
tic = time.time()
sim.step(steps)
toc = time.time()
print(f"\n\n{steps} steps in {toc - tic} seconds")
```

## System environment
I'm running Ubuntu 20.04. I pulled the conda environment as suggested in the forum post.

`conda env create mmh/openmm-8-beta-linux`

Needed to downgrade the cudatoolkit from 11.7 to 11.6, since I have the 11.6 drivers. Full environment attached in `env.txt`.

[openmm_8_bug_repro.zip](https://github.com/openmm/openmm/files/9840907/openmm_8_bug_repro.zip)

**Comment by raimis** [comment] 2022-10-21 17:25
Similar to https://github.com/openmm/openmm-torch/issues/84

**Comment by peastman** [comment] 2022-10-22 00:24
I can't figure out where that code is coming from.  It doesn't appear to be part of torchani.  A web search for `AD_sum_backward` doesn't turn up anything either.

**Comment by peastman** [comment] 2022-10-22 22:50
The problem seems to be related to NNPOps.  If I add `implementation='torchani'` to the `createSystem()` call, it runs correctly.

**Comment by raimis** [comment] 2022-10-24 13:16
It seems that TorchScript has become more stringent. I'm trying to reduce the test case to find the cause.

**Comment by raimis** [comment] 2022-10-25 12:07
I have installed a new environment with:
 ```bash
conda env create mmh/openmm-8-beta-linux
``` 
Run the script:
```bash
$ python debug.py 
/shared2/raimis/opt/miniconda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
/shared2/raimis/opt/miniconda/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/resources/
Running warmup
#"Step","Potential Energy (kJ/mole)","Temperature (K)"
1,-44332435.58578159,319.8004098272167
2,-44332539.87829229,332.846256631403
3,-44332523.64569288,333.6018414163098
4,-44332608.27404819,342.41404152648926
5,-44332676.911427684,349.43591938174876
Running timed run
6,-44332680.84062815,349.47175818935443
7,-44332637.11113709,343.45681359303023
8,-44332508.86220914,330.31330494027065
9,-44332545.52953043,335.3767191864763
10,-44332800.14697877,363.58596993408645
11,-44332956.492475614,381.8605020077687
12,-44332980.27049201,386.52771364000205
13,-44333032.792954065,391.7789958145508
14,-44333097.61318135,398.7749099197864
15,-44333129.42987743,401.6060583189521
16,-44333019.08676107,389.07076831747946
17,-44332868.38373882,372.9317003746404
18,-44332913.02401317,378.65707569205136
19,-44333120.358350724,401.7719296910947
20,-44333276.650014326,420.5192141526989
21,-44333311.26979463,425.5351980143107
22,-44333276.79148307,421.9890501013698
23,-44333291.24633366,423.43618827371904
24,-44333251.26576431,416.9946290101039
25,-44333065.007765725,395.7629125536522


20 steps in 1.6338467597961426 seconds
```
And it works!

**Comment by raimis** [comment] 2022-10-25 12:08
I tried to downgrade `cudatoolkit` to 11.6, but it still works.

**Comment by peastman** [comment] 2022-10-25 16:33
I installed with exactly the same command he did: `conda env create mmh/openmm-8-beta-linux`, and I get the same error.  Here is my environment.

```
# packages in environment at /home/peastman/miniconda3/envs/openmm-8-beta-linux:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
brotlipy                  0.7.0                    pypi_0    pypi
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
cryptography              38.0.2                   pypi_0    pypi
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
cudnn                     8.4.1.50             hed8a83a_0    conda-forge
exceptiongroup            1.0.0rc9           pyhd8ed1ab_0    conda-forge
h5py                      3.7.0                    pypi_0    pypi
hdf5                      1.12.2          nompi_h4df4325_100    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4                   pypi_0    pypi
importlib_metadata        4.11.4               hd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lark-parser               0.12.0             pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.85.0               h2283fc2_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libprotobuf               3.21.8               h6239696_0    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               14.0.4               he0ac6c6_0    conda-forge
magma                     2.5.4                hc72dce7_3    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
nnpops                    0.2             cuda112py310h8b99da5_5    conda-forge
numpy                     1.23.4                   pypi_0    pypi
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openmm                    8.0.0                    pypi_0    pypi
openmm-ml                 1.0beta            pyh79ba5db_2    conda-forge/label/openmm_rc
openmm-torch              1.0beta         cuda112py310h02d4f52_1    conda-forge/label/openmm-torch_rc
openmmtorch               1.0                      pypi_0    pypi
openssl                   3.0.5                h166bdaf_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.0                    pypi_0    pypi
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytorch                   1.12.1          cuda112py310he33e0d6_201    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
setuptools                59.5.0                   pypi_0    pypi
setuptools-scm            6.3.2              pyhd8ed1ab_0    conda-forge
setuptools_scm            6.3.2                hd8ed1ab_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
tbb                       2021.6.0             h924138e_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torch                     1.12.1.post201           pypi_0    pypi
torchani                  2.2.2                    pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
```

@mikemhenry does the environment file install anything with pip?  Can you post it?  I don't think the checked in version is up to date.

**Comment by mikemhenry** [comment] 2022-10-25 18:06
I've updated the env files @peastman https://github.com/openmm/openmm/pull/3818
They don't pull from pypi.

**Comment by peastman** [comment] 2022-10-25 18:30
To make absolutely sure, I put that into a local `environment.yaml` file and installed with the command `conda env create -f environment.yaml`.  Sure enough, it still lists some packages as being from pypi.

**Comment by jchodera** [comment] 2022-10-25 18:35
> To make absolutely sure, I put that into a local environment.yaml file and installed with the command conda env create -f environment.yaml. Sure enough, it still lists some packages as being from pypi.

I think this is due to how those packages were built. For example, [`pytest` is pulled from pypi in the conda recipe](https://github.com/conda-forge/pytest-feedstock/blob/main/recipe/meta.yaml#L7-L8). Just ignore this.

**Comment by peastman** [comment] 2022-10-25 18:48
I think the difference comes from whether you use conda or mamba to create the environment.  If I use conda, the example fails.  If I use mamba, it works.

Comparing the environments, there are a lot of differences.  Conda installs pytorch 1.12.1 while mamba installs 1.11.0, which is probably the reason for a lot of the differences.  And conda installs packages that use OpenBLAS while mamba installs ones that use MKL.

**Comment by peastman** [comment] 2022-11-15 00:16
I've been trying to understand the cause of this error.  I'm still not clear on what causes it, but I have made a few observations that might be useful.

First, I tracked down the code listed in the error message.  It's part of the internal PyTorch JIT code.  It's [this file](https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/runtime/symbolic_script.cpp).  Note that's actually a C++ file.  But it contains a string with Python code in it.

I also tried creating the environment with conda, then downgrading PyTorch to various versions.  If I downgrade to 1.11.0 it works.  If I downgrade to 1.12.0 it fails with a different error:

```
Traceback (most recent call last):
  File "/home/peastman/Downloads/bug_repro/run.py", line 15, in <module>
    system = potential.createSystem(pdb.getTopology(), implementation='nnpops')
  File "/home/peastman/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmmml/mlpotential.py", line 178, in createSystem
    self._impl.addForces(topology, system, None, 0, **args)
  File "/home/peastman/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/openmmml/models/anipotential.py", line 71, in addForces
    import torchani
  File "/home/peastman/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/__init__.py", line 32, in <module>
    from .utils import EnergyShifter
  File "/home/peastman/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torchani/utils.py", line 1, in <module>
    import torch
  File "/home/peastman/miniconda3/envs/openmm-8-beta-linux/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcupti.so.11.2: cannot open shared object file: No such file or directory
```

That looks like a binary incompatibility between libraries.  But mamba *thinks* everything it has installed should be compatible.

**Comment by peastman** [comment] 2022-11-15 00:20
That was with `cudatoolkit=11.6`.  When I downgraded it to `11.2` the above error went away, and PyTorch 1.12.0 gave the same error as 1.12.1.

**Comment by peastman** [comment] 2022-11-22 04:58
Here is a bit more data.  This is the body of OptimizedTorchANI.forward().

```python
species_coordinates = self.species_converter(species_coordinates)
species_aevs = self.aev_computer(species_coordinates, cell=cell, pbc=pbc)
species_energies = self.neural_networks(species_aevs)
species_energies = self.energy_shifter(species_energies)

return species_energies
```

If I remove the call to `self.energy_shifter()`, the error goes away.  I can also make it go away by inserting a `print()` command immediately before it:

```
species_energies = self.neural_networks(species_aevs)
print()
species_energies = self.energy_shifter(species_energies)
```

That strongly suggests a bug in the compiler.  Making it produce output at that point somehow alters its internal state or prevents incorrect optimizations that lead to the error.  Placing the `print()` at any other point in this function does not remove the error.  It has to be exactly there.

To narrow it down even more, here is the `forward()` method of `self.neural_networks`:

```python
    def forward(self, species_aev: Tuple[Tensor, Tensor]) -> SpeciesEnergies:

        species, aev = species_aev

        # Reshape: [num_mols, num_atoms, num_features] --> [num_mols, num_atoms, 1, num_features, 1]
        vectors = aev.unsqueeze(-2).unsqueeze(-1)

        vectors = batchedLinear(vectors, self.layer0_weights, self.layer0_biases) # Linear 0
        vectors = F.celu(vectors, alpha=0.1)                                      # CELU   1
        vectors = batchedLinear(vectors, self.layer2_weights, self.layer2_biases) # Linear 2
        vectors = F.celu(vectors, alpha=0.1)                                      # CELU   3
        vectors = batchedLinear(vectors, self.layer4_weights, self.layer4_biases) # Linear 4
        vectors = F.celu(vectors, alpha=0.1)                                      # CELU   5
        vectors = batchedLinear(vectors, self.layer6_weights, self.layer6_biases) # Linear 6

        # Sum: [num_mols, num_atoms, num_models, 1, 1] --> [num_mols, num_models]
        # Mean: [num_mols, num_models] --> [num_mols]
        energies = torch.mean(torch.sum(vectors, (1, 3, 4)), 1)

        return SpeciesEnergies(species, energies)
```

The `print()` must come at the very end, after computing `energies`.  Putting it earlier than that doesn't work.  And here is the `forward()` method of `self.energy_shifter()`:

```python
    def forward(self, species_energies: Tuple[Tensor, Tensor],
                cell: Optional[Tensor] = None,
                pbc: Optional[Tensor] = None) -> SpeciesEnergies:

        species, energies = species_energies

        return SpeciesEnergies(species, energies + self.self_energies)
```

It hardly does anything: unpack a tuple, add two tensors, and pack the result into a new tuple.  The `print()` must come before the addition.  It doesn't matter whether it's before or after unpacking the tuple.

**Comment by peastman** [comment] 2022-11-23 00:11
Ok, I think I have a workaround.  In `_BatchedNN.forward()` replace the line

```python
energies = torch.mean(torch.sum(vectors, (1, 3, 4)), 1)
```

with

```python
energies = torch.sum(vectors, (1, 2, 3, 4))/vectors.shape[2]
```

That makes the error go away, and I believe it should always produce identical results.  Can you try it out and see if it works?

**Comment by raimis** [comment] 2022-11-29 10:31
This looks like a TorchScript issue. It may be worth to create an issue in the PyTorch repo.

**Comment by peastman** [comment] 2022-11-29 17:10
Sounds like a good idea.

**Closed** 2022-11-29 17:42 UTC
