### ISSUE TITLE
CHARMM-Drude 2019 residue patch

### ISSUE THREAD

**Issue by smlee99** [openmm/openmm#3815] opened 2022-10-23 07:50 UTC
Hi OpenMM devs!

I'm currently trying to simulate the amino acid ARG capped with ACE and NME. Following the CHARMM convention, I just included ACE and NME atoms into the ARG single residue. It seems like `modeller.addExtraParticles()` does not work properly since No template found for residue 1 (ARG).

```
from openmm.app import *
from openmm import *
from openmm.unit import *

pdb = PDBFile('./test.pdb')
forcefield = ForceField('charmm_polar_2019.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addExtraParticles(forcefield)
```

I think the input topology is defined correctly. Is there any problem regarding `modeller.addExtraParticles()` for patch residues? For instance, I've checked that such function correctly added the drude particles for standard residues. There were some issues regarding disulfide patch in CHARMM-Drude 2019 (as seen in #2848) but idk this is also the case. I installed OpenMM 7.7 via source compile and below is the test.pdb file I've used. All bonds (including ARG) are defined.

```
REARGK   1 CREATED WITH OPENMM 7.7, 2022-10-23
CRYST1   39.352   42.600   80.000  90.00  90.00  90.00 P 1           1 
HETATM    1  CH3 ARG A   1      12.588   0.951  34.637  1.00  0.00           C  
HETATM    2  H1  ARG A   1      12.260   0.249  35.404  1.00  0.00           H  
HETATM    3  H2  ARG A   1      13.545   0.625  34.232  1.00  0.00           H  
HETATM    4  H3  ARG A   1      11.848   0.986  33.838  1.00  0.00           H  
HETATM    5  CF  ARG A   1      12.740   2.325  35.246  1.00  0.00           C  
HETATM    6  OF  ARG A   1      12.533   2.493  36.449  1.00  0.00           O  
HETATM    7  N   ARG A   1      13.123   3.308  34.425  1.00  0.00           N  
HETATM    8  H   ARG A   1      13.287   3.070  33.458  1.00  0.00           H  
HETATM    9  CA  ARG A   1      13.320   4.724  34.793  1.00  0.00           C  
HETATM   10  HA  ARG A   1      12.513   5.017  35.464  1.00  0.00           H  
HETATM   11  CB  ARG A   1      14.696   4.870  35.487  1.00  0.00           C  
HETATM   12  HB2 ARG A   1      15.464   5.019  34.729  1.00  0.00           H  
HETATM   13  HB3 ARG A   1      14.948   3.936  35.989  1.00  0.00           H  
HETATM   14  CG  ARG A   1      14.814   5.995  36.536  1.00  0.00           C  
HETATM   15  HG2 ARG A   1      15.799   5.913  36.994  1.00  0.00           H  
HETATM   16  HG3 ARG A   1      14.768   6.962  36.034  1.00  0.00           H  
HETATM   17  CD  ARG A   1      13.761   5.964  37.662  1.00  0.00           C  
HETATM   18  HD2 ARG A   1      12.850   6.442  37.301  1.00  0.00           H  
HETATM   19  HD3 ARG A   1      14.124   6.550  38.506  1.00  0.00           H  
HETATM   20  NE  ARG A   1      13.423   4.587  38.070  1.00  0.00           N  
HETATM   21  HE  ARG A   1      12.989   4.012  37.361  1.00  0.00           H  
HETATM   22  CZ  ARG A   1      13.671   3.938  39.187  1.00  0.00           C  
HETATM   23  NH1 ARG A   1      14.257   4.485  40.215  1.00  0.00           N  
HETATM   24 HH11 ARG A   1      14.531   5.456  40.162  1.00  0.00           H  
HETATM   25 HH12 ARG A   1      14.433   3.947  41.052  1.00  0.00           H  
HETATM   26  NH2 ARG A   1      13.319   2.689  39.256  1.00  0.00           N  
HETATM   27 HH21 ARG A   1      12.899   2.273  38.436  1.00  0.00           H  
HETATM   28 HH22 ARG A   1      13.475   2.139  40.089  1.00  0.00           H  
HETATM   29  C   ARG A   1      13.248   5.598  33.528  1.00  0.00           C  
HETATM   30  O   ARG A   1      13.734   5.174  32.490  1.00  0.00           O  
HETATM   31  NJ  ARG A   1      12.675   6.804  33.549  1.00  0.00           N  
HETATM   32  HJ  ARG A   1      12.710   7.284  32.661  1.00  0.00           H  
HETATM   33  CJ  ARG A   1      11.950   7.456  34.640  1.00  0.00           C  
HETATM   34  HJ1 ARG A   1      12.642   7.785  35.416  1.00  0.00           H  
HETATM   35  HJ2 ARG A   1      11.204   6.784  35.063  1.00  0.00           H  
HETATM   36  HJ3 ARG A   1      11.432   8.334  34.254  1.00  0.00           H  
TER      37      ARG A   1
CONECT    1    2    3    4    5
CONECT    2    1
CONECT    3    1
CONECT    4    1
CONECT    5    1    6    7
CONECT    6    5
CONECT    7    8    9    5
CONECT    8    7
CONECT    9    7   10   11   29
CONECT   10    9
CONECT   11   12   13    9   14
CONECT   12   11
CONECT   13   11
CONECT   14   15   16   11   17
CONECT   15   14
CONECT   16   14
CONECT   17   18   19   14   20
CONECT   18   17
CONECT   19   17
CONECT   20   21   17   22
CONECT   21   20
CONECT   22   20   23   26
CONECT   23   24   25   22
CONECT   24   23
CONECT   25   23
CONECT   26   27   28   22
CONECT   27   26
CONECT   28   26
CONECT   29    9   30   31
CONECT   30   29
CONECT   31   32   33   29
CONECT   32   31
CONECT   33   34   35   36   31
CONECT   34   33
CONECT   35   33
CONECT   36   33
END
```

**Comment by smlee99** [comment] 2022-10-23 16:09
Hm... I solved this issue. For both ACE and NME (in CHARMM Drude 2019, CT3) residues in xml file, the only considered AddBond is the one between patch and standard residue and internal bonds are missing. And for the ACE residue, <RemoveExternalBond atomName="N"/> is missing. I manually added such topology information in xml file and now residues are properly recognized. So there should be a change in current CHARMM Drude 2019 xml file, right? I wonder this since there are various patches without defining internal bonds as AddAtom.

**Comment by peastman** [comment] 2022-11-17 19:31
I'm working on fixing this issue.  I think I have fixes for both problems.  I can hopefully get an updated XML file checked in soon.

Even after fixing those problems, your PDB file still doesn't work correctly.  The problem is that you call the residue ARG, indicating it's a standard residue, but in fact it isn't a standard ARG residue.

The PDB spec specifies that CONECT records should not be included for standard residues.  Instead, the reader is supposed to automatically fill in the bonds for them.  In a standard ARG residue, the atoms H1, H2, and H3 are all bonded to N, so those bonds automatically get added when the file is read.  But in your case, you intend them to be bonded to CH3 instead.  The fix is to change the residue name so it doesn't get interpreted as a standard ARG residue.

**Closed** 2022-12-01 16:37 UTC
Labels: bug
