### ISSUE TITLE
Planning for 8.1

### ISSUE THREAD

**Issue by peastman** [openmm/openmm#4182] opened 2023-08-10 19:47 UTC
I think it's getting to be time to start planning an 8.1 release.  There've been a number of important changes added since 8.0, including a bunch of performance improvements, ATMForce, and support for GROMOS force fields.  What else do we want to include?  If anyone has specific features or changes they'd like to see included in 8.1, now is the time to speak up!

**Comment by leeping** [comment] 2023-08-18 03:24
The recently merged AMOEBA bug fix should be part of it, right?

**Comment by peastman** [comment] 2023-08-18 03:31
Right.  Everything that's already merged will definitely be included.

**Comment by sef43** [comment] 2023-08-24 09:40
Merge #4075 so when the 8.1 docs are uploaded as the latest release the link will be there.

**Comment by bdenhollander** [comment] 2023-09-02 13:35
I would like to see #3973 included. Combined with #3934, #4070, #4147,and #4177, AMD OpenCL on Windows should see 5-40% performance gains between 8.0 and 8.1.

**Comment by peastman** [comment] 2023-10-02 16:22
I was hoping to include #4185, but it's been a month and a half and still no one has tested it.  We can't keep delaying indefinitely, and clearly it isn't a high priority for anyone.  I suggest we move ahead with it.

Shall I create the beta?

**Comment by peastman** [comment] 2023-10-09 23:00
It finished building the packages.  I tested a couple of them and they worked correctly.  That means we can go ahead and create the github release.

**Comment by peastman** [comment] 2023-10-09 23:09
Here is the release: https://github.com/openmm/openmm/releases/tag/8.1.0beta

Here is the announcement on the forum: https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=17037&p=0&start=0&view=

**Comment by peastman** [comment] 2023-11-01 17:50
We're probably about a week away from building the release candidate.  Are there any open issues you particularly want to see addressed first?  No new features at this point, just bug fixes and documentation updates.  Speak now or it probably won't get addressed!

**Comment by mattwthompson** [comment] 2023-11-03 15:43
The beta - thanks for making these with every release - has worked great in OpenFF infrastructure since builds were online. No unexpected issues, the only updates we've needed to make were from expected changes. Looking forward to the RC and full release

**Comment by peastman** [comment] 2023-11-08 04:29
Are we ready to build the release candidate?  Last chance to speak up!

**Comment by peastman** [comment] 2023-11-09 22:50
The RC packages are now up.  Give it a try.

**Comment by bdenhollander** [comment] 2023-11-11 03:38
I ran through a collection of FAH projects on RC1 with my AMD Radeon RX 6600 (Windows 10, OpenCL 3592). Most of the results were good but there were a few regressions on systems with 100K+ atoms.

| Project | Atoms  | OpenMM 8.0<br>ns/day | OpenMM 8.1 RC1<br>ns/day | Change  |
|---------|--------|------------|----------------|---------|
| 13415   | 4038   | 145.695    | 174.0264       | 19.45%  |
| 17600   | 37801  | 150.703    | 198.1146       | 31.46%  |
| 12271   | 42065  | 159.9059   | 202.289        | 26.51%  |
| 16918   | 65523  | 59.6494    | 69.6369        | 16.74%  |
| 18717   | 77795  | 43.2609    | 50.4236        | 16.56%  |
| 13428   | 90729  | 11.8919    | 13.0515        | 9.75%   |
| 17919   | 103824 | 44.8951    | 47.1498        | 5.02%   |
| 14944   | 105522 | 45.4175    | 41.5543        | -8.51%  |
| 18449   | 142541 | 27.826     | 29.4495        | 5.83%   |
| 17308   | 158384 | 49.1856    | 41.3582        | -15.91% |
| 17424   | 167028 | 48.9424    | 53.8038        | 9.93%   |
| 14908   | 215357 | 18.2397    | 18.219         | -0.11%  |
| 18213   | 302725 | 12.5914    | 15.3767        | 22.12%  |

Since 100K is the OpenCL cutoff for `useLargeBlocks`, I checked that first and reran those projects with the cutoff set to 250K.

| Project | Atoms  | OpenMM 8.0<br/>ns/day | 100K<br/>ns/day | 250K<br/>ns/day | 
|---------|--------|------------|---------|---------|
| 17919   | 103824 | 44.8951    | 47.1498 | 46.6724 |
| 14944   | 105522 | 45.4175    | 41.5543 | 46.7476 |
| 18449   | 142541 | 27.826     | 29.4495 | 29.5443 |
| 17308   | 158384 | 49.1856    | 41.3582 | 50.7176 |
| 17424   | 167028 | 48.9424    | 53.8038 | 52.114  |
| 14908   | 215357 | 18.2397    | 18.219  | 18.7048 |
| | Sum ns/day | 234.5063 | 231.5346	| 244.5007

50% of projects in the 100K-250K atom range get a boost from large blocks on my GPU but those gains are not enough to offset the regressions. With a 250K cutoff for large blocks, all projects show gains compared to OpenMM 8.0.

| Project | Atoms  | OpenMM 8.0<br/>ns/day | 250K<br/>ns/day | Change |
|---------|--------|------------|----------|--------|
| 13415   | 4038   | 145.695    | 174.0264 | 19.45% |
| 17600   | 37801  | 150.703    | 198.1146 | 31.46% |
| 12271   | 42065  | 159.9059   | 202.289  | 26.51% |
| 16918   | 65523  | 59.6494    | 69.6369  | 16.74% |
| 18717   | 77795  | 43.2609    | 50.4236  | 16.56% |
| 13428   | 90729  | 11.8919    | 13.0515  | 9.75%  |
| 17919   | 103824 | 44.8951    | 46.6724  | 3.96%  |
| 14944   | 105522 | 45.4175    | 46.7476  | 2.93%  |
| 18449   | 142541 | 27.826     | 29.5443  | 6.18%  |
| 17308   | 158384 | 49.1856    | 50.7176  | 3.11%  |
| 17424   | 167028 | 48.9424    | 52.114   | 6.48%  |
| 14908   | 215357 | 18.2397    | 18.7048  | 2.55%  |
| 18213   | 302725 | 12.5914    | 15.3767  | 22.12% |

I think benchmarking a wider variety of systems and adjusting the cutoff point before the release would be a good idea.

**Comment by peastman** [comment] 2023-11-11 03:53
The release candidate is already out.  At this point the only changes we'll make are critical bug fixes.  Further optimization will have to wait for 8.2.

**Comment by peastman** [comment] 2023-11-16 23:21
I'm building a second release candidate (see https://github.com/conda-forge/openmm-feedstock/pull/118) to get the fixes in #4317 and #4319.

**Comment by hmacdope** [comment] 2023-11-17 08:17
@peastman @bdenhollander I have just tested the `rc2` candidate [43f571d](https://github.com/openmm/openmm/commit/43f571d90fc1c882848cbd9b55e097a1775a9075) as basis for build of  OpenMM core and everything seems to be working as expected (cc @jchodera)

**Comment by peastman** [comment] 2023-11-26 00:38
It's been over a week since rc2 and no new problems have been reported.  Let's plan to make the release on Monday.

**Comment by peastman** [comment] 2023-11-27 23:15
The github release has been made, and the conda packages are now online.

**Comment by peastman** [comment] 2023-11-27 23:26
The documentation page on the website now points to the new version.

**Comment by jchodera** [comment] 2023-11-27 23:31
Congrats, everyone!

**Closed** 2023-12-12 16:12 UTC
Labels: discussion
