### ISSUE TITLE
TestOpenCLDrudeNoseHooverSingle failing repeatedly on Jenkins CI

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#4124] opened 2023-06-25 09:42 UTC
The `TestOpenCLDrudeNoseHooverSingle` test seems to be repeatedly failing on the Jenkins CI.

Here is [two days ago](https://jenkins.jasonswails.com/blue/organizations/jenkins/openmm-github%2Fopenmm/detail/master/350/pipeline#step-81-log-346).

You can see all the failures over the last 25 days here:
https://jenkins.jasonswails.com/blue/organizations/jenkins/openmm-github%2Fopenmm/activity/

I haven't found a single instance where this test has succeeded.

The error message may be misleading, since it says the test may stochastically fail, yet it essentially produces ~310 each time:
```
exception: Assertion failure at TestDrudeNoseHoover.h:184.  Expected 300, found 310.185 (This test is stochastic and may occasionally fail)
```

**Comment by peastman** [comment] 2023-06-25 16:03
This is a duplicate of #4109.  See the discussion there for details.

**Closed by peastman** 2023-06-25 16:03 UTC
