### ISSUE TITLE
Errors in CUDA platform with simultaneous use of multiple forces

### ISSUE THREAD

**Issue by mvanvleet** [openmm/openmm#1794] opened 2017-04-26 00:50 UTC
As per the title, I am running into errors on the CUDA platform when evaluating energies from a force field that contains both an AmoebaMultipoleForce and a NonbondedForce. (As to why I am doing this, I would like to run a simulation that includes both multipoles and LJ-type nonbonded interactions. I would prefer to use LJPME to evaluate the long-range LJ forces, hence why I used both forces).

When I evaluate the energies of one (but not both) of the two forces, I get the following energies (kj/mol, results from the CPU platform also shown for reference):
```
Just nonbondedforce:
    CPU: -1.70043045353
    CUDA: -1.70042987235
Just AmoebaMultipoleForce:
    CPU: -3155.15307921
    CUDA: -3155.15648635
Both NonbondedForce + AmoebaMultipoleForce: 
    CPU: -3156.85350967
    CUDA: -213.760077752
```
As you can see, with the CPU platform the combined energy is (as it should be) the sum of the nonbonded and AmoebaMultipole energies; for the CUDA platform, on the other hand, the energies are significantly off, and an energy decomposition suggests that the nonbonded/amoebamultipole energies are, respectively, 0.0103488924474 and -213.770426645 (which is incorrect).

For aid in debugging this problem, I've attached the systems I used for comparison:

[nonbonded_amoebamultipole_bug.zip](https://github.com/pandegroup/openmm/files/956917/nonbonded_amoebamultipole_bug.zip)

 All files can be run with the command

```sh
$ python run_co2.py CUDA; python run_co2.py CPU
```

As always, your time and effort in solving these bugs is greatly appreciated.

**Comment by mvanvleet** [comment] 2017-04-27 15:14
As a side note, even for forces that add up to the correct total energy between CUDA and CPU, I'm seeing many discrepancies in the energy decomposition between the two platforms. (As above, the CPU platform is the sum of the energies I get from running separate simulations with each force). This may be an error on my part in using the energy decomposition, or it may be a bug in the CUDA code, but I thought it worth mentioning. 

As an example of these discrepancies, I've attached a sample run script:

[bad_energy_decomposition.zip](https://github.com/pandegroup/openmm/files/962051/bad_energy_decomposition.zip)

**Comment by mvanvleet** [comment] 2017-05-03 15:33
Any insight into this yet, either for the strange energy decompositions or for the discrepancies between CUDA and CPU platform?

**Comment by mvanvleet** [comment] 2017-05-04 15:01
I've realized that this problem isn't necessarily specific to NonbondedForce and AmoebaMultipoleForce; rather, it seems to crop up (without patterns that I've yet been able to identify, though AmoebaMultipoleForce seems to be a common thread) when I use multiple forces in conjunction with one another. Here's an example of failures that I see when combining some bonded forces with CustomManyParticleForce, CustomHbondForce/CustomNonbondedForce, and AmoebaMultipoleForce:

[simultaneous_forces_bug.zip](https://github.com/pandegroup/openmm/files/976570/simultaneous_forces_bug.zip)

```
1.) CustomNonbondedForce, CPU platform
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x208c840> > 9.11265862304 kJ/mol
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x208c780> > -4414.48712296 kJ/mol
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x208c9f0> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x208c8a0> > 275.129899246 kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x208c7e0> > 0.0 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x208c7b0> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x208cf00> > -3413.26533522 kJ/mol
-7543.5099003 kJ/mol
----
2.) CustomNonbondedForce, CUDA platform
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x3236f90> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x3236930> > 0.0 kJ/mol
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x3236960> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x3236840> > 281.482862429 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x3236a80> > 0.0 kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x32368d0> > -4405.36657081 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x3236810> > -3413.33501018 kJ/mol
-7537.21871856 kJ/mol
----
3.) CustomHbondForce, CPU platform
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x2a0d6f0> > 0.0 kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x2a0d300> > 0.0 kJ/mol
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x2a0d2a0> > 9.11265862304 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x2a0d7b0> > -3413.26533522 kJ/mol
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x2a0d330> > -4414.48716746 kJ/mol
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x2a0d270> > 144.80521013 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x2a0d540> > 0.0 kJ/mol
-7673.83463392 kJ/mol
----
4.) CustomHbondForce, CUDA platform
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x1bd2810> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x1bd2390> > -1272.22492148 kJ/mol
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x1bd22d0> > -4414.48727207 kJ/mol
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x1bd25a0> > 148.048629422 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x1bd2750> > 0.0 kJ/mol
<simtk.openmm.openmm.MonteCarloBarostat; proxy of <Swig Object of type 'OpenMM::MonteCarloBarostat *' at 0x1bd22a0> > 0.0 kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x1bd2300> > 9.1197838889 kJ/mol
-5529.54378023 kJ/mol
----
```
I obtained these results by running single-point energy calculations on a snapshot of a liquid. I tested use of both CustomHbondForce and CustomNonbondedForce (using identical energy expressions within each force such that they *should* return the same energy, and *do* return the same energy so long as I only evaluate the energies of dimers), and also tested the CPU/CUDA platforms.

I see three problems emerge when combining these forces together. 
1. When using CustomNonbondedForce (simulations 1. and 2.), the energies returned by the CPU platform and the CUDA platform are mostly the same (CustomManyParticleForce may be off by a few kJ/mol, which is concerning), but the energy decomposition is incorrect for the CUDA platform. 
2. Upon switching to CustomHbondForce (you can validate from the CPU platform results that CustomNonbonded and CustomHbond are returning the same energies), CustomManyParticleForce suddenly returns a very different value for the energy. 
3. Most importantly, when using the CUDA platform and CustomHbondForce (simulation 4), the resulting energy is dramatically different than for any of the other three simulations.

I'm unfortunately under a deadline to run some production simulations with the force fields from simulation 4, so any help in debugging these problems ( @peastman, will you have time for this in the next 10 days?) is supremely appreciated.

**Comment by peastman** [comment] 2017-05-04 16:45
I haven't had a chance to look at it yet, but within the next 10 days should be doable.

**Comment by peastman** [comment] 2017-05-05 18:17
Here's the problem you're running into: on the CUDA platform, NonbondedForce and AmoebaMultipoleForce both store the particle charges in the same place.  They were really never meant to be used together.  They'll still "work", in some sense, as long as they both have the same charge for every atom.  But if they have different charges, as in your case, then whichever one gets initialized second will overwrite the charges from the first one.

I don't really have a good solution for this.  Changing where they store charges would be a big change and would hurt performance.  Using a CustomNonbondedForce for LJ is an easy fix, except that then you can't use LJPME.  Perhaps I could make it so that if NonbondedForce sees all your charges are 0, it omits storing them?  It already ifdefs out the part of the kernel dealing with Coulomb forces in that case, so it doesn't care what values get stored then.

**Comment by jchodera** [comment] 2017-05-05 18:47
The code should *certainly* throw an `Exception` right now if they cannot be used together, though I could imagine many cases in which one would want to use LJPME + `AmoebaMultipoleForce` for advanced (post-AMOEBA) forcefields, so it would be wonderful to have this capability.

**Comment by mvanvleet** [comment] 2017-05-05 19:10
Two things:

1. I agree with @jchodera that LJPME + `AmoebaMultipoleForce` is highly desirable. I'll leave it up to the developers how best to enable this capability, however it's probably worth mentioning that many of these 'post-AMOEBA' forcefields (such as my own) use neither point charges nor a 1/r^12 repulsive term, such that (for these post-AMOEBA) force fields, using `NonbondedForce` just for dispersion-PME feels clunky on several levels. As a future enhancement, it would be nice to not have the dispersion-PME capabilities tied to the Lennard-Jones forcefield.

2. @peastman, it makes sense that `AmoebaMultipoleForce` and `NonbondedForce` would subtly conflict in this way, and I think this elucidates the problem I'm seeing when I use these two forces together on the same platform. However, I don't think this explains the inconsistencies I'm seeing when combining other forces ([see my previous comment](https://github.com/pandegroup/openmm/issues/1794#issuecomment-299211825)). Do you have any idea what might be going on there?

**Comment by peastman** [comment] 2017-05-09 17:59
The incorrect energy decomposition is because you don't call `forcegroupify()` until after you've already created the Simulation.  To work correctly, force groups need to be set before the Simulation/Context is created.

I'm looking into the other issues now.

**Comment by peastman** [comment] 2017-05-09 18:13
When using CUDA, the energy returned by CustomManyParticleForce seems to vary slightly from one run to another:

```
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x7fe9447ebe70> > 299.597913706 kJ/mol
...
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x7f21ebf1fe70> > 298.546919621 kJ/mol
...
<simtk.openmm.openmm.CustomManyParticleForce; proxy of <Swig Object of type 'OpenMM::CustomManyParticleForce *' at 0x7fd0cf5b2e70> > 296.22738849 kJ/mol
```

It doesn't seem to be a precision issue, since it still happens in double precision mode.  I'll try to figure out what's going on with that.

I can't reproduce your third problem.  All forces other than the CustomManyParticleForce are producing identical energies in the two versions of the script.

**Comment by peastman** [comment] 2017-05-09 22:51
See #1810.

**Comment by mvanvleet** [comment] 2017-05-10 05:11
I checked out your code from [#1810](https://github.com/pandegroup/openmm/pull/1810), leading to the following two effects:
1. As expected, this fixes the small discrepancies I was seeing in CustomManyParticleForce
2. Somewhat disconcertingly, I now also cannot reproduce the third problem I was seeing. Whatever that problem was, it's gone now!

I am still seeing one lingering problem with my test systems, which is that CustomManyParticleForce appears to be returning incorrect energies when used in conjunction with CustomHbondForce. For the test systems I gave you, if I calculate CustomManyParticleForce for any force field that doesn't employ CustomHbondForce, I now get a consistent energy of 275.130 kJ/mol, independent of platform. As soon as I add in the CustomHbondForce, however, this number drops to 144.805 kJ/mol, also independent of platform. (The test systems I gave you above should be able to reproduce this problem, but let me know if they don't). Is this a bug with CustomManyParticleForce or a user error on my part?

As always, I highly appreciate the time and effort you've spent diagnosing these problems.

**Comment by peastman** [comment] 2017-05-12 21:55
This is happening because the CustomHbondForce and CustomManyParticleForce each use a global parameter called `scale`.  When you do that, it means they both depend on exactly the same parameter.  All global parameters get stored in the Context, referenced by name.  But in this case you meant for them to be two different parameters with different values, so you need to give them unique names.

**Comment by peastman** [comment] 2020-12-01 18:46
I believe this is now fixed.

**Closed by peastman** 2020-12-01 18:46 UTC
