### ISSUE TITLE
SWIG Typemapping fails on NumPy int scalars

### ISSUE THREAD

**Issue by tristanc1** [openmm/openmm#1880] opened 2017-08-24 17:33 UTC
This is more of a really annoying bug in SWIG itself, and only in some environments: for any wrapped function that takes scalar integer arguments, attempting to provide them directly from a Numpy int array fails. For example, if b_force is a CustomBondForce that takes two indices and a tuple of two doubles:
```
indices = numpy.array([1,2], int)
params = (1.0, 2.0)
b_force.addBond(*indices, params)

NotImplementedError: Wrong number or type of arguments for overloaded function 'CustomBondForce_addBond'.
Possible C/C++ prototypes are:
OpenMM::CustomBondForce::addBond(int,int,std::vector< double,std::allocator< double > > const &)
OpenMM::CustomBondForce::addBond(int,int)

indices = indices.tolist()
b_force.addBond(*indices, params)

# Works fine, but gets old in a hurry
```

See the "NumPy Array Scalars and SWIG" section of https://docs.scipy.org/doc/numpy/reference/swig.interface-file.html. From my experience in another project, I'd recommend not quite following their instructions. Renaming pyfragments.swg to pyfragments.i and then explicitly importing it after numpy.i avoids a lot of headaches.

**Comment by peastman** [comment] 2020-12-01 21:12
Closing this since it's a duplicate of #2831.

**Closed by peastman** 2020-12-01 21:12 UTC
