### ISSUE TITLE
Abort trap: 6 on OpenCL platform

### ISSUE THREAD

**Issue by andrrizzi** [openmm/openmm#1588] opened 2016-09-19 20:20 UTC
This script crashes randomly (i.e. at seemingly random values of `i`) with `Abort trap: 6` on my OSX laptop with `openmm 7.0.1` (and `openmmtools 0.8.2`)

``` python
from simtk import openmm, unit
from openmmtools import testsystems

test = testsystems.HostGuestExplicit()
platform = openmm.Platform.getPlatformByName('OpenCL')
for i in range(30):
    integrator = openmm.VerletIntegrator(1.0 * unit.femtoseconds)
    context = openmm.Context(test.system, integrator, platform)
    context.setPositions(test.positions)
    context.getState(getEnergy=True)
    del context, integrator
```

as far as I can tell, `Reference` and `CUDA` platforms work fine.

**Comment by jchodera** [comment] 2016-09-20 12:06
Which `osx` version and laptop are you using, @andrrizzi?

My `osx` 10.9.5 MacBook Air doesn't have the `OpenCL` platform available, and I can't get a crash out of `linux` with a GTX-680 driver version 352.39.

**Comment by andrrizzi** [comment] 2016-09-20 14:33
Sorry! I'm using `10.10.5` on MacBook pro. And you are right, this script doesn't crash on the cluster for example, although some other code did with the same error. It's not a problem with conda installation because I reinstalled miniconda from scratch. I'll try to see if it is only my hardware/drivers.

**Comment by andrrizzi** [comment] 2016-09-20 15:47
Correction. I can reproduce it on the cluster but only on `CPU` platform. The scripts terminates but I receive a `exceeded MEM usage soft limit` at the end and the interactive session shuts down.

**Comment by peastman** [comment] 2016-09-21 17:21
What if you add a call to `gc.collect()` after deleting the context and integrator?  Just to make sure the objects have really gotten deleted.

**Comment by jlmaccal** [comment] 2016-09-21 18:13
Something fishy is going on with object ownership. I think it's probably worth adding debugging print calls to a bunch of the constructors and destructors to understand what's going on (likely some weird interaction between swig / python / C++). Looking at the swig documentation, there are definitely some complexities to getting memory management right.

Unless there are reference cycles, the calls to `del` and `gc.collect()` should be unnecessary. Python (specifically CPython, but that's all we support) is reference counted, so as soon as `integrator` and `context` are assigned on each iteration of the loop, the previous objects should immediately be cleaned up. The garbage collector only enters the picture if there are cycles and there generally should be no need to call it explicitly. 

It also seems weird that 30 copies of a context / integrator for a moderately sized system would be enough to hit memory usage limits.

@leeping had issues with this as well, so it might be worth trying to track down what the actual problem is, rather than just find band aids that make it (sort of) work.

**Comment by andrrizzi** [comment] 2016-09-21 20:09
> What if you add a call to gc.collect() after deleting the context and integrator?

Sorry for not mentioning this before. I did play a little with the garbage collector but it didn't change anything on my laptop with platform `OpenCL`. In fact, the list `gc.garbage` was constantly empty (checked right after deleting `context` and `integrator`), so either `gc` was very quick to destroy them everytime, or the objects never got their reference count to 0.

I didn't try on the cluster with `CPU` but I can try that too if you want.

**Comment by jchodera** [comment] 2016-09-21 20:16
Oh, I already tried running the minimal script on a `linux` system with `CPU` and there are no problems.

**Comment by jchodera** [comment] 2016-09-21 20:17
I think the memory issue is something that we should worry about, but is a red herring for the `Abort trap`

**Comment by peastman** [comment] 2016-09-22 17:43
I adding debugging code to print out a message when the `Context` and `Integrator` destructors are called.  I also added `print(i)` at the start of the loop.  This confirms that the C++ objects are properly deleted at the end of each iteration:

 ```
0
context deleted
integrator deleted
1
context deleted
integrator deleted
...
29
context deleted
integrator deleted
```

I also tried removing the `del context, integrator` line.  Without that, everything still gets deleted properly, just delayed by one iteration:

```
0
1
context deleted
integrator deleted
...
29
context deleted
integrator deleted
context deleted
integrator deleted
```

That's what you'd expect, since the objects created in one iteration don't get deleted until the variable is reassigned during the next iteration.  All the garbage collection and object management looks like it's working correctly.

**Comment by jlmaccal** [comment] 2016-09-22 17:53
Hmm… that’s good, but it’s puzzling what the problem could be.

I wonder if things are getting copied? Could you add similar debugging to all of the constructors? Are we using any compiler-generated copy constructors?

**Comment by andrrizzi** [comment] 2016-09-22 17:55
Thanks! I'll try to compile OpenMM from source and debug this more on my laptop over the weekend. Maybe it really is a problem with my hardware.

**Comment by peastman** [comment] 2016-09-22 18:16
Good thought.  But no, that doesn't seem to be the problem:

```
0
integrator created
context created
context deleted
integrator deleted
1
integrator created
context created
context deleted
integrator deleted
```

**Comment by jlmaccal** [comment] 2016-09-22 18:26
Hmm…

It seems like either context or integrator (or one of the objects they create) must not be cleaning up properly. There seem to be problems whenever contexts are created and destroyed repeatedly.

**Comment by andrrizzi** [comment] 2016-09-22 22:42
One important piece of information that I just noticed I forgot to share (sorry again), is that the crash always happens inside `context.getState(getEnergy=True)`. I have had also rare random crashes on `CPU` on my platforms since I opened the thread.

**Comment by jchodera** [comment] 2016-09-24 18:33
Is this something `valgrind` might be able to help catch?

**Comment by andrrizzi** [comment] 2017-04-06 05:00
Sorry for the very long inactivity on this. I had more time to debug this, and I isolated the `Abort trap: 6` error to [this line](https://github.com/pandegroup/openmm/blob/master/platforms/opencl/src/OpenCLKernels.cpp#L151). This is still a problem on my MacBook pro on the last OpenMM installed from source. I'll keep you updated if I figure out something else.

**Comment by peastman** [comment] 2020-12-01 01:11
Closing this old issue, since we never had enough information to reproduce it.

**Closed by peastman** 2020-12-01 01:11 UTC
