### ISSUE TITLE
Problem with Amber-prepared truncated octahedral/triclinic system

### ISSUE THREAD

**Issue by gitkol** [openmm/openmm#2361] opened 2019-08-06 13:54 UTC
Hi, I have a bizarre problem and I wonder if you can suggest something how to debug it. I prepared a system (protein+co-factor) with Amber using a truncated octahedral simulation box. I have successfully read the parm7 and rst7 input files in OpenMM (verified that the box vectors were triclinic) and started a vanilla simulation to test the system. I noticed, however, that after proper minimization the simulation invariably crashed with "Exception: Particle coordinate is nan." I started to experiment with more or less stringent simulation parameters that have always worked just fine with orthorhombic systems, but even with the most stringent settings the simulation crashed after many millions of MD steps, which is, I guess, indicating that this is not an equilibration issue. Unfortunately, I cannot see any smoking gun as to why the simulations end up with these nan coordinates. However, I ran a sanity check by preparing the exact same system with Amber except that I built an orthorhombic box and ran the exact same simulations with OpenMM, and found that all of them without exception ran just fine and never crashed. Even simulations with HMR and MTS and a loose Ewald tolerance are running and seem totally healthy. It seems that there might be something about the truncated octahedral/triclinic simulation box that is ultimately causing the crashes, but I have no idea how to debug it since I have not found any signs of bad behavior.

Thanks a million for any suggestions.

Best regards,

   Istvan

**Comment by peastman** [comment] 2019-08-06 18:50
Nothing obvious comes to mind.  The fact that it successfully runs for millions of steps suggests some rare event is causing it.

A slow but straightforward way of debugging issues like this is to use the approach described in https://github.com/openmm/openmm/issues/2026#issuecomment-378676641.  It tries to catch the system just at the moment it blows up, then write out a series of states leading up to that point.  It makes things run *very* slowly though.  So first you might want to see if you can find a way to reproduce it in only a small number of steps.  Run a regular simulation, saving a checkpoint every 10,000 steps or so.  Once it crashes go back to the last checkpoint and see if you can reproduce it by starting from there.

If you're using the CUDA platform, specify the property `{'DeterministicForces':'true'}` when creating your Simulation.  That increases the chance you'll be able to reproduce it from a checkpoint.

**Comment by gitkol** [comment] 2019-08-07 03:14
Thank you, I'll try this. Out of curiosity, is there a way to set a random seed to exactly reproduce a simulation from the start and not from a checkpoint?

**Comment by jchodera** [comment] 2019-08-07 07:23
Tagging @andrrizzi, who has also run into this issue with octahedral/triclinic systems.

@gitkol: Which OpenMM version were you using?

**Comment by gitkol** [comment] 2019-08-07 12:30
I am using 7.3.

   Istvan

**Comment by gitkol** [comment] 2019-08-07 15:14
To be precise, this is the download file I used openmm-7.3.1-py27_cuda100_rc_2.tar-2.bz2.

**Comment by peastman** [comment] 2019-08-07 15:18
Call `setRandomNumberSeed()` on the integrator.  See http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.LangevinIntegrator.html#simtk.openmm.openmm.LangevinIntegrator.setRandomNumberSeed for some details about how it is interpreted.  If you have a barostat, also call `setRandomNumberSeed()` on it.

**Comment by stxkol** [comment] 2019-09-18 16:42
I tried reproducing the crash from the checkpoint file as you suggested, but there must be some non-deterministic factor present, because I can't reproduce it. I mean after restarting the job from the checkpoint file, it does crash at some point, but not within 10,000 steps (I write out the checkpoint file every 10,000 steps in the first place). I guess, there is very little I can do at this point, maybe I'll try NVT to factor out at least one parameter.

**Comment by gitkol** [comment] 2019-09-19 22:36
Yes, when running NVT simulation I can reproduce the crash from the checkpoint file and should be able to use Peter's code to further narrow it down.

**Comment by gitkol** [comment] 2019-09-30 22:09
OK, I generated the states for the last 30 steps before the crash, did find the problem but I still have no clue. The cause of the crash is that a chlorine counter ion gets too close to a water molecule. The distance between Cl- and O is 1.6 Angs and the distance between Cl- and H1 is 0.6 Angs just before OpenMM crashes with a nan. Even just a single time step before the last everything seems to be OK, forces, velocities are fine (or at least not huge) and, then, at the next and final step Cl- and the HOH get too close and immediately forces are huge between them and velocities skyrocket as well, only for these two entities. The rest of the system is perfectly fine. Here are the last 3 time steps.

```
> State 27
> <?xml version="1.0" ?>
> <State openmmVersion="7.3" time="75249.41601166032" type="State" version="1">
> 	<PeriodicBoxVectors>
> 		<A x="8.40356629" y="0" z="0"/>
> 		<B x="-2.801188537313168" y="7.922958359656429" z="0"/>
> 		<C x="-2.801188537313168" y="-3.9614787003670537" z="6.861483489405759"/>
> 	</PeriodicBoxVectors>
> 	<Parameters AndersenCollisionFrequency="1" AndersenTemperature="300"/>
> 	<Energies KineticEnergy="104244.4320598625" PotentialEnergy="-494589.9043172826"/>
> 	<Positions>
> 	Cl-	<Position x="-8.033673432672416" y="2.2081288221423616" z="24.434763989871676"/>
> 	O	<Position x="34.04133781314357" y="-9.884309130438712" z="-23.730268598595792"/>
> 	H1	<Position x="34.02520495373485" y="-9.801619160554555" z="-23.68483273300281"/>
> 	H2	<Position x="34.13314046269119" y="-9.90422493976126" z="-23.7118851215201"/>
> 	<Velocities>
> 	Cl-	<Velocity x=".05995634823036703" y="-1.372047188039024" z="-.4040609074825148"/>
> 	O	<Velocity x="-.15708944392549112" y="2.498773269413716" z=".8159130945402974"/>
> 	H1	<Velocity x="-1.4196788964694922" y="2.136545114944155" z="1.0268354846953966"/>
> 	H2	<Velocity x=".155031511598246" y="3.8684010255154324" z=".7410475695587794"/>
> 	<Forces>
> 	Cl-	<Force x="1162.0187381110154" y="-1138.2800451740623" z="-930.2753852009773"/>
> 	O	<Force x="-519.5705902539194" y="-91.74123160983436" z="17.054982990026474"/>
> 	H1	<Force x="-245.39509072504006" y="1562.6739298608154" z="990.9614195413888"/>
> 	H2	<Force x="248.28228984586895" y="259.40479847602546" z="140.3388132462278"/>
> 
> State28
> <?xml version="1.0" ?>
> <State openmmVersion="7.3" time="75249.42401166032" type="State" version="1">
> 	<PeriodicBoxVectors>
> 		<A x="8.40356629" y="0" z="0"/>
> 		<B x="-2.801188537313168" y="7.922958359656429" z="0"/>
> 		<C x="-2.801188537313168" y="-3.9614787003670537" z="6.861483489405759"/>
> 	</PeriodicBoxVectors>
> 	<Parameters AndersenCollisionFrequency="1" AndersenTemperature="300"/>
> 	<Energies KineticEnergy="104233.37352198639" PotentialEnergy="-494622.4418043797"/>
> 	<Positions>
> 	Cl-	<Position x="-8.032057467048652" y="2.1958801571805306" z="24.430444497455973"/>
> 	O	<Position x="34.0389853360857" y="-9.860748808565365" z="-23.72133013652442"/>
> 	H1	<Position x="34.01245355497232" y="-9.782923798791455" z="-23.672323498209092"/>
> 	H2	<Position x="34.13312725973401" y="-9.868007840637564" z="-23.7056163585096"/>
> 	<Velocities>
> 	Cl-	<Velocity x=".37065607683393403" y="-1.7743823085913368" z="-.7631757416509132"/>
> 	O	<Velocity x="-.5132311667833647" y="3.5857104085840796" z="1.539900715972855"/>
> 	H1	<Velocity x="-1.3796083455750714" y="2.749561949022029" z="2.398696668653494"/>
> 	H2	<Velocity x="-.30357201066434747" y="4.87091579191334" z=".8775283300048724"/>
> 	<Forces>
> 	Cl-	<Force x="1653.247056646971" y="-2629.9467871300876" z="-2403.636640049517"/>
> 	O	<Force x="-514.626875010319" y="66.22498571220785" z="86.71922014653683"/>
> 	H1	<Force x="-485.4228192376904" y="2849.736276866868" z="1998.0969616714865"/>
> 	H2	<Force x="-54.32283843122423" y="319.28896455373615" z="202.53686944348738"/>
> 
> State 29
> <?xml version="1.0" ?>
> <State openmmVersion="7.3" time="75249.43201166032" type="State" version="1">
> 	<PeriodicBoxVectors>
> 		<A x="8.40356629" y="0" z="0"/>
> 		<B x="-2.801188537313168" y="7.922958359656429" z="0"/>
> 		<C x="-2.801188537313168" y="-3.9614787003670537" z="6.861483489405759"/>
> 	</PeriodicBoxVectors>
> 	<Parameters AndersenCollisionFrequency="1" AndersenTemperature="300"/>
> 	<Energies KineticEnergy="3024708.424847007" PotentialEnergy="-440121.5291760103"/>
> 	<Positions>
> 	Cl-	<Position x="-8.027301862087661" y="2.178409793054234" z="24.421423233731677"/>
> 	O	<Position x="34.031935456106325" y="-9.824220618414966" z="-23.703312838886912"/>
> 	H1	<Position x="34.007432526113405" y="-9.751682505385705" z="-23.645865935278056"/>
> 	H2	<Position x="34.12749342128599" y="-9.827247581128898" z="-23.69864047954948"/>
> 	<Velocities>
> 	Cl-	<Velocity x="-61.62601896520093" y="175.76578981966756" z="140.85265815026122"/>
> 	O	<Velocity x="134.53585997811993" y="-353.3442424880256" z="-283.01696842134896"/>
> 	H1	<Velocity x="-93.43428528810384" y="-393.9442424444034" z="-328.98798148015806"/>
> 	H2	<Velocity x="132.9800659252756" y="-171.02631034788607" z="-133.08469263174993"/>
> 	<Forces>
> 	Cl-	<Force x="-1105167.8060550913" y="3158707.352121383" z="2520707.3406732827"/>
> 	O	<Force x="1110078.698006259" y="-3169974.9248327203" z="-2530531.178754002"/>
> 	H1	<Force x="-3946.5953453315888" y="11561.071094777435" z="9126.841797176749"/>
> 	H2	<Force x="-482.8815143466927" y="556.2857914301567" z="407.7815601825714"/>
> 
```

I attached a screenshot showing the progression how the Cl- is trying to fuse with H1. The force field shouldn't allow this. What is totally unclear is that the huge force is the repulsion between Cl- and O, so how come the two are approaching each other to fatal proximity? This doesn't make any sense.

Of course, I cannot be sure that all the other crashes were like this, but one thing is for sure, multiple systems where the orthorhombic simulation cell works fine, the triclinic crashed every single time after shorter or longer time periods, sometimes after close to 10 million time steps. Is there any way the triclinic cell might have anything to do with this?

Thanks for any suggestions, the triclinic cell would make the simulation significantly faster.

   Istvan
![progression-to-crash](https://user-images.githubusercontent.com/42390762/65920152-3d124b80-e3ac-11e9-917a-16ac7b1851a7.png)

**Comment by peastman** [comment] 2019-09-30 23:43
That's great!  I think we're very close to tracking it down.

First a bit of background.  Many water models don't put a Lennard-Jones term on the hydrogens.  Personally I think that's crazy, and I don't know any good reason for it, but that's how they're defined.  That means the energy landscape is full of infinite holes.  If a negative atom gets too close to a water hydrogen, the attraction between them becomes infinite as they approach each other.  That isn't usually a problem because the oxygen's LJ repulsion extends over the hydrogens.  There's a large barrier that has to be crossed to reach the infinite hole.  But that just means it will be infrequent.  There's always a probability of something managing to get over the barrier, and then the system blows up.

So in part I think that's what's happening.  But using a triclinic box shouldn't make any difference.  In this case it does appear to make a difference, which suggests something more is going on.

Is it possible for you to post or send me the files needed to reproduce this?  I'd like to examine the last few steps and see exactly what interactions are acting on each of the atoms involved at each step.

**Comment by peastman** [comment] 2019-10-01 18:13
I don't have a 1080 Ti, so I can't run from the checkpoint.  But if you post the 30 serialized states, I can just load them directly and see what forces are present in each one.

**Comment by gitkol** [comment] 2019-10-01 18:21
Absolutely, can you suggest a good way to post them? Even gzipped it is over 100 MB and GitHub allows only up to 10 MB.

**Comment by peastman** [comment] 2019-10-01 19:29
Upload them to https://send.firefox.com/.  Post the link and I'll download them.

**Comment by gitkol** [comment] 2019-10-01 19:31
https://send.firefox.com/download/70f655100d3895df/#KE3undqJsn0WOdlYlC3PhQ

**Comment by peastman** [comment] 2019-10-01 19:34
Got it, thanks!

**Comment by peastman** [comment] 2019-10-01 21:53
This definitely seems to be a stochastic problem.  If I load up the very last state I can see that there's a very large force.  But if I load the state immediately before it and run from there, it works without problem.  There's nothing in the second to last state that causes a problem.  Usually it works fine.  The problem first appears in the very last state, presumably because of a random kick from the thermostat.

I notice that you're really pushing the limits of stability.  You have a MTSIntegrator that computes reciprocal space nonbonded forces every 8 fs, and everything else every 4 fs.  That's a much larger time step than people normally use.  That could easily lead to instability like you're seeing, and also is probably leading to inaccurate sampling.  I would try cutting the step size in half.

**Comment by gitkol** [comment] 2019-10-01 22:01
Thanks, Peter. This system was part of an investigation into how far we can push the limit. As you point out this is a setting that just makes it. I did a bunch of simulations with no MTS, no HMR, 1 fs time step, and every single time they crashed with the triclinic cell but were running OK with the orthorhombic cell. I really don't know what to say, I guess, I'll start over with the investigation, but now I know how to debug the crashes. Could you show me the code that you use to run the simulation from the state xml files?

Thanks a million for looking into this.

**Comment by peastman** [comment] 2019-10-01 22:44
I'm really puzzled then.  Let me see if I can get this to happen on my own computer.  How long do you typically have to run?

The code to run from the XML file is trivial:

```python
with open('states/state28.xml') as input:
    state_in = XmlSerializer.deserialize(input.read())
context.setState(state_in)
print(context.getState(getEnergy=True).getPotentialEnergy())
for i in range(30):
    integrator.step(1)
    print(context.getState(getEnergy=True).getPotentialEnergy())
```

**Comment by gitkol** [comment] 2019-10-01 23:58
Thanks for the script, I'll use it. I really appreciate your help, but I don't want to over use your time. Let me rerun my test simulations and I'll pass you my job files when I find a case where the crash occurs quickly.

**Comment by peastman** [comment] 2019-10-02 00:21
Don't worry about my time.  And if there's a bug somewhere, I want to find it!  This is my job, after all.

**Comment by gitkol** [comment] 2019-10-02 15:34
There is definitely something going on. I ran 12 tests overnight, 7 still running. I summarize the results below. 1) HMR, MTS, dt=8 fs   2) HMR, no MTS, dt=4fs   3) HMR, no MTS, dt=2 fs   4) no HMR, MTS, dt=4fs   5) no HMR, no MTS, dt=2 fs   6) no HMR, no MTS, dt=1fs. ewaldErrorTolerance = 5e-4, nonbondedCutoff = 0.9*nanometers, NVT simulation with Andersen thermostat.
```
orthorhombic cell
        1        2        3        4        5        6
status  running  running  running  running  running  running
steps   9051000  15849000 15923000 10221000 14740000 10299000

truncated octahedral cell
        1        2        3        4        5        6
status  crashed  crashed  complete crashed  crashed  crashed
steps   9363000  16101000 20000000 8280000  5168000  4112000

```
As you can see, all of the orthorhombic jobs are running while 5 of the 6 truncated octahedral jobs crashed with "Particle coordinate is nan." This is pretty compelling. I set the maximum number of time steps to 20 million, that should be more than enough to deem the simulation stable. I am quite sure all orthorhombic jobs will get there and I will report it when they do. Surprisingly, though, run3 with the truncated octahedral cell did complete without incidents.

If we assume that octa or ortho should absolutely make no difference for MD and that these crashes are all stochastic in nature, I wonder whether the problem is with the minimizer. What if the minimizer does something funny with truncated octahedral cells and injects a sort of time bomb in the simulation that later on blows up.

Not sure how to interpret why the most conservative HMR octa run did complete while all others crashed, but maybe that's a red herring and run3 just happened to be defused before the bomb went off.

**Comment by peastman** [comment] 2019-10-02 18:01
I have a simulation running now.  I'll let you know what I find.

> What if the minimizer does something funny with truncated octahedral cells and injects a sort of time bomb in the simulation that later on blows up.

I don't think that's likely.  Minimization problems usually lead to immediate crashes.  By the time it's gone through a million steps, any memory of what the minimizer did is long since forgotten.

**Comment by peastman** [comment] 2019-10-02 19:15
I managed to reproduce the error.  I'm investigating now.

**Comment by gitkol** [comment] 2019-10-02 19:33
I am "glad". :) In the meantime 3 of the 6 orthorhombic simulations completed without incident and the others are still running.

**Comment by peastman** [comment] 2019-10-02 23:25
Found it!  The fix is easy, but it was a lot of work to track down!  I'll get a PR in with the fix shortly.

The problem was in the code that builds neighbor lists.  It deals with blocks of 32 atoms.  To quickly identify atoms within the cutoff, it applies three levels of filtering.

1. Compute the closest distance between the bounding boxes of two blocks.  If it's beyond the cutoff, we exclude all interactions between their atoms without looking any further.
2. For each atom in one block, compute the distance to the bounding box of the other block.  If it's beyond the cutoff, we can exclude all interactions involving that atom.
3. Compute the atom's distance to every atom in the other block to see if any of them are actually within the cutoff.

Now, how do we compute those distances when using a triclinic box?  To compute the nearest distance between two points, you need to consider 27 possible displacements corresponding to different periodic copies, which is really slow.  Instead we use a different approach that is much faster but has a limitation: it only works correctly if the nearest copy is less than half a box width away.  Otherwise it might pick the wrong copy, one that isn't actually the nearest one.  When computing distances between atoms that's fine: the cutoff is limited to half the box width, so *if* any copy is within the cutoff distance, *then* we're guaranteed to find it.

But it's more complicated when looking at bounding boxes rather than points.  In that case you compare the distance to the box center against a cutoff padded by half the bounding box width.  Most bounding boxes are quite small, but a fraction of them are much larger.  So very occasionally, that turns out to be more than half the periodic box width, and in that case the distance calculation isn't guaranteed to be correct.

OK, we already knew about that problem and it had a check for that situation.  But it only applied the check in step 1 above, not in step 2.  So in very rare cases when using triclinic boxes, step 2 would throw out an atom even though that atom was actually within the cutoff distance of an atom in the other block.

Whew!

**Comment by gitkol** [comment] 2019-10-03 00:08
OMG! This was an extremely subtle bug then, after all. Glad I insisted and
thanks a million to fix it. Let me know when I can download a fixed version.

Best,

   Istvan

**Closed** 2019-10-04 17:25 UTC

**Comment by peastman** [comment] 2019-10-04 17:29
Ok, I've hopefully got this really fixed.  It successfully ran for 20 million steps without crashing.  You can get the fixed code from the repository, or if you wait until tomorrow it will be in the nightly build.  You can install that with `conda install -c omnia-dev openmm`.  And I'm hoping to release 7.4.1 pretty soon, which will include the fix.

**Comment by gitkol** [comment] 2019-10-04 17:40
Fantastic, thanks a million!
