### ISSUE TITLE
Unstable Energies with NPT Dynamics in OpenMM 8.1.0

### ISSUE THREAD

**Issue by shriramc1** [openmm/openmm#4360] opened 2023-12-17 22:24 UTC
I'm observing unstable energies in OpenMM 8.1, where the same simulation run in OpenMM 8.0 and 7.7 don't have these instabilities. I've also included a plot of the potential energy and the instantaneous temperature, which highlight these differences.

I'm running NPT dynamics in explicit solvent for a protein domain, where the input files were prepared using Amber tleap. The simulation uses a LangevinMiddleIntegrator (T=300K, dt = 2 fs and friction = 1 ps^-1) and a MonteCarloBarostat. I'm also attaching a zip file containing the minimal files needed to reproduce the plots, where amber_test.py is the python file that needs to be run.

![temperature](https://github.com/openmm/openmm/assets/25778144/b3bc5535-fc7d-4bc2-a533-4191107ced92)
![pe](https://github.com/openmm/openmm/assets/25778144/eb5b6b13-0784-4fbc-8b4a-94a2cf5b930a)
[121823OpenmmVersionTest.zip](https://github.com/openmm/openmm/files/13697972/121823OpenmmVersionTest.zip)

**Comment by peastman** [comment] 2023-12-19 18:12
Thanks for the test case.  I can reproduce it, but it's nondeterministic.  If I use settings that should produce completely deterministic behavior and then run it twice, the two trajectories perfectly match for a while.  Then after some tens of thousands of steps, they suddenly diverge.  The point at which they diverge is different every time, so it's nondeterministically nondeterministic, if you know what I mean.  Which makes it harder to debug.

It seems to be related to the pressure control.  If I remove the barostat, the behavior is completely deterministic.  Hopefully that's a clue that can lead us to the problem.

**Comment by peastman** [comment] 2023-12-20 17:41
I figured it out.  The fix is in #4364.

**Closed** 2023-12-20 20:59 UTC
