### ISSUE TITLE
How to track progress of minimization?

### ISSUE THREAD

**Issue by aizvorski** [openmm/openmm#3896] opened 2023-01-10 02:56 UTC
I'd like to monitor what the minimizer is doing, in terms of the energy and gradient norm at each step, and the number of steps total before it finishes (maybe there are some other specifically LBFGS-related metrics).

Looking at [LocalEnergyMinimizer.minimize()](
http://docs.openmm.org/latest/api-python/generated/openmm.openmm.LocalEnergyMinimizer.html#openmm.openmm.LocalEnergyMinimizer.minimize) and similarly [Simulation.minimizeEnergy()](http://docs.openmm.org/latest/api-python/generated/openmm.app.simulation.Simulation.html#openmm.app.simulation.Simulation.minimizeEnergy) it seems there is no return value, and also no callback.

(a) Is it possible to add a return value from minimize()?  Perhaps something like a list of `{'step':step, 'energy':energy, 'gradient':gradient}`
(b) Is it possible to add an optional callback which gets this info during minimization for realtime monitoring?  (eg to print out progress)

Example usage:
```
def print_progress(step, energy, gradient):
    print(step, energy, gradient)

mm.LocalEnergyMinimizer.minimize(context, callback=print_progress)
```

P.S. This is analogous to the callback parameter in [scipy.optimize.minimize()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html).  It seems the callback gets an [OptimizeResult](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html) and the return value of minimize() is also an OptimizeResult.  Those have a bit more info than what I suggested; it includes the x (current solution, here coordinates) and even the inverse hessian.  This may be a good API to copy since anyone using scipy would already know it.

**Comment by peastman** [comment] 2023-01-10 16:34
This is a duplicate of #1155.  See the discussion there for details.  The short answer is that we'd like to add some way of monitoring progress, but it's complicated.  The process works by replacing all constraints with harmonic restraints, then minimizing, then checking whether the constraints are satisfied, then tightening the restraints if they aren't, then possibly doing a bit more minimization or possibly going back to the beginning and restarting the whole minimization from scratch.  So what do you report and when?

I'm going to close this as a duplicate so we keep the discussion in one place.

**Closed by peastman** 2023-01-10 16:34 UTC
