### ISSUE TITLE
Add documentation on running benchmarks to the User Guide

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3419] opened 2022-01-20 18:37 UTC
It appears that we have not documented how to run the OpenMM benchmark script in the [User Guide](http://docs.openmm.org/latest/userguide/).

It would be helpful to provide users with some guidance about where to find the script and how to run it.

**Comment by peastman** [comment] 2022-01-20 20:17
This is a duplicate of #3346.

**Closed by peastman** 2022-01-20 20:17 UTC
