### ISSUE TITLE
PDBxFile raises RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by bolhuis** [openmm/openmm#2311] opened 2019-05-30 19:03 UTC
I am running openmm 7.3.1 in python 3.7.
When loading a cif file using PDBxFile I get the following error:

---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
~/miniconda3/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbx/reader/PdbxReader.py in __tokenizer(self, ifh)
    358         while True:
--> 359             line = next(fileIter)
    360             self.__curLineNumber += 1

StopIteration: 

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-25-df29ea3bece8> in <module>
----> 1 pdb = app.PDBxFile('test.cif')

~/miniconda3/lib/python3.7/site-packages/simtk/openmm/app/pdbxfile.py in __init__(self, file)
     75         reader = PdbxReader(inputFile)
     76         data = []
---> 77         reader.read(data)
     78         block = data[0]
     79 

~/miniconda3/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbx/reader/PdbxReader.py in read(self, containerList)
     69         self.__curLineNumber = 0
     70         try:
---> 71             self.__parser(self.__tokenizer(self.__ifh), containerList)
     72         except StopIteration:
     73             pass

~/miniconda3/lib/python3.7/site-packages/simtk/openmm/app/internal/pdbx/reader/PdbxReader.py in __parser(self, tokenizer, containerList)
    271                             curRow.append(curQuotedString)
    272 
--> 273                         curCatName,curAttName,curQuotedString,curWord = next(tokenizer)
    274 
    275                     # loop_ data processing ends if -

RuntimeError: generator raised StopIteration

When looking this up, it seems that this is specific for python 3.7 because of https://www.python.org/dev/peps/pep-0479/

**Comment by peastman** [comment] 2019-05-30 19:30
Yes, this is caused by a change in behavior in Python 3.7.  It's fixed in the latest code in the repository, so it will work in the next release.

**Comment by bolhuis** [comment] 2019-05-30 19:53
Thanks. Will be patient. In the meantime, I will just use the fixed code.

**Comment by jchodera** [comment] 2019-05-31 15:22
@peastman: I guess we should think about a 7.3.2 bugfix release! Are there other things we can put in there?

**Closed** 2020-12-03 18:01 UTC
