### ISSUE TITLE
Multi-step integrator

### ISSUE THREAD

**Issue by raimis** [openmm/openmm#2482] opened 2019-11-25 11:09 UTC
@peastman @jchodera

It is loosely based on https://arxiv.org/pdf/physics/0502064.pdf

1. Compute `fastForces` and `slowForces`
2. Propagate the state with `fastForces + 2*slowForces`
3. Compute `fastForces`
4. Propagate the state with `fastForces`
where `slowForces` is the reciprocal term of PME, and `fastForces` is everything else.

**Comment by peastman** [comment] 2019-11-25 17:05
I'm closing this since it's a duplicate of #2483.

**Closed by peastman** 2019-11-25 17:05 UTC
