### ISSUE TITLE
import new force file such as pcff，cvff？

### ISSUE THREAD

**Issue by lifewadwdv** [openmm/openmm#2795] opened 2020-08-05 14:42 UTC
how can i import the new force file such as **pfcc**, **cvff** from lammps to the system

**Comment by peastman** [comment] 2020-08-05 17:08
I don't know of any tool that can directly convert LAMMPS force fields to OpenMM.  You might be able to do it in two steps, using [InterMol](https://github.com/shirtsgroup/InterMol) to convert it from LAMMPS to Gromacs, then [ParmEd](https://github.com/ParmEd/ParmEd) to convert it from Gromacs to OpenMM.

**Comment by jchodera** [comment] 2020-08-06 03:07
It looks like those [force fields (cvff and pcff)](https://github.com/lammps/lammps/tree/master/tools/msi2lmp/frc_files) were originally developed by MSI and then converted to a format that LAMMPS could read using [this tool](https://github.com/lammps/lammps/tree/master/tools/msi2lmp).

Do you have any idea how broadly these force fields are used, @lifewadwdv? Adding support for these force fields might be a feature request for http://github.com/openmm/openmm-forcefields, but we'd want to know how widely used this would be so we can prioritize it appropriately.

The other alternative, as @peastman suggests, is to find some way to support LAMMPS -> OpenMM conversions for an individual parameterized system.

**Comment by lifewadwdv** [comment] 2020-08-06 03:36
@peastman  I think it might be now, more prudent approach, thank you,  I'll try it.  @jchodera Those files is indeedly origined from MSI, however, Force field files like pfcc cvff.etc are suitable for many structures in lammps, here I have collected some files, I don’t know if it can help you, https://github.com/lifewadwdv/openmmforcefields/tree/master/otherForcefield

**Comment by jchodera** [comment] 2020-08-06 04:48
@lifewadwdv : Where did the XML files in that GitHub repo originate from? It looks like they might be in [foyer](https://github.com/mosdef-hub/foyer/issues/255) format (see also [this](https://arxiv.org/pdf/1812.06779.pdf))?

@mattwthompson has extensive experience with this can can comment on whether there is a convenient pipeline for Foyer -> OpenMM.

**Comment by lifewadwdv** [comment] 2020-08-06 04:55
@jchodera I found them in commerial software MAPS lammps Module path，simmlar to the foryer format

**Comment by jchodera** [comment] 2020-08-06 05:01
We have to be careful about files coming from commercial vendors, since it's unclear from the files whether the license or copyright permits redistribution of those files. 

If they are Foyer format, @mattwthompson may be able to help guide us in the right direction.

**Comment by lifewadwdv** [comment] 2020-08-06 05:11
@jchodera You're right，https://github.com/lifewadwdv/openmmforcefields/tree/master/convertByMyself  here are files converted from lammps force files by myself. And @mattwthompson but i want to know if those files can be converted to formats supported by opemm, because there are some parameters of pcff.frc I didn’t find in opemm

**Comment by mattwthompson** [comment] 2020-08-06 14:25
Unfortunately, those do not look to be compatible with  Foyer; Foyer uses a very light wrapper around OpenMM's force field class with added `def` strings to encode SMARTS patterns for atom-typing, which I do not see in those files.

I agree with everything above; going from LAMMPS data files to other formats is a pretty tricky. Reproducing an atom-typing scheme (going from a force field and chemical topology to a parametrized system)  from LAMMPS files is nearly impossible since it does not handle that logic internally. If you just have a parametrized system in LAMMPS format, using  InterMol to convert to a more standard fromat, that ParmEd can than read and load into OpenMM, is probably the only strategy with a chance of working. For a small system, it may be worth considering doing it by hand since the intermediate tools support far fewer functional forms than OpenMM.

Also do consult the licenses to see if there are any restrictions on pushing this data through a pipeline (or even posting it on GitHub); I am not personally familiar with MAPS myself.

**Comment by lifewadwdv** [comment] 2020-08-06 14:35
@mattwthompson  thank you, I'm now considering if the conversions of the force files are successful, and the parameters like improper in **cvff** are converted to opemm, and whether there is a corresponding label in openmm? this is the key to my current technology

**Comment by peastman** [comment] 2020-08-06 15:30
> If you just have a parametrized system in LAMMPS format, using InterMol to convert to a more standard fromat, that ParmEd can than read and load into OpenMM, is probably the only strategy with a chance of working.

If you just need to convert a parametrized system, you can probably even skip the ParmEd step.  Use InterMol to convert it to a Gromacs .top file, and then OpenMM can read that file directly.

**Comment by lifewadwdv** [comment] 2020-08-06 15:42
@peastman  Thank you. In fact, I personally like the excellent function that openmm can automatically match the force field to the imported model. So I want to develop a function that force field file of any format selected by the user can be applied to the struture, providing some convenience for lammps or opemm users in the pre-processing stage.

**Comment by peastman** [comment] 2021-11-18 16:48
Closing this issue, since I think all questions have been resolved.

**Closed by peastman** 2021-11-18 16:48 UTC
