### ISSUE TITLE
problem [ virtural_site3 ] from GROMACS files

### ISSUE THREAD

**Issue by btam125** [openmm/openmm#4534] opened 2024-05-08 05:25 UTC
Hi, 

I am currently using martini forcefield from GROMACS file and trying to run that in OpenMM software. Currently I have this error: 

ValueError: Unsupported function type in [ virtual_sites3 ] line:    6  4  3  7   4  0.2287  0.4111   1.1531

The error disappear if I delete the two line after first line, therefore I would like to ask is it the virtual_sites3 only read the first line or there is some error in the gromacstop.py ?

Thanks, 

Ben

**Comment by peastman** [comment] 2024-05-08 14:41
Are you using an old version of OpenMM?  That feature has been supported since 8.0.

**Comment by btam125** [comment] 2024-05-09 02:00
Yes I am using the latest OpenMM. Without deleting the lines except the first line, the error pop up for all the lipid molecules with virtual sites

**Comment by peastman** [comment] 2024-05-10 03:56
Can you post the files needed to reproduce the problem?  I'll take a look.

**Comment by btam125** [comment] 2024-05-10 04:03
Here is the file. Thank you for your help.
[Uploading example.zip…]()

**Comment by btam125** [comment] 2024-05-10 04:04
[example.zip](https://github.com/openmm/openmm/files/15270189/example.zip)

**Comment by peastman** [comment] 2024-05-10 15:49
I see, it specifies function 4 for the vsite, which corresponds to OpenMM's OutOfPlaneSite class.  I'll mark this as a feature request to add support for it in Gromacs files.  It should be an easy change.

**Comment by peastman** [comment] 2024-05-10 17:55
The fix is in #4536, if you want to try it out.

**Closed** 2024-05-13 17:53 UTC
Labels: enhancement
