### ISSUE TITLE
Wave64 of `findInteractingBlocks` is missing support for `USE_LARGE_BLOCKS`

### ISSUE THREAD

**Issue by bdenhollander** [openmm/openmm#4623] opened 2024-08-21 21:33 UTC
It looks Wave64 support was accidentally missed during #4147 so the number of parameters expected by OpenCL is different when running on GCN or CDNA GPUs. I don't see any code in OpenCLNonbondedUtilities.cpp that checks SIMD width and disables `useLargeBlocks` so C++ is generating parameters that do not exist in the kernel code.

Wave32 used by RDNA:

https://github.com/openmm/openmm/blob/75d4f2996a053e444cc8aa4230f1fece1a3df7a1/platforms/opencl/src/kernels/findInteractingBlocks.cl#L157-L166

Wave64 used by GCN and CDNA:

https://github.com/openmm/openmm/blob/75d4f2996a053e444cc8aa4230f1fece1a3df7a1/platforms/opencl/src/kernels/findInteractingBlocks.cl#L575-L580

This was noticed by a FAH tester on a Radeon VII GPU. If needed, I can test a fix on an RX 460.

**Comment by peastman** [comment] 2024-08-21 22:09
Thanks for reporting it.  That should be an easy fix.

**Comment by peastman** [comment] 2024-08-23 20:03
The fix is in #4629.  If you can test it, that would be great.  I don't have a GPU with width 64 to test on.

**Comment by bdenhollander** [comment] 2024-08-24 21:41
Adding the arguments fixes the `clSetKernelArg` error. However, I'm seeing a lot of particle coordinate is NaN errors on master. I tried git blame twice from different starting points and it gave different commits as the first bad one, neither of which made sense. 8.1.0 seems to be running fine so I will test 8.1.2 and retry git blame next week.

**Comment by bdenhollander** [comment] 2024-08-26 23:17
I confirmed 8.1.2 runs fine on GCN. Running git bisect again, from the 8.1.0 tag on master, https://github.com/openmm/openmm/commit/796ffaaa97decdf1593ed75afa5fbb21b6b32e9c is the first bad commit. If you have any suggestions to test, please let me know. Also, you may be able to run your 5700 XT in Wave64 mode by setting the environment variable `GPU_ENABLE_WAVE32_MODE=0`.

**Comment by peastman** [comment] 2024-08-27 19:38
> Also, you may be able to run your 5700 XT in Wave64 mode by setting the environment variable GPU_ENABLE_WAVE32_MODE=0.

Do you know what effect that variable is supposed to have?  `device.getInfo<CL_DEVICE_WAVEFRONT_WIDTH_AMD>()` still returns 32.

**Comment by bdenhollander** [comment] 2024-08-27 21:54
> > Also, you may be able to run your 5700 XT in Wave64 mode by setting the environment variable GPU_ENABLE_WAVE32_MODE=0.
> 
> Do you know what effect that variable is supposed to have? `device.getInfo<CL_DEVICE_WAVEFRONT_WIDTH_AMD>()` still returns 32.

It's supposed to force Wave64 mode but it's not well documented. I thought I had it working at one point since I saw a slight performance decrease with the variable is set but the queries still returns 32.

**Comment by peastman** [comment] 2024-08-30 20:04
Installing ROCm on that computer seems to have broken OpenCL.  HIP works fine, but running any benchmark with OpenCL produces the error

> Error compiling kernel: fatal error: malformed or corrupted AST file: 'could not find file '/home/peastman/miniconda3/envs/openmm/lib/clang/17/include/opencl-c-base.h<F5><FF><FF><FF><FF><FF><FF><FF><U+000F><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000><U+0000>' referenced by AST file '/tmp/comgr-b16853/include/opencl1.2-c.pch''
> 1 error generated.
> Error: Failed to compile source (from CL or HIP source to LLVM IR).

@ex-rzr any idea what might be the reason?

**Comment by ex-rzr** [comment] 2024-09-01 13:25
@peastman 

> @ex-rzr any idea what might be the reason?

No, it is the first time I'm seeing such an error. I haven't launched OpenCL tests on ROCm for a while, so I can's say anything about the issue in nonbonded, but I'm sure OpenCL kernels for the tests can be compiled. Do you use ROCm conda packages or ubuntu/centos packages?
I'll try to reproduce NaNs in nonbonded.

**Comment by peastman** [comment] 2024-09-03 23:21
I found the problem that was causing the nans.  I added the fix to #4629.  Can you try it out?

**Comment by bdenhollander** [comment] 2024-09-04 01:40
All the benchmarks and 13 FAH projects of various sizes all ran successfully on RX 460. I call that a successful fix!

If this could be back-ported to 8.1.x and released so GCN is usable while waiting for HIP, that would be appreciated.

**Closed as completed** 2024-09-04 15:47 UTC
Labels: bug

**Comment by peastman** [comment] 2024-09-04 15:49
I'm hoping we can release the 8.2 beta really soon now, and there won't be any need for a 8.1.3.  But that will depend on how long HIP takes.
