### ISSUE TITLE
DrudeForce incompatible with AmoebaMultipoleForce

### ISSUE THREAD

**Issue by mvanvleet** [openmm/openmm#1531] opened 2016-06-29 22:27 UTC
I am attempting to run a simulation with a force field that uses both higher-order electrostatic multipoles and includes polarizability via drude oscillators. The following files give an example of such a force field for the water dimer:

[drude_issue.zip](https://github.com/pandegroup/openmm/files/340313/drude_issue.zip)

Note that, for testing purposes, I've set all multipole moments to zero, so that the correct energy for AmoebaMultipoleForce is 0 kJ/mol.

When running a simulation with just multipoles (and no drude oscillators, see directory 02_multipoles_no_drudes), the output of an energy minimization is as expected:

```
$ python run_water.py
...
(4.19077393441784, 96.5605887399242, 171.35694845868744) nm
(4.255972125905252, 96.52459900920773, 171.41708366727988) nm
(4.2356059458928845, 96.5644692663304, 171.2724650037593) nm
(-2.489773657837164, -91.60226809004654, -167.00729535217798) nm
(-2.5374794219479253, -91.53157310234911, -166.9638364183268) nm
(-2.557098923725927, -91.65101576594796, -167.0547651079055) nm
0.344137606917 kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7fc01c162210> > 1.1777326431e-07 kJ/mol
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7fc01c162240> > 2.97371402837e-07 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7fc01c1622a0> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x7fc01c1623f0> > -7.90173653041e-19 kJ/mol
<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7fc01c1621e0> > 0.344137191772 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7fc01c1621b0> > 0.0 kJ/mol
```

Similarly, including drude oscillators (with no multipoles) produces a reasonable output.

By contrast, if I include both an AmoebaMultipoleForce and a DrudeForce in my force field (see directory 01_drudes_and_multipoles), AmoebaMultipoleForce returns a NaN energy:

``` Minimizing...
(0.8552, 2.5324000000000004, 2.2607) nm
(0.9101000000000001, 2.5144, 2.3373000000000004) nm
(0.8022, 2.6079000000000003, 2.2871) nm
(0.8552, 2.5324000000000004, 2.2607) nm
(0.8492000000000002, 2.3907000000000003, 2.0078) nm
(0.7915000000000001, 2.3542, 2.0748) nm
(0.8898, 2.4652000000000003, 2.0529) nm
(0.8492000000000002, 2.3907000000000003, 2.0078) nm
nan kJ/mol
<simtk.openmm.openmm.HarmonicBondForce; proxy of <Swig Object of type 'OpenMM::HarmonicBondForce *' at 0x7fde44c9e540> > 0.0558748082808 kJ/mol
<simtk.openmm.openmm.HarmonicAngleForce; proxy of <Swig Object of type 'OpenMM::HarmonicAngleForce *' at 0x7fde44c9e510> > 0.386420830284 kJ/mol
<simtk.openmm.openmm.NonbondedForce; proxy of <Swig Object of type 'OpenMM::NonbondedForce *' at 0x7fde44c9e570> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomNonbondedForce; proxy of <Swig Object of type 'OpenMM::CustomNonbondedForce *' at 0x7fde44c9e5a0> > 4.9485969911 kJ/mol
<simtk.openmm.openmm.DrudeForce; proxy of <Swig Object of type 'OpenMM::DrudeForce *' at 0x7fde44c9e5d0> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7fde44c9e4e0> > nan kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7fde44c9e600> > 0.0 kJ/mol
```

which is obviously incorrect. 

Any ideas as to why AmoebaMultipoleForce is returning a Nan energy are appreciated.

**Comment by peastman** [comment] 2016-06-29 22:45
I'll take a look.  AmoebaMultipoleForce was never designed to work with Drude particles, so I'm not surprised something is failing.  But possibly it can be fixed easily.

**Comment by mvanvleet** [comment] 2016-06-30 17:35
I'm not terribly surprised by this either. As far as I can tell, AmoebaMultipoleForce and (NonbondedForce + DrudeForce) are both self-contained and non-interacting. That is, charges assigned in AmoebaMultipoleForce do not interact with the electrostatic potential generated by NonbondedForce, and vice versa. 

This incompatibility probably effects a small number of users (namely people like myself who wish to simultaneously use Drude oscillators and multipole moments); given the similarities between induced dipoles and Drude oscillators, these users should maybe switch over to using induced dipoles if a (relatively) easy fix isn't possible.

At the very least, however, it would be nice if the python interface warned users about the incompatibilities between AmoebaMultipoleForce and NonbondedForce/DrudeForce mentioned above.

**Comment by peastman** [comment] 2016-06-30 18:00
NonbondedForce and AmoebaMultipoleForce definitely don't interact with each other.  Each of them is an independent force.  But why include both of them?  AmoebaMultipoleForce can reproduce a simple point charge just by setting the polarizability and higher multipole moments to 0.  There's no fundamental reason you couldn't then add a DrudeForce, which also is its own independent force.

The main difficulties appear to be in how AMOEBA handles exceptions, which is a lot more complicated than how NonbondedForce does.  So the problems seen there with Drude particles being right on top of their atoms come back in a context where it's much harder to just skip them.

**Comment by mvanvleet** [comment] 2016-06-30 21:35
There's no fundamental reason, and I agree that NonbondedForce should be redundant if AmoebaMultipoleForce is already specified. Currently, however, DrudeForce requires a NonbondedForce to be present in the input file; if a NonbondedForce is not included, the following error message results:

```
Traceback (most recent call last):
  File "run_water.py", line 36, in <module>
    ewaldErrorTolerance=0.0005)
  File "/srv/home/mvanvleet/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 994, in createSystem
    force.createForce(sys, data, nonbondedMethod, nonbondedCutoff, args)
  File "/srv/home/mvanvleet/anaconda2/lib/python2.7/site-packages/simtk/openmm/app/forcefield.py", line 4758, in createForce
    raise ValueError('<DrudeForce> must come after <NonbondedForce> in XML file')
ValueError: <DrudeForce> must come after <NonbondedForce> in XML file
```
This can, of course, be avoided by simply including a NonbondedForce with all charges set to zero, though the potential for confusion and/or accidental double-counting of interactions is possible with the current code set up.

**Comment by peastman** [comment] 2016-06-30 21:47
Oh, right.  ForceField requires that so it can figure out where to add screened pairs.  The C++ API doesn't need it though.

**Comment by peastman** [comment] 2020-12-01 00:59
I don't think we're planning to do anything about this, so I'm closing the issue.  Those two forces aren't intended to be used together.

**Closed by peastman** 2020-12-01 00:59 UTC
