### ISSUE TITLE
PyPI packages (originally "Python 3.8 OpenMM builds")

### ISSUE THREAD

**Issue by tomgoddard** [openmm/openmm#2871] opened 2020-09-28 21:32 UTC
Would it be possible to provide OpenMM builds for Python 3.8?  Current OpenMM Conda builds are for Python 3.7.  Python 3.8 was released about 1 year ago, and python 3.9 is about to be released (first week of October 2020).

I have updated ChimeraX which uses OpenMM to Python 3.8.

Either of two options would allow me to continue to include OpenMM in ChimeraX.

1) Update the OpenMM 7.4.2 Conda distributions to include Python 3.8 versions on Linux, macOS, Windows.

or

2) Provide an OpenMM 7.5 beta Python 3.8 Linux version compiled for CentOS 7 (ie compatible with its C++ standard library).

In the ChimeraX update to Python 3.8 last week I used OpenMM 7.5 beta builds from omnia-dev.  These are fine for Windows and macOS where C++ ABI compatibility allows these OpenMM builds to run on older operating systems.  But the OpenMM 7.5 beta for Linux is based on gcc-9 requiring C++ library version GLIBCXX_3.4.26 which is only supported on Ubuntu 20.04, and not 18.04, nor 16.04, nor CentOS 7 or 8.

OpenMM in ChimeraX is used for the ISOLDE cryoEM refinement tool written by Tristan Croll.  He is currently busy with manuscripts and funding, so obtaining a Python 3.8 OpenMM for the latest ChimeraX is probably not required for about a month since he will not have time to update ISOLDE to use a new OpenMM until them.  But within a few months the need for a working Python 3.8 OpenMM will be critical.

**Comment by tomgoddard** [comment] 2020-09-28 21:41
There is a ChimeraX ticket about OpenMM for Python 3.8 with more of the ChimeraX details here:

   https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/3756

**Comment by jchodera** [comment] 2020-09-29 00:04
cc @jaimergp @peastman who are working with folks from Quansight to help us update to use the conda-forge infrastructure for builds.

@tomgoddard : Has ChimeraX thought of going to conda-forge? Quansight might be able to help, and we might be able to extend our contract with them to cover the costs.

**Comment by tomgoddard** [comment] 2020-09-29 00:29
It isn't practical for us to turn a small problem like OpenMM not providing Python 3.8 builds into a big undertaking of changing the ChimeraX distribution system.  ChimeraX depends on about 60 third-party packages most obtained via PyPi and pip install.  OpenMM is just one of those packages.  We are over-extended in our programming effort as I am sure everyone in scientific programming is familiar with so being able to leverage libraries from others without joining their preferred distribution ecosystem is necessary for us.  The ideal OpenMM packaging for ChimeraX would be from PyPi.  But we can also handle Conda or tar balls or any other form as long as they don't do things that lock them into a specific ecosystem like replacing the Linux libstdc++.so with their own.

**Comment by jchodera** [comment] 2020-09-29 00:36
> The ideal OpenMM packaging for ChimeraX would be from PyPi.

Can you point us to any packages that make use of CUDA and OpenCL support and are packaged through PyPI through some sort of automated infrastructure? We don't know much about how this would work, but could look into it.

> But we can also handle Conda or tar balls or any other form as long as they don't do things that lock them into a specific ecosystem like replacing the Linux libstdc++.so with their own.

Conda-build now requires builds with a specific compiler suite, and conda-forge uses a specialized scheme for that. Once we convert to conda-forge, would that solve your issues?

**Comment by tomgoddard** [comment] 2020-09-29 01:01
I don't know if OpenMM builds from conda-forge would solve my problem.  The Linux OpenMM 7.5 beta from omnia-dev (using version from about 1 week ago) depends on a libstdc++.so that only Ubuntu 20.04 includes (the most current Linux distro we build for). 

	https://anaconda.org/omnia-dev/openmm/7.5.0/download/linux-64/openmm-7.5.0-py38_cuda110_1.tar.bz2

Many of the UCSF labs use CentOS 7 which is much older, with an older libstdc++.  As far as I understand the only way that OpenMM distribution can be used on most Linux distributions (except for the very latest) would be to replace the Linux libstdc++.so which is a very undesirable solution, prone to causing all kinds of havoc when an app then ends up pulling in different libstdc++ libraries.  I guess the Conda system replaces libstdc++.so if this package is able to run in Conda on anything other than 2020 Linux distros.  I'm not sure if or how this can be remedied in the Conda build environment, I have not experience with that.

It is worth considering whether OpenMM intends to distribute builds for non-Conda environments.  If not, Tristan could potentially build the ChimeraX OpenMM distributions, but that is a significant burden.

I did not mean to suggest OpenMM use PyPi.  I realize CUDA especially is a nightmare to handle the many versions.  That behavior of CUDA is staggeringly unfriendly -- could you imagine depending on 3 libraries that each had 10 versions that required different builds -- you would need hundreds of different builds.  And the nightmare for end-users trying to match up applications versions with CUDA library versions -- this only seems viable for extremely niche applications (e.g. science).

**Comment by peastman** [comment] 2020-09-29 04:47
OpenMM 7.5 will definitely include builds for Python 3.8.  Hopefully we'll have that out soon.  Getting things moved to the new conda build infrastructure is just taking a lot longer than we hoped.

We have no plans to distribute builds through any means other than conda.  We get regular suggestions for other mechanisms (pip, Debian packages, a Mac framework, Docker containers, etc.), but maintaining those would be a major burden we don't want to take on.

**Comment by tristanic** [comment] 2020-09-29 13:32
The attached Singularity recipe and build script successfully builds the current OpenMM with `devtoolset-9`, Python 3.8 and CUDA 10.1. Well... _almost_ successfully - the document generation fails due to what looks like a bug in the current version of `sphinxcontrib.autodoc_doxygen`:

```
reading sources... [  1%] generated/OpenMM.AmoebaAngleForce                                                        
Exception occurred:
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sphinxcontrib/autodoc_doxygen/autosummary/__init__.py", line 29, in import_by_name
    parent_symbols = [p[0].get_display_string() for p in parents]
TypeError: 'LookupKey' object is not iterable
The full traceback has been saved in /tmp/sphinx-err-kipf6d66.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```
... but the rest of the build works fine. I don't have a copy of the AMD APP SDK, so it just uses the CUDA OpenCL headers - not sure how much of an issue that is. 

Unzip `openmm_build.zip` to a directory of your choice, make sure Singularity 3.6 is installed, then:

```
singularity config fakeroot --add {your linux user name}
singularity build --fakeroot centos-7-devtoolset-9-py38-cuda-openmm.sif centos-7-devtoolset-9-cuda.def
singularity run --fakeroot --bind .:/host centos-7-devtoolset-9-py38-cuda-openmm.sif
```
The `fakeroot` stuff is optional, but allows you to run the last two lines without `sudo`. The OpenMM build will be in {working dir}/build. The compiled tests all run successfully in my vanilla(ish) CentOS 7 environment.

[openmm_build.zip](https://github.com/openmm/openmm/files/5299221/openmm_build.zip)

**Comment by jaimergp** [comment] 2020-09-29 13:40
Last time I found problems with doxygen stuff was because I forgot to pin to a specific version. doxygem `1.8.14` is the last I could get to work, if that helps!

**Comment by tristanic** [comment] 2020-09-29 14:31
Thanks! Although for the purposes of bundling into ChimeraX, I suppose the documentation is somewhat superfluous - probably better to just point to the online docs.

**Comment by jaimergp** [comment] 2020-09-29 14:40
I don't think we are even building them for the conda packages, but I recall Doxygen was also used in the Python wrappers generation. But if that's working, then no need to change it!

**Comment by peastman** [comment] 2020-09-29 16:42
`sphinxcontrib.autodoc_doxygen` is a plugin for sphinx, so it's probably an incompatibility with the version of that rather than doxygen.  But it's only used in generating the docs.

**Comment by tristanic** [comment] 2020-09-30 14:25
> Can you point us to any packages that make use of CUDA and OpenCL support and are packaged through PyPI through some sort of automated infrastructure? We don't know much about how this would work, but could look into it.

@jchodera This doesn't directly address the "automated" part of your question, but there are quite a few CUDA and OpenCL packages on the PyPI: `pyopencl`, `pycuda`, `reikna`, `numba`, etc.. The PyPI page for `pyopencl` says it does its Linux builds for distribution with Travis-CI.

**Comment by jchodera** [comment] 2020-09-30 17:07
> @jchodera This doesn't directly address the "automated" part of your question, but there are quite a few CUDA and OpenCL packages on the PyPI: pyopencl, pycuda, reikna, numba, etc.. The PyPI page for pyopencl says it does its Linux builds for distribution with Travis-CI.

Hoping for some information on _how_ to build and package a CUDA and OpenCL enabled pip package by example. Any pointers to specific "here's the code that allows them to do that" would be useful for me to look into!

**Comment by tristanic** [comment] 2020-09-30 17:15
I'm not sure this should be particularly challenging. The single biggest challenge is already taken care of - OpenMM doesn't require OpenCL and CUDA - it only links via dlopen​ at runtime and won't break the environment if they're not there. If you were to start from the manylinux2014​ docker image (https://www.python.org/dev/peps/pep-0599/), add a suitable devtoolset​ and install CUDA for building purposes, the result should be entirely compliant.
________________________________

**Comment by tristanic** [comment] 2020-09-30 17:18
pyopencl​ Travis-CI recipe is at https://github.com/inducer/pyopencl/blob/master/.travis.yml and build script at https://github.com/inducer/pyopencl/blob/master/travis/build-wheels.sh.

________________________________

**Comment by tristanic** [comment] 2020-10-02 18:56
With a bit of hacking (hand-editing of the processed `setup.py`) I've gotten to the point of building what looks to be a fully portable Python3.8 wheel (https://drive.google.com/file/d/1Jlmq7ohAYCiLxC86PhWH03ss_XMU2amK/view?usp=sharing if you want to give it a test drive - it passed all the Python tests after installing into a naive Python3.8 on my CentOS system. Certainly not a production-ready pipeline, but a good exercise to work out what needs to be done to make it into one. Basically, for this test I did:
```
make 
make install
make PythonInstall
cd python
find . -name "_openmm*.so" -delete # to rebuild with different RPATH
# copy in the modified openmm_setup.py
python3.8 openmm_setup.py bdist_wheel
```
Key things that needed to change:

`from distutils.core import setup` replaced with `from setuptools import setup` to allow the bdist_wheel keyword.

Remove the call to `uninstall()` in `main()`

Copy the core compiled libraries and headers into `simtk/openmm/lib` and `simtk/openmm/include` respectively (setuptools _really_ expects everything to be inside the Python tree, and this seems like the sensible place to put them). BTW: I just noticed that I forgot to include the `symlinks=True` argument in `shutil.copytree()`, so all symlinks have been expanded to true files. Annoying, but a trivial fix.

Update `writeVersionPy()` so that `version.openmm_library_path` will return the final installed path, and add a 
`version.openmm_include_path`.

 Remove the "runtime_library_dirs" argument to `extensionArgs` (previously set to the installed location of the compiled libraries, which now just adds a superfluous entry to the RPATH of `_openmm.cpython...so`). 

Modify the `extra_link_args` entries for Darwin and Linux to set the rpath relative to the location of `_openmm`. Not as familiar with how this works in Windows... @tomgoddard maybe Greg could offer some advice here?

Anyway, if I'm not mistaken fully `manylinux2014` compliant. According to `auditwheel`:
```
The wheel references external versioned symbols in these system-
provided shared libraries: libgcc_s.so.1 with versions {'GCC_3.4',
'GCC_3.0', 'GCC_4.0.0'}, libpthread.so.0 with versions {'GLIBC_2.2.5',
'GLIBC_2.3.2'}, libstdc++.so.6 with versions {'GLIBCXX_3.4.9',
'GLIBCXX_3.4.15', 'CXXABI_1.3.1', 'GLIBCXX_3.4.11', 'GLIBCXX_3.4',
'CXXABI_1.3', 'GLIBCXX_3.4.14', 'GLIBCXX_3.4.5'}, libc.so.6 with
versions {'GLIBC_2.4', 'GLIBC_2.3.3', 'GLIBC_2.2.5', 'GLIBC_2.3.4',
'GLIBC_2.3', 'GLIBC_2.14', 'GLIBC_2.3.2', 'GLIBC_2.7'}, libm.so.6 with
versions {'GLIBC_2.2.5'}, librt.so.1 with versions {'GLIBC_2.2.5'},
libdl.so.2 with versions {'GLIBC_2.2.5'}, libcufft.so.10 with versions
{'libcufft.so.10'}, libnvrtc.so.10.1 with versions
{'libnvrtc.so.10.1'}, libOpenCL.so.1 with versions {'OPENCL_1.0',
'OPENCL_1.2'}

This constrains the platform tag to "manylinux2014_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.

...


In order to achieve the tag platform tag "manylinux2014_x86_64" the
following shared library dependencies will need to be eliminated:

libOpenCL.so.1, libOpenMM.so.7.5, libOpenMMAmoeba.so,
libOpenMMCUDA.so, libOpenMMDrude.so, libOpenMMOpenCL.so,
libOpenMMRPMD.so, libcuda.so.1, libcufft.so.10, libfftw3f.so.3,
libfftw3f_threads.so.3, libnvrtc.so.10.1
```
Most of these are only there either because `auditwheel` can't tell that they know how to find each other. The rest are dynamically linked at runtime, and the lack of them isn't a show-stopper (i.e. it won't break Python, OpenMM just won't load its plugins). 






[openmm_setup.zip](https://github.com/openmm/openmm/files/5319640/openmm_setup.zip)

**Comment by tristanic** [comment] 2020-10-02 19:00
In general I do agree with Tom that a maximally-compatible version usable in the non-Conda ecosystem would be a valuable thing, and would keep OpenMM available to the widest possible developer community.

**Comment by tristanic** [comment] 2020-10-02 19:34
Hmm... it seems like `symlinks=True` in `shutil.copytree()` just pushes the problem downstream - the symlinks still get converted to real files by the packaging machinery, and some Googling suggests that it's near-impossible to force it not to. I guess the simplest approach would be to only copy the non-versioned `libOpenMM.so`?

**Comment by peastman** [comment] 2020-10-02 21:29
That should be fine.  Our standard build scripts only produce non-versions libraries.

> Copy the core compiled libraries and headers into simtk/openmm/lib and simtk/openmm/include respectively

You can probably accomplish this by just setting `CMAKE_INSTALL_PREFIX` to that directory.

**Comment by tristanic** [comment] 2020-10-05 19:52
Word from the ChimeraX team is that the `devtoolset-9` builds are playing nicely with ChimeraX built with the same toolchain. This solves the most pressing issue for now... if there's interest (and unless anyone else is interested in the meantime), I'd be happy to look developing this initial exploration into an automated build pipeline for PyPI wheels once my grant-writing plate is clear (December or early in the new year).

**Comment by jchodera** [comment] 2020-10-09 00:39
> if there's interest (and unless anyone else is interested in the meantime), I'd be happy to look developing this initial exploration into an automated build pipeline for PyPI wheels once my grant-writing plate is clear (December or early in the new year).

@tristanic : Yes! Let's set up a chat with @jaimergp and @peastman to see if we can somehow support this as well, since it would make a ton of things (including educational use in Google colab notebooks) much easier, even if it isn't our primary approach to distribution.

**Comment by jaimergp** [comment] 2020-12-07 15:48
Check the new `conda` packages at conda forge](https://anaconda.org/conda-forge/openmm/files). Includes Python 3.6, 3.7, 3.8, and 3.9, for Linux (64, ppc, arm), MacOS and Windows. Linux 64 and Windows are built with CUDA 10.0 and above. Linux 64 also provides 9.2

**Comment by tristanic** [comment] 2020-12-07 16:00
> Check the [new `conda` packages at conda forge](https://anaconda.org/conda-forge/openmm/files). Includes Python 3.6, 3.7, 3.8, and 3.9, for Linux (64, ppc, arm), MacOS and Windows. Linux 64 and Windows are built with CUDA 10.0 and above. Linux 64 also provides 9.2

The problem is that (as I understand it) C++ programs compiled using conda are not ABI-compatible with those compiled using devtoolset, even if the headline gcc version is the same. So the conda builds would be fine if I only needed to use OpenMM via the Python interface, but there are a few places where I need to work in C++: a slightly-customised minimiser pushed off into a separate thread, a routine to step the simulation (and perform trajectory smoothing, and safety checks on atomic velocities) in a separate thread; some customisations to various `CustomForce` objects to allow fast initialisation/updating via Numpy arrays. So the options are:

- add a build pipeline to make PyPI-compliant builds using a `devtoolset`
- I work with you to implement support for my needs within `OpenMM` itself.

I'm honestly open to both approaches, and in the new year should finally have a bit of free time to properly focus on it.

**Comment by jaimergp** [comment] 2020-12-07 16:03
Conda Forge as a platform won't allow to distribute anything compiled with different compilers, but I can help set up the infrastructure you would need to obtain the same packages compiled for `devtoolset`!

**Comment by tristanic** [comment] 2020-12-07 16:06
That would be great!

**Comment by tristanic** [comment] 2021-02-12 14:02
Situation update: until this lockdown finally ends, my domestic situation is not going to be conducive to anything other than occasional tinkering with code. Would certainly still like to see this happen, but may be at least another few months before I can contribute.

**Comment by jaimergp** [comment] 2021-02-12 14:41
All good! We are definitely comfortable with conda-forge right now, I would say, so I don't think we are on a rush here.

Also, this issue should be renamed to "PyPI packages" or something similar, because the original title doesn't reflect the conversation we ended up having. @peastman can you do that? Thanks!

**Comment by peastman** [comment] 2021-02-12 16:56
Renamed!

Good luck with things getting back to normal.  This is such a strange time for everyone.

**Comment by jaimergp** [comment] 2021-05-20 07:30
This project will help set things up:
https://github.com/pypa/cibuildwheel

**Comment by jchodera** [comment] 2021-05-20 20:57
The [CTranslate2 example](https://github.com/OpenNMT/CTranslate2) looks especially interesting!
![image](https://user-images.githubusercontent.com/3656088/119047833-43837b80-b973-11eb-8835-f8b9a713ea6d.png)

**Comment by tristanic** [comment] 2021-05-20 21:20
That does look useful!

Still wrapped up in chasing funding and tying up some other loose ends around here, but the good news is that we should be allowed back into the office in a few weeks so I might finally have some quality time to put into this.

**Comment by tristanic** [comment] 2021-07-20 14:33
Finally (!) found the time to have a proper look at this. Working proof-of-principle at https://github.com/tristanic/openmm/tree/pypi (builds successfully in CentOS 7/devtoolset-9 and Python 3.9 with OpenMM forked from the current master branch). Built, installed into ChimeraX using pip, and successfully ran a simulation (well... after getting rid of all my `from simtk...` imports) Should _hopefully_ work in MacOS and Windows as well, but that's not yet tested. Three files new/changed:

Build script: https://github.com/tristanic/openmm/blob/pypi/build_wheel.sh
setup.py: https://github.com/tristanic/openmm/blob/pypi/wrappers/python/setup.py
top-level CMakeLists.txt: https://github.com/tristanic/openmm/blob/5727e5e4c392a0314e201a341774ff861155b5a0/CMakeLists.txt#L281

The `setup.py` should still be fully compatible with the existing build pipeline. Apart from two minor things, every change is under the control of the environment variable `OPENMM_BUILD_WHEEL`. Those two things are:

- import `setup` from `setuptools` rather than `distutils` - this is required to enable `python setup.py bdist_wheel`
- `version.py` provides `openmm_include_path` as well as `openmm_library_path` - having the headers in the wheel will make it much easier/safer to build against, and I figured it would be sensible to include in the conda build for consistency. Feel free to disagree, of course!

The change to CMakeLists.txt adds an extra option, `OPENMM_BUILD_UNVERSIONED`, that causes `libOpenMM` to be built without versioning. This is needed because setuptools does not support symlinks, so the versioned approach leads to the `libOpenMM.so` symlink becoming a full copy of `libOpenMM.so.x.y`. While there might be various hacky ways to work around that, this seems the cleanest approach.

Anyway, at this point it would be great to get some input from someone who has more than my (essentially zero) experience with continuous integration servers to help take this forward.

Other thing worth discussing: whether it would be worth bundling the relevant `libnvrtc`, `libnvrtc-builtins` and `libcudart` into the wheels as discussed in #3174?

**Comment by tristanic** [comment] 2021-07-22 07:24
@jaimergp would be great to chat when you have a little free time.

**Comment by jchodera** [comment] 2021-07-22 12:22
Would be great if @peastman could join as well---having pip wheels would be *super* useful for deploying OpenMM in notebooks for tutorials! (cc @Yoshanuikabundi)

**Comment by tristanic** [comment] 2021-09-07 19:22
Update: I've been actively using the build made according to my 20 July post ever since, after `pip install`ing it into ChimeraX. No sign of any issues.

**Comment by jchodera** [comment] 2021-09-07 22:35
We should seriously consider officially supporting "experimental pip builds" if we can bring on some developer expertise with more pip experience to help us maintain this.

@peastman is now also a maintainer of https://pypi.org/project/openmm/, so we can replace that outdated package when we have something for 7.6.

@tristanic : I know you're swimming in TODOs, but perhaps you'd be willing to help if we went down this route? Would you consider at least opening a PR with your changes?

**Comment by tristanic** [comment] 2021-09-08 08:54
Done. See #3239.

**Comment by peastman** [comment] 2024-11-11 22:25
OpenMM 8.2 added PyPI builds, so we can finally close this!

**Closed by peastman** 2024-11-11 22:25 UTC
Labels: enhancement
