### ISSUE TITLE
OpenMM/FAHCore fails with ERROR:exception: Error invoking kernel reduceEnergy: clEnqueueNDRangeKernel (-54)

### ISSUE THREAD

**Issue by toTOWfr** [openmm/openmm#3177] opened 2021-07-14 16:35 UTC
An user on FAH Discord server reported an issue with his AMD 5700 XT GPU.

System specifications and software detection :

> 15:56:37:******************************* System ********************************
> 15:56:37:            CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
> 15:56:37:         CPU ID: GenuineIntel Family 6 Model 165 Stepping 5
> 15:56:37:           CPUs: 16
> 15:56:37:         Memory: 15.92GiB
> 15:56:37:    Free Memory: 11.76GiB
> 15:56:37:        Threads: WINDOWS_THREADS
> 15:56:37:     OS Version: 6.2
> 15:56:37:    Has Battery: false
> 15:56:37:     On Battery: false
> 15:56:37:     UTC Offset: 9
> 15:56:37:            PID: 13288
> 15:56:37:            CWD: C:\ProgramData\FAHClient
> 15:56:37:  Win32 Service: false
> 15:56:37:             OS: Windows 10 Enterprise
> 15:56:37:        OS Arch: AMD64
> 15:56:37:           GPUs: 1
> 15:56:37:          GPU 0: Bus:3 Slot:0 Func:0 AMD:6 Navi 10 [Radeon RX 5600 OEM/5600
> 15:56:37:                 XT/5700/5700 XT]
> 15:56:37:           CUDA: Not detected: Failed to open dynamic library 'nvcuda.dll': The
> 15:56:37:                 specified module could not be found.
> 15:56:37:
> 15:56:37:OpenCL Device 0: Platform:0 Device:0 Bus:3 Slot:0 Compute:1.2 Driver:3240.6
> 15:56:37:***********************************************************************

FAHCore/OpenMM fails to start with the following error : 

> 16:01:51:WU02:FS01:0x22:  opencl-device 0 specified
> 16:02:03:WU02:FS01:0x22:Attempting to create OpenCL context:
> 16:02:03:WU02:FS01:0x22:  Configuring platform OpenCL
> 16:02:41:WU02:FS01:0x22:ERROR:exception: Error invoking kernel reduceEnergy: clEnqueueNDRangeKernel (-54)

The parameters to the program call seem correct for the OpenCL platform and device : 

> 15:56:52:WU00:FS01:Running FahCore: "C:\Program Files (x86)\FAHClient/FAHCoreWrapper.exe" C:\ProgramData\FAHClient\cores/cores.foldingathome.org/win/64bit/22-0.0.13/Core_22.fah/FahCore_22.exe -dir 00 -suffix 01 -version 706 -lifeline 13288 -checkpoint 15 -opencl-platform 0 -opencl-device 0 -gpu-vendor amd -gpu 0 -gpu-usage 100

Here is the output of clinfo : 

> Number of platforms:                             1
>   Platform Profile:                              FULL_PROFILE
>   Platform Version:                              OpenCL 2.1 AMD-APP (3240.6)
>   Platform Name:                                 AMD Accelerated Parallel Processing
>   Platform Vendor:                               Advanced Micro Devices, Inc.
>   Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
> 
> 
>   Platform Name:                                 AMD Accelerated Parallel Processing
> Number of devices:                               1
>   Device Type:                                   CL_DEVICE_TYPE_GPU
>   Vendor ID:                                     1002h
>   Board name:                                    AMD Radeon RX 5700 XT
>   Device Topology:                               PCI[ B#3, D#0, F#0 ]
>   Max compute units:                             20
>   Max work items dimensions:                     3
>     Max work items[0]:                           1024
>     Max work items[1]:                           1024
>     Max work items[2]:                           1024
>   Max work group size:                           1024
>   Preferred vector width char:                   4
>   Preferred vector width short:                  2
>   Preferred vector width int:                    1
>   Preferred vector width long:                   1
>   Preferred vector width float:                  1
>   Preferred vector width double:                 1
>   Native vector width char:                      4
>   Native vector width short:                     2
>   Native vector width int:                       1
>   Native vector width long:                      1
>   Native vector width float:                     1
>   Native vector width double:                    1
>   Max clock frequency:                           1795Mhz
>   Address bits:                                  64
>   Max memory allocation:                         8304721920
>   Image support:                                 Yes
>   Max number of images read arguments:           128
>   Max number of images write arguments:          64
>   Max image 2D width:                            16384
>   Max image 2D height:                           16384
>   Max image 3D width:                            2048
>   Max image 3D height:                           2048
>   Max image 3D depth:                            2048
>   Max samplers within kernel:                    16
>   Max size of kernel argument:                   1024
>   Alignment (bits) of base address:              2048
>   Minimum alignment (bytes) for any datatype:    128
>   Single precision floating point capability
>     Denorms:                                     Yes
>     Quiet NaNs:                                  Yes
>     Round to nearest even:                       Yes
>     Round to zero:                               Yes
>     Round to +ve and infinity:                   Yes
>     IEEE754-2008 fused multiply-add:             Yes
>   Cache type:                                    Read/Write
>   Cache line size:                               64
>   Cache size:                                    16384
>   Global memory size:                            8573157376
>   Constant buffer size:                          8304721920
>   Max number of constant args:                   8
>   Local memory type:                             Scratchpad
>   Local memory size:                             65536
>   Max pipe arguments:                            16
>   Max pipe active reservations:                  16
>   Max pipe packet size:                          4009754624
>   Max global variable size:                      7474249728
>   Max global variable preferred total size:      8573157376
>   Max read/write image args:                     64
>   Max on device events:                          1024
>   Queue on device max size:                      8388608
>   Max on device queues:                          1
>   Queue on device preferred size:                262144
>   SVM capabilities:
>     Coarse grain buffer:                         Yes
>     Fine grain buffer:                           Yes
>     Fine grain system:                           No
>     Atomics:                                     No
>   Preferred platform atomic alignment:           0
>   Preferred global atomic alignment:             0
>   Preferred local atomic alignment:              0

I vaguely remember of a similar issue on some AMD GPUs and/or drivers, that required a patch to get the work group detect correct or to pass the correct value on those GPUs ... is it possible that it is a similar issue ?

Additional informations : the user reported that the issue is occurring on Windows, but not on Linux on the same GPU. He also reported that FAHBench (which uses an older version of OpenMM) is working.

**Comment by toTOWfr** [comment] 2021-07-16 21:56
A complete reinstallation of Windows fixed the issue, but the cause of the original issue is still unknown.

**Comment by jchodera** [comment] 2021-08-28 21:44
Closing this for now---please reopen if we end up with more info on the cause.

**Closed by jchodera** 2021-08-28 21:44 UTC
