### ISSUE TITLE
 No matching distribution found for openmm>=7.1 (from pdbfixer) #244 

### ISSUE THREAD

**Issue by tkcaccia** [openmm/openmm#3536] opened 2022-03-29 16:08 UTC
**I am trying to install pdbfixer without success**

conda install -c omnia openmm

    Collecting package metadata (current_repodata.json): done
    Solving environment: done
    All requested packages already installed.

conda install -c omnia/label/beta pdbfixer

    Collecting package metadata (current_repodata.json): done
    Solving environment: done
    All requested packages already installed.

python3 -m pip install openmm

    Requirement already satisfied: openmm in /home/user/.local/lib/python3.8/site-packages (0.2)

python3 -m pip install pdbfixer

    Requirement already satisfied: pdbfixer in /home/user/alphafold (1.8.1)
    Requirement already satisfied: numpy in /home/user/.local/lib/python3.8/site-packages (from pdbfixer) (1.22.3)
    ERROR: Could not find a version that satisfies the requirement openmm>=7.1 (from pdbfixer) (from versions: 0.1, 0.2)
    ERROR: No matching distribution found for openmm>=7.1 (from pdbfixer)

**Comment by peastman** [comment] 2022-03-29 16:38
This is a duplicate of https://github.com/openmm/pdbfixer/issues/244.  I answered the question there, so I'm closing this one.

**Closed by peastman** 2022-03-29 16:38 UTC
