### ISSUE TITLE
one pdb file work but not the another same file 

### ISSUE THREAD

**Issue by AhmetGG** [openmm/openmm#3343] opened 2021-11-22 00:48 UTC
Hi, I have run two pdb file but xx.pdb file gives the error and it was written of "no template found for residue". But the other PDB file similar, called yy.pdb, doesnt have a problem and 'it run. I looked at both and I think there is no difference for file context. I looked into frequently questions but I couldnt find any solution for my problem. I get confused one file run but another no.Could you help me about why I get the error? The pdb files are here.
[xx.pdb.tar.gz](https://github.com/openmm/openmm/files/7577512/xx.pdb.tar.gz)
[yy.pdb.tar.gz](https://github.com/openmm/openmm/files/7577513/yy.pdb.tar.gz)

**Comment by peastman** [comment] 2021-11-22 18:25
What force field are you using?  And which residue does it say there's no template for?  Can you paste the full error message?

**Comment by AhmetGG** [comment] 2021-11-23 11:07
Thank you so much for replying. When I run xx.pdb fusing amber14/protein.ff14SB.xml, amber14/spce.xml, and using charmm36.xml","charmm36/spce, seperately, I get the error of "No template found for residue 31762 (HOH).  The set of atoms matches HOH, but the bonds are different."

**Comment by tristanic** [comment] 2021-11-28 12:23
Your immediate problem is the lines starting with "CONECT" at the end of the first PDB file. My guess is that these are carry-over from some earlier version of the file, but are now connecting the wrong atoms to each other.

Beyond that, though, I feel I should warn you that this model is **not** really suitable for simulation as-is. If you look closely at the two protein chains you'll see that they're tangled right through each other - even if your simulation doesn't crash at startup it's not going to give you meaningful results from that.

**Comment by peastman** [comment] 2021-11-29 17:21
The problem is that your file contains over 100,000 atoms.  That's the maximum number PDB supports, since it only provides five columns for the atom number.  After that, the numbers wrap around to zero again.  Then when it encounters the line

```
CONECT  234  710
```

it doesn't know which atoms to connect, since there's more than one with the number 234.

The best solution would probably be to use PDBx/mmCIF instead.  It's the successor to the PDB format and it doesn't have the limit on number of atoms.

**Comment by peastman** [comment] 2021-12-03 23:39
I'm closing this, since I think all questions have been answered.  If I missed something, feel free to reopen it.

**Closed by peastman** 2021-12-03 23:39 UTC
