### ISSUE TITLE
openMM 8.0.0 CUDA platform experiencing large temperature increase during simulation

### ISSUE THREAD

**Issue by peter-zhang-chem** [openmm/openmm#4353] opened 2023-12-13 20:46 UTC
Hi openMM team,

I am using openMM 8.0.0 CUDA platform to run my simulation. However, I am experiencing large temperature change as the simulation proceeds (desired temperature = 300 K, but the simulation goes up to 2000 K). The problem does not appear when I run on the reference platform. The testInstallation was successfully passed for all three available platforms (Reference vs. CPU, Reference vs. CUDA, CPU vs. CUDA)

Here are some details regarding my simulation:

integrator = omm.LangevinMiddleIntegrator(simu.temp, 1/unit.picosecond, 2*unit.femtoseconds)
platform = omm.Platform.getPlatformByName('CUDA')
properties = {'CUDAPrecision': 'mixed')

**Comment by peastman** [comment] 2023-12-13 21:10
>  properties = {'CUDAPrecision': 'mixed')

That should be `'CudaPrecision'`.  It's case sensitive.  Though that's a deprecated name: you can just say `'Precision'`.

If that doesn't fix it, can you provide the files to reproduce it?  It's hard to guess what might be going on.

**Comment by peter-zhang-chem** [comment] 2023-12-14 15:02
Hi there!

Thank you, it made the temperature fluctuation less severe; however, there is occasionally few temperature points that are extremely high. 
[OpenMM Trouble Shooting 12-14-23.zip](https://github.com/openmm/openmm/files/13674904/OpenMM.Trouble.Shooting.12-14-23.zip)

**Comment by peter-zhang-chem** [comment] 2023-12-14 15:04
To run:  python main.py -f GA -s 100000000 -K 150 -T 302 -t GA-302-GPU-check-121323.dcd -e GA-302-GPU-check-121323-energy.out -o GA-302-GPU-check-121323-md.out -r GA-302-GPU-check-121323-2.chk

**Comment by peter-zhang-chem** [comment] 2023-12-14 15:05
![image](https://github.com/openmm/openmm/assets/33939722/3d7fa911-c367-43a9-9c79-dfe101e2ca2f)
Here is an example of the temperature over the course of the simulation using the CUDA platform, I am expecting the average temperature to be 302 K here.

**Comment by peter-zhang-chem** [comment] 2023-12-15 16:39
Another I found really troubling was if I use CPU platform, it is significantly slower than reference platform. I was expecting the opposite. Thank you.

**Comment by peastman** [comment] 2023-12-18 20:19
It looks like your code requires some other package `Bio.PDB`?  What is that?

Would it be possible to create a simpler, self contained test?  The easiest way is to just save your System, State, and Integrator to XML files: see https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html.  Then if you post those three files, it's easy to load them and reproduce your simulation without all the complicated setup.

**Comment by peastman** [comment] 2023-12-18 20:20
It looks like your code requires some other package `Bio.PDB`?  What is that?

Would it be possible to create a simpler, self contained test?  The easiest way is to just save your System, State, and Integrator to XML files: see https://openmm.github.io/openmm-cookbook/latest/notebooks/cookbook/Saving%20Systems%20to%20XML%20Files.html.  Then if you post those three files, it's easy to load them and reproduce your simulation without all the complicated setup.

**Comment by peter-zhang-chem** [comment] 2023-12-19 00:57
Hi Peter,

Bio.PDB is from a package under biopython (https://biopython.org/docs/1.75/api/Bio.PDB.html), it can read pdb file and help me perform coarse grain. The test run actually do not use the package as the input is 'GA' sequence, not a pdb file.

But yes I can provide the three XML files to have a simpler test, how do I save the integrator as XML files? I saw some discussion that it was added to the saveState().

Thanks!

Peter

**Comment by peastman** [comment] 2023-12-19 03:27
Thanks!  It's just like saving the system:

```python
with open('integrator.xml', 'w') as output:
    output.write(XmlSerializer.serialize(integrator))
```

**Comment by peter-zhang-chem** [comment] 2023-12-19 13:44
[Issue-4345-GPU-testing.zip](https://github.com/openmm/openmm/files/13716284/Issue-4345-GPU-testing.zip)

Hi Peter, 

I saved the three xml files here (integrator.xml (integrator), system.xml (system), and output.xml (state)). Thank you!

**Comment by peastman** [comment] 2023-12-19 20:31
I simulated your system for 10 million steps without any sign of problem:

```python
from openmm import *
system = XmlSerializer.deserialize(open('system.xml').read())
integrator = XmlSerializer.deserialize(open('integrator.xml').read())
state = XmlSerializer.deserialize(open('output.xml').read())
context = Context(system, integrator)
context.setState(state)
for i in range(1000):
    s = context.getState(getEnergy=True)
    print(i, s.getPotentialEnergy(), s.getKineticEnergy())
    integrator.step(10000)
```

Does that script work for you?

**Comment by peter-zhang-chem** [comment] 2023-12-20 13:11
That is interesting, I also just ran 50 million steps, the temperature is working as expected now. Let me run a few more simulations and see. Thank you Peter.

**Comment by peter-zhang-chem** [comment] 2023-12-20 18:23
[GPU-trouble-shoot.zip](https://github.com/openmm/openmm/files/13730868/GPU-trouble-shoot.zip)

Hi Peter, at temperature 302 K it works as expected; however, at 352 K it showed the temperature fluctuation again. Can you please see if you can reproduce using the files attached? Thanks!

**Comment by peter-zhang-chem** [comment] 2023-12-20 18:24
![image](https://github.com/openmm/openmm/assets/33939722/209ea920-6d51-4379-ac51-95714d5892cd)

**Comment by peastman** [comment] 2023-12-20 20:25
Can you show the plot without those two outlier points?  You can just restrict the y axis to some reasonable range, like 0 to 2000.

I suspect this is a sign of instability.  It could be that you need to reduce the time step a bit, or it might indicate one of your custom forces has a point where it becomes very large.  I'm especially suspicious of the CustomCompoundBondForce.  It divides by `abs(pi + dihedral(p2,p3,p4,p5) - phi20)`, which becomes zero when the dihedral is -0.0702 radians.

**Comment by peter-zhang-chem** [comment] 2023-12-20 21:32
The issue does not occur when I use the "reference" platform, will that rule out that problem is with the CustomCompoundBondForce?

**Comment by peter-zhang-chem** [comment] 2023-12-20 21:43
![image](https://github.com/openmm/openmm/assets/33939722/dc3c35da-9088-46af-90f0-58c4bca05692)

**Comment by peastman** [comment] 2023-12-20 21:58
That's because the reference platform works entirely in double precision.  It can still run into problems if it gets too close to the singularity, but it has a bigger margin.

What happens if you remove the CustomCompoundBondForce?

**Comment by peter-zhang-chem** [comment] 2023-12-21 03:24
Hi Peter,

You are right, by turning off that particular CustomCompoundBondForce, the temperature fluctuation was no longer an issue. 

The functional form I'd like to use is `energyfunction = "U0/(1.0 + kbond * (distance(p6, p7) - r0)^2 + kphi1 * (dihedral(p1, p2, p3, p4) - phi10)^2 + kphi2 * (dihedral(p2, p3, p4, p5) - phi20)^2)` 

![image](https://github.com/openmm/openmm/assets/33939722/468f34aa-63b5-40ca-a39e-8b9eb37c3ca2)

**Comment by peter-zhang-chem** [comment] 2023-12-22 15:41
![image](https://github.com/openmm/openmm/assets/33939722/d4b60968-e7e6-4cc2-b3de-60cec0f6c4fa)

**Comment by peter-zhang-chem** [comment] 2023-12-22 15:42
![image](https://github.com/openmm/openmm/assets/33939722/d99a761d-dd6f-4ec4-8fcd-3d8296f7f5e0)

**Comment by peter-zhang-chem** [comment] 2023-12-22 15:44
^ here is what I want to accomplish with the "correction factor" after the `kphi1*(dihedral(p1,p2,p3,p4) - phi10` term

**Comment by peter-zhang-chem** [comment] 2023-12-22 15:56
I am thinking should I change the functional form of the CustomCompoundBondForce, or should I run the simulation with CUDA in double precision instead of mixed?

**Comment by peter-zhang-chem** [comment] 2023-12-22 15:59
![image](https://github.com/openmm/openmm/assets/33939722/cd53f38f-5c51-40da-a45d-6b950248b598)

If we look at one of the terms that involve `abs(pi + dihedral(p2,p3,p4,p5) - phi20)`, here is what I am trying to do with the correction term.

**Comment by peastman** [comment] 2023-12-22 17:49
That isn't the energy function in your force.  Here is the expression.

> U0/(1.0 + kbond*(distance(p6,p7) - r0)^2  + kphi1*(dihedral(p1,p2,p3,p4) - phi10 + pi*(((pi - dihedral(p1,p2,p3,p4) + phi10)/abs(pi - dihedral(p1,p2,p3,p4) + phi10)) -  ((pi + dihedral(p1,p2,p3,p4) - phi10)/abs(pi + dihedral(p1,p2,p3,p4) - phi10)))  )^2  +  kphi2*(dihedral(p2,p3,p4,p5) - phi20 + pi*(((pi - dihedral(p2,p3,p4,p5) + phi20)/abs(pi - dihedral(p2,p3,p4,p5) + phi20)) -  ((pi + dihedral(p2,p3,p4,p5) - phi20)/abs(pi + dihedral(p2,p3,p4,p5) - phi20)))  )^2 )

All those divisions by factors that can be zero create numerically unstable points.

The simpler expression you show above will be stable as long as all the force constants are positive.  If any of them is negative, that will allow the denominator to become zero.

**Comment by peter-zhang-chem** [comment] 2023-12-22 18:07
Can you elaborate a little bit more on why double precision has a bigger margin? I'd like to keep the current energy function if possible, so I am trying to see if running double precision with CUDA platform would be an appropriate idea.

**Comment by peastman** [comment] 2023-12-22 18:21
I don't recommend that.  It will make your simulation much slower, and ultimately it won't fix the problem.  It will just make it come up less often.

Computers represent numbers with a finite precision.  You need to take care to avoid situations where that limited precision causes problems.  For example, if you subtract two numbers that are almost equal to each other, the result has much less precision than either of the original numbers.  The closer they are, the more precision you lose.  If you then divide by that number, the low precision is propagated to the result.

Working in double precision means the numbers have to get closer to each other before you start experiencing severe loss of precision.  But when your computer is performing billions of operations per second, it's almost certain that sooner or later it will happen.  It's just a question of how often.  The correct solution is to pick a functional form that doesn't have this issue, because it never divides by something that can be zero.

**Comment by peter-zhang-chem** [comment] 2023-12-22 18:25
ok, thank you Peter! That was a very clear explanation.

**Closed** 2023-12-29 09:58 UTC
