### ISSUE TITLE
Apparent Bugs with Switching Functions and CustomNonbondedForces

### ISSUE THREAD

**Issue by Exarctus** [openmm/openmm#2768] opened 2020-07-02 10:23 UTC
Hi Guys,

I've been running into serious problems with CustomNonbondedForces when using switching functions. I'd first like to state that using switching functions in the "normal" NonbondedForce objects seems to look fine, this issue is only encountered with CustomNonbondedForces.

You can find all the code necessary to reproduce this issue, as well as a (hopefully) helpful readme on the following github repository:

https://github.com/Exarctus/OpenMMSolvation/tree/master/OpenMMSolvation

I started off looking at using reaction-field electrostatics with alchemy.py to calculate hydration free energies, and noticed that when simulating the fully interacting end-point the simulations are essentially frozen. 

I then made a test code which is independent of alchemy.py, which replaced all interactions between solute/solvent groups with CustomNonbondedForces, and again the same issue arises. This is why I've posted this issue here.

Whenever one uses switching functions with CustomNonbondedForces, the dynamics are grossly incorrect. Turning off switching functions (or reducing the distance at which the switch occurs to low values e.g 1.0 Angstrom) seems to alleviate the issue, but then the dynamics aren't reliable as in the first case you have energy discontinuities with no switching function, or in the second case results I cannot trust as switching functions seem to work in the opposite way they should!

If any developers could take a look into this issue it would be greatly appreciated.

**Comment by peastman** [comment] 2020-07-02 15:13
I would strongly recommend against using a switching function for electrostatics.  That introduces severe artifacts.  Depending on the charges of the atoms involved, it can either create an energy well or a hill, where groups get pulled into or pushed away from the region where the switching is happening.  It also is totally unnecessary.  Reaction field already makes the energy go smoothly to zero.

The switching function should be used only for vdw interactions, and the switching should only begin at a distance where the energy is already fairly close to zero.  It's just a way of smoothing out that last little edge to improve energy conservation.

**Comment by Exarctus** [comment] 2020-07-02 16:26
The reason I decided to try switched reaction field electrostatics was mostly due to [this comment](https://github.com/choderalab/openmmtools/blob/d4097719d49437c87ad8ca7136d74791fe762dcf/openmmtools/alchemy.py#L1492-L1493)  in the alchemy.py source code:

```
# WARNING: Setting c_rf != 0 can cause large errors in DeltaG for hydration free energies
```

Since I'm interested in hydration free energies specifically I presumed I needed to use a reaction field treatment. Do you have any idea where this statement that setting c_rf to a non-zero value would give erroneous hydration free energies?

**Comment by peastman** [comment] 2020-08-12 23:02
I'm closing this since the code is working correctly.  No idea what the origin of that comment is, but maybe try asking on that repository?

**Closed by peastman** 2020-08-12 23:02 UTC

**Comment by jchodera** [comment] 2020-08-14 03:31
@Exarctus: Apologies for the very late reply! The origin of that comment is that OpenMM's implementation of reaction field [includes a `c_rf` term](http://docs.openmm.org/latest/userguide/theory.html#coulomb-interaction-with-cutoff) that shifts (but does not switch) the energy to zero at the cutoff. However, force is still discontinuous at the cutoff---it is not switched smoothly and continuously to zero.

Unlike other implementations of reaction field electrostatics that use groups of charges that, together, form a neutral or integral charge, OpenMM applies this to each pairwise interaction. You'll find that this means running a simulation with cutoff `r_c` and then recomputing the energies with a slightly different cutoff `r_c + dr` (where `dr = 0.1 A` or even smaller) will give essentially uncorrelated energies---there is very little statistical overlap between these. This is also worrisome.

The motivation for dropping the `c_rf` term in computing a hydration free energy is this:
Suppose we have a simple dipole molecule composed of two opposite-charged atoms that are really close together, in a box of water with dielectric ~80. If we discharge the molecule in solvent and recharge it in gas phase, the reaction field electrostatics contribution from beyond the cutoff should match the response of a reaction field of dielectric 80 outside a spherical cavity of radius `r_c` (the cutoff).

The origin of the reaction field functional form is that the terms *excluding* the `c_rf` term give the free energy of discharging the atoms in solvent according to the [Onsager dipole reaction field model](https://en.wikipedia.org/wiki/Reaction_field_method). But the `c_rf` term was added later to make the energies go to zero at the cutoff. Unfortunately, the energy that is added depends on how many pairs of atoms are within the cutoff, which isn't predictable and fluctuates with time. That's the motivation behind that comment, at least.

We haven't been able to get free energy calculations with reaction field to work, but @jmichel80 has with SireMol. We'd love to support this at some point if we can just figure out what the right functional form to support should be!

**Comment by jmichel80** [comment] 2020-08-14 07:20
It’s one issue that has been on the back of my mind for some time. We do set c_rf of course so the arguments above should apply. Yet this does not seem to stop us from reproducing free energies of hydration of neutral mols or of sodium from the literature. Maybe @ppxasjsm has some ideas why.

**Comment by peastman** [comment] 2020-08-14 15:51
> Unlike other implementations of reaction field electrostatics that use groups of charges that, together, form a neutral or integral charge, OpenMM applies this to each pairwise interaction.

I don't believe that's correct.  I've never heard of any program combining group cutoffs with reaction field, and I can't see how that would work.  The two models are incompatible with each other.

If you want the force to be continuous, just set the reaction field dielectric to be infinite (or at least very large).  The discontinuity goes roughly as `1 - (eps-0.5)/(eps+1)`.  As epsilon goes to infinity, that goes to zero.

**Comment by jmichel80** [comment] 2020-08-14 16:07
Hi @peastman FYI the work reported here used charge groups and reaction-field as implemented in Gromos https://onlinelibrary.wiley.com/doi/full/10.1002/jcc.26143

**Comment by jchodera** [comment] 2020-08-15 01:17
@jmichel80 thanks for the insight! I believe you also do something special in gas phase to ensure there is some kind of cancellation that allows hydration free energies to come out correct---is that right?

**Comment by jmichel80** [comment] 2020-08-15 10:28
Yes this is necessary because we apply the RF to all non-excluded intramolecular non-bonded pairs, but in vacuum those are computed with Coulomb Law and no cutoff. This correction step isn’t necessary for binding free energy calcs, or hydration of very small solutes that lack >1-4 atom pairs.

**Comment by peastman** [comment] 2020-08-15 18:31
How does that work?  Normally group cutoffs mean you include all interactions with atoms in the group as long as any one of the atoms is within the cutoff distance.  But reaction field causes the interaction energy to go smoothly to zero at the cutoff distance, so what does it mean to include interactions beyond the cutoff distance?

**Comment by jchodera** [comment] 2020-08-15 21:51
> How does that work? 

@peastman: Here's a good explanation of how that works, from gromos developers: [Hünenberger and van Gunsteren, JCP 108:6117, 1998](https://doi.org/10.1063/1.476022).
