### ISSUE TITLE
 frame dimension is 0 in AMBER netcdf files written using `parmed NETCDFReporter`

### ISSUE THREAD

**Issue by nrkssa** [openmm/openmm#3440] opened 2022-02-02 15:17 UTC
I am using OpenMM to run implicit solvent MD simulations using the AMBER force field. The trajectories are written as AMBER netcdf files using the `parmed netCDFreporter`. The relevant part of the script is as below

```
from parmed.openmm import NetCDFReporter
netcdfreporter = NetCDFReporter('prod.nc', 1000, crds=True)
.
.
simulation.reporters.append(netcdfreporter)
```

The size of the resulting netcdf file is around 8 GB for nearly 30000 frames. However, I could not open the netcdf file in MDtraj/cpptraj. `cpptraj` fails with an error message `"frame dimension is 0"`,   while `mdtraj` reports `0 frames`.

```
md.load_netcdf('prod.nc', top='initial.parm7')
<mdtraj.Trajectory with 0 frames, 20504 atoms, 1338 residues, without unitcells at 0x7fe0cfa05820>
```

The attached zip file contains the OpenMM script, AMBER7 topology file,  output of dataReporter, and the resulting netcdf file with 14 frames. It would be very helpful if you can look into this and help me figure out the issue. 

The package versions are as below.
```
python: 3.9.2
openmm: 7.5.0.dev-b49b82e 
parmed: 3.4.1
mdtraj: 1.9.5
cpptraj: 5.1.0
```

[test_trajectory.zip](https://github.com/openmm/openmm/files/7987584/test_trajectory.zip)
 
Thanks in advance

Best
Ram

**Comment by nrkssa** [comment] 2022-02-02 15:25
Here is the info on the failing netcdf file:
```
$ncinfo  prod.nc
<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: AMBER
    ConventionVersion: 1.0
    application: AmberTools
    program: ParmEd
    programVersion: 3.4.0+11.g1be8ca0f
    title: ParmEd-created trajectory
    dimensions(sizes): frame(0), spatial(3), atom(20504)
    variables(dimensions): |S1 spatial(spatial), float32 time(frame), float32 coordinates(frame, atom, spatial)
    groups:
```

**Comment by peastman** [comment] 2022-02-02 16:53
That reporter is part of ParmEd.  You should open an issue at https://github.com/ParmEd/ParmEd.

MDTraj also includes its own NetCDF reporter.  Have you tried using it instead?

**Comment by nrkssa** [comment] 2022-02-02 17:02
@peastman Thank you taking a look. I will file a issue report with Parmed. I have not used the openmm netcdf reporter but will give it a try at once.

**Comment by nrkssa** [comment] 2022-02-02 17:21
@peastman MDtraj netCDFReporter works as expected.

**Comment by peastman** [comment] 2022-02-02 17:32
Great, I'm glad that one works!  I'm going to close this since the problem isn't in OpenMM.

**Closed by peastman** 2022-02-02 17:32 UTC
