### ISSUE TITLE
Simulation Module Unknow Error

### ISSUE THREAD

**Issue by CayetanaZF** [openmm/openmm#4196] opened 2023-08-20 21:59 UTC
Hey guys, 

I'm trying to run some MD in a HPC but I got the next error (I'm using a cuda platform):

Traceback (most recent call last):
  File "/home/czamorano/MD_Sulkowska/Sulkowska_RUN_NLHPC.py", line 380, in <module>
    simulation = Simulation(pdb.topology, system, integrator,platform)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/czamorano/.conda/envs/MD_OpenMM_Jupyter_Labq_Cay/lib/python3.11/site-packages/openmm/app/simulation.py", line 101, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/czamorano/.conda/envs/MD_OpenMM_Jupyter_Labq_Cay/lib/python3.11/site-packages/openmm/openmm.py", line 3749, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Error compiling program: default_program(956): warning: variable "bondParams1" was declared but never referenced

default_program(1004): error: floating constant is out of range

1 error detected in the compilation of "default_program"

If you could help me, would be nice!

Cayetana

**Comment by peastman** [comment] 2023-08-21 21:31
Can you post the script and input files needed to reproduce the error?

**Comment by peastman** [comment] 2023-11-06 20:34
Closing since the poster never replied.

**Closed by peastman** 2023-11-06 20:34 UTC
