### ISSUE TITLE
AmoebaVdwForce.get/setParticleParameters() not working as intended

### ISSUE THREAD

**Issue by leeping** [openmm/openmm#3921] opened 2023-01-20 06:00 UTC
Hi there,

I've run into some trouble with ForceBalance when attempting to fit an AMOEBA force field with vdW parameters.  I've traced the problem to a [function](https://github.com/leeping/forcebalance/blob/master/src/openmmio.py#L319) that copies the AmoebaVdwForce parameters from a new System (created from a modified forcefield.xml file) into an existing Context.  

The parameters that I'm getting from the new System have sigma set to 1.0 and epsilon set to 0.0, although it still gets the correct reduction factor.  The parameter setter also seems to have problems, because I'd expect it to set the vdW energy component to zero, but the vdW energy does not change after setting the new parameters.  As a result, ForceBalance thinks that changing the vdW parameter has no effect on the energies or forces, and the parameter doesn't change during the optimization.  

The following output is for a water dimer with the parameters as follows (I assume OpenMM ignores the `parameterize` tag):

```
  <AmoebaVdwForce type="BUFFERED-14-7" radiusrule="CUBIC-MEAN" radiustype="R-MIN" radiussize="DIAMETER" epsilonrule="HHG" vdw-13-scale="0.0" vdw-14-scale="1.0" vdw-15-scale="1.0" >
   <Vdw class="73" sigma="0.3405" epsilon="0.46024" reduction="1.0" parameterize="sigma, epsilon" />
   <Vdw class="74" sigma="1.0" epsilon="0.0" reduction="1.0"/>
 </AmoebaVdwForce>
```

Here's the output of calling getParticleParameters() from OpenMM 7.7:
```
AmoebaVDWForce particle 0 : , parameters = 0 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 1 : , parameters = 0 1.0 nm 0.0 kJ/mol 1.0 False 1
AmoebaVDWForce particle 2 : , parameters = 0 1.0 nm 0.0 kJ/mol 1.0 False 1
AmoebaVDWForce particle 3 : , parameters = 3 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 4 : , parameters = 3 1.0 nm 0.0 kJ/mol 1.0 False 1
AmoebaVDWForce particle 5 : , parameters = 3 1.0 nm 0.0 kJ/mol 1.0 False 1
```

And from OpenMM 7.4:
```
AmoebaVDWForce particle 0 : , parameters = 0 0.17025 nm 0.46024 kJ/mol 1.0
AmoebaVDWForce particle 1 : , parameters = 0 0.5 nm 0.0 kJ/mol 1.0
AmoebaVDWForce particle 2 : , parameters = 0 0.5 nm 0.0 kJ/mol 1.0
AmoebaVDWForce particle 3 : , parameters = 3 0.17025 nm 0.46024 kJ/mol 1.0
AmoebaVDWForce particle 4 : , parameters = 3 0.5 nm 0.0 kJ/mol 1.0
AmoebaVDWForce particle 5 : , parameters = 3 0.5 nm 0.0 kJ/mol 1.0
```

It would be really helpful if you could take a quick look at this.  Thank you!

- Lee-Ping

**Comment by peastman** [comment] 2023-01-20 17:20
Do you have a test case to reproduce this?  `getParticleParameters()` and `setParticleParameters()` are really simple:

https://github.com/openmm/openmm/blob/e1c4e1f8ee3e574f582b107412c7f9b595610012/plugins/amoeba/openmmapi/src/AmoebaVdwForce.cpp#L62-L82

There's not a lot of room for anything to go wrong in those methods.  I suspect the problem is really somewhere else.

**Comment by leeping** [comment] 2023-01-20 17:40
Hi Peter,

Thanks for looking at this.  Here's a test case.  

[test_get_set_parameter.tar.gz](https://github.com/openmm/openmm/files/10468730/test_get_set_parameter.tar.gz)

- Lee-Ping

**Comment by leeping** [comment] 2023-01-20 17:46
I forgot to attach the output of my local run - here it is:
```
(main) leeping@bright:$ python test.py
AmoebaVDWForce particle 0 : parameters = 0 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 1 : parameters = 0 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 2 : parameters = 0 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 3 : parameters = 0 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 4 : parameters = 4 1.0 nm 0.0 kJ/mol 1.0 False 2
AmoebaVDWForce particle 5 : parameters = 5 1.0 nm 0.0 kJ/mol 1.0 False 3
AmoebaVDWForce particle 6 : parameters = 6 1.0 nm 0.0 kJ/mol 1.0 False 4
AmoebaVDWForce particle 7 : parameters = 7 1.0 nm 0.0 kJ/mol 1.0 False 5
AmoebaVDWForce particle 8 : parameters = 7 1.0 nm 0.0 kJ/mol 0.92 False 6
AmoebaVDWForce particle 9 : parameters = 9 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 10 : parameters = 10 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 11 : parameters = 10 1.0 nm 0.0 kJ/mol 0.92 False 6
AmoebaVDWForce particle 12 : parameters = 12 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 13 : parameters = 12 1.0 nm 0.0 kJ/mol 0.92 False 6
AmoebaVDWForce particle 14 : parameters = 14 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 15 : parameters = 15 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 16 : parameters = 15 1.0 nm 0.0 kJ/mol 0.92 False 6
AmoebaVDWForce particle 17 : parameters = 17 1.0 nm 0.0 kJ/mol 1.0 False 7
AmoebaVDWForce particle 18 : parameters = 17 1.0 nm 0.0 kJ/mol 0.92 False 6
AmoebaVDWForce particle 19 : parameters = 19 1.0 nm 0.0 kJ/mol 1.0 False 8
AmoebaVDWForce particle 20 : parameters = 20 1.0 nm 0.0 kJ/mol 1.0 False 9
AmoebaVDWForce particle 21 : parameters = 21 1.0 nm 0.0 kJ/mol 1.0 False 10
AmoebaVDWForce particle 22 : parameters = 22 1.0 nm 0.0 kJ/mol 1.0 False 11
AmoebaVDWForce particle 23 : parameters = 23 1.0 nm 0.0 kJ/mol 1.0 False 12
AmoebaVDWForce particle 24 : parameters = 23 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 25 : parameters = 23 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 26 : parameters = 26 1.0 nm 0.0 kJ/mol 1.0 False 13
AmoebaVDWForce particle 27 : parameters = 27 1.0 nm 0.0 kJ/mol 1.0 False 14
AmoebaVDWForce particle 28 : parameters = 28 1.0 nm 0.0 kJ/mol 1.0 False 15
AmoebaVDWForce particle 29 : parameters = 28 1.0 nm 0.0 kJ/mol 0.91 False 16
AmoebaVDWForce particle 30 : parameters = 30 1.0 nm 0.0 kJ/mol 1.0 False 17
AmoebaVDWForce particle 31 : parameters = 30 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 32 : parameters = 32 1.0 nm 0.0 kJ/mol 1.0 False 17
AmoebaVDWForce particle 33 : parameters = 32 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 34 : parameters = 34 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 35 : parameters = 34 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 36 : parameters = 34 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 37 : parameters = 34 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 38 : parameters = 38 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 39 : parameters = 38 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 40 : parameters = 38 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 41 : parameters = 38 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 42 : parameters = 42 1.0 nm 0.0 kJ/mol 1.0 False 13
AmoebaVDWForce particle 43 : parameters = 43 1.0 nm 0.0 kJ/mol 1.0 False 14
AmoebaVDWForce particle 44 : parameters = 44 1.0 nm 0.0 kJ/mol 1.0 False 15
AmoebaVDWForce particle 45 : parameters = 44 1.0 nm 0.0 kJ/mol 0.91 False 16
AmoebaVDWForce particle 46 : parameters = 46 1.0 nm 0.0 kJ/mol 1.0 False 0
AmoebaVDWForce particle 47 : parameters = 46 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 48 : parameters = 46 1.0 nm 0.0 kJ/mol 0.91 False 1
AmoebaVDWForce particle 49 : parameters = 46 1.0 nm 0.0 kJ/mol 0.91 False 1
```

**Comment by peastman** [comment] 2023-01-20 18:43
AmoebaVdwForce used to always work by assigning parameters to each particle and applying combining rules.  But newer versions of AMOEBA require the ability to override the combining rules for certain pairs of particles, similar to NBFIX in CHARMM.  So we added an alternate mode where instead each particle just specifies a type index, which is the last column in the output above, and sigma and epsilon are specified for each type rather than each particle.  You also can  add `<Pair>` tags to override them for certain combinations:

https://github.com/openmm/openmm/blob/e1c4e1f8ee3e574f582b107412c7f9b595610012/wrappers/python/openmm/app/data/amoeba2018.xml#L9472-L9474

See [the API docs](http://docs.openmm.org/latest/api-c++/generated/AmoebaVdwForce.html) for more details on how this works.

**Comment by leeping** [comment] 2023-01-20 19:08
Thanks. Do you mean the correct way to copy parameters from one Force object (`src`) to another (`dest`) is to loop over the ParticleTypeParameters and the TypePairParameters, as follows?  Does that mean the ParticleParameters are no longer being used (at least when a System is created from a forcefield.xml file)?  

Here's my attempt at a code that works for both old and new OpenMM versions:

```def CopyAmoebaVdwParameters(src, dest):
    for i in range(src.getNumParticles()):
        dest.setParticleParameters(i,*src.getParticleParameters(i))
    if hasattr(src, 'getParticleTypeParameters'):
        for i in range(src.getNumParticleTypes()):
            print(src.getParticleTypeParameters(i))
            dest.setParticleTypeParameters(i,*src.getParticleTypeParameters(i))
    if hasattr(src, 'getTypePairParameters'):
        for i in range(src.getNumTypePairs()):
            dest.setTypePairParameters(i,*src.getTypePairParameters(i))```

However, when I try to call `AmoebaVdwForce.getParticleTypeParameters(0)`, I'm getting an IndexError.  I attached a modified test case to reproduce this behavior.

```Traceback (most recent call last):
  File "/home/leeping/projects/SCC11-QMMM/1-gfp/12-forcebalance/forcefield/test_get_set_parameter/./test.py", line 24, in <module>
    print("AmoebaVDWForce particle type %i : parameters =" % i, *f.getParticleTypeParameters(i))
  File "/home/leeping/opt/miniconda3/envs/main/lib/python3.9/site-packages/openmm/openmm.py", line 3493, in getParticleTypeParameters
    val[2]=unit.Quantity(val[2], unit.kilojoule_per_mole)
IndexError: list index out of range```

[test_get_set_parameter.tar.gz](https://github.com/openmm/openmm/files/10469339/test_get_set_parameter.tar.gz)

**Comment by leeping** [comment] 2023-01-20 19:16
For clarification, my use case is that I have two Systems, `src` and `dest`, that were originally created from two forcefield XML files that differ only in the numerical values of parameters.  One of these Systems (`dest`) belongs to an existing Context.  The goal is to copy all of the force parameters from `src` into `dest`, followed by calling `force.updateParametersInContext()` for each Force object, such that the existing Context behaves exactly as if it were created using the system `src`.  This is the same thing you helped me with many years ago during my postdoc, and this whole discussion is only to maintain compatibility with the new versions.

**Comment by peastman** [comment] 2023-01-20 19:39
>  Does that mean the ParticleParameters are no longer being used (at least when a System is created from a forcefield.xml file)?

The `sigma` and `epsilon` parameters are ignored when operating in the alternate mode.  The other parameters (`parentIndex`, `reductionFactor`, etc.) are still used.

The simplest way of making them identical is just to remove the AmoebaVdwForce from the first System, add a deep copy of the one from the other System, and reinitialize the Context.  Is that reasonable, or would it be too expensive?

I'm not sure what's causing the IndexError.  I'll take a look.

**Comment by leeping** [comment] 2023-01-20 20:07
Thanks, I think the original source of confusion could have been that the alternative mode was activated by default. I’ll check if there’s a way to ask for the original mode in the XML file or createSystem(). At the same time I think it would be good if ForceBalance could support optimizing type pair-specific vdW parameters so it’s good to continue working on this.

As for reinitializing the Context, would it be much faster than creating a new Simulation and Context from scratch? These parameter copying methods were originally added in FB because re-creating the Context each time a parameter changes is too expensive. Depending on the type of calculation, changing the parameters and re-evaluating the properties could happen once or more per second.

**Comment by peastman** [comment] 2023-01-20 21:04
There's no option in ForceField to use the original mode.  It always assigns parameters by class.

Reinitializing a Context is basically the same cost as creating a new Context.  You wouldn't want to do it once a second.

**Comment by peastman** [comment] 2023-01-20 21:24
I found the problem causing the exception.  It's fixed in #3923.  I'll build an updated release candidate as soon as it's merged.

**Comment by leeping** [comment] 2023-01-20 21:33
Thanks so much for the fix and the explanations! :)

- Lee-Ping

**Closed** 2023-01-20 22:11 UTC

**Comment by peastman** [comment] 2023-01-21 01:49
It's done building packages.  Can you test out the new release candidate and confirm this works for you?  You can install it with

```
conda install -c conda-forge/label/openmm_rc -c conda-forge openmm
```

**Comment by leeping** [comment] 2023-01-21 02:25
I just installed the new package from Conda and it works great. Thanks again!! :)

- Lee-Ping
