### ISSUE TITLE
Nonbonded exceptions interfering with barostat

### ISSUE THREAD

**Issue by EqualAPriori** [openmm/openmm#2664] opened 2020-04-28 21:01 UTC
Hi, I'm running into a case where adding non-bonded exceptions seems to interfere with the barostat -- the barostat updates for the first few thousand steps, but usually by 10k steps the box dimensions stop updating. This seems like a problem that I run into only if I'm adding a lot of exceptions, i.e. > 2000 exceptions in a system with ~23000 atoms.

Use case: I'm trying to implement non-bonded fixes where I modify sodium-oxygen LJ interactions from their typical mixing rule values. Below is the sample code I use to change the cross-interactions. Even when I set the exception to the same values as the mixing rule, I still run into this issue. However, when I implement the non-bonded fix using a CustomNonbondedForce, I don't run into this barostat issue. Following #2310 I'm using the latest version of openMM and have verified that the two approaches give the same energy to roughly within the error tolerance.

Am I using the exceptions in a way that I'm not supposed to be using them? 

Thanks!

How I'm using the exceptions:
```
ftmp = [f for ii, f in enumerate(system.getForces()) if isinstance(f,mm.NonbondedForce)]
fnb = ftmp[0]   

inds_Na = []
inds_Op = []

#first get original LJ parameters
for ia,atom in enumerate(top.topology.atoms()):
    if atom.element: #i.e. not virtual site
        if atom.residue.name in ['DS']:
            if atom.name in ['O1','O2','O3']:
                inds_Op.append(ia)
                [qO, sigO, epsO] = fnb.getParticleParameters(ia)
        if atom.residue.name in ['NA+']:
            inds_Na.append(ia)
            [qNa, sigNa, epsNa] = fnb.getParticleParameters(ia)

logger.info("... Detected original Na LJ parameters: {}".format([qNa, sigNa, epsNa]))
logger.info("... Detected original oP LJ parameters: {}".format([qO, sigO, epsO]))

logger.info( "... Detected {} Na ions".format(len(inds_Na)) )
logger.info( "... Detected {} Op oxygens".format(len(inds_Op)) )

#use exceptions, in this example set the exceptions to the same value as mixing rule
logger.info("... adding LJ exceptions")
new_exceptions = []
for ii_Na in inds_Na:
    for ii_Op in inds_Op:
        new_exceptions.append( fnb.addException( ii_Na, ii_Op, qNa*qO, 0.5*(sigNa+sigO), np.sqrt(epsNa*epsO) ) )

logger.info('Added {} exceptions, expected {}'.format(len(new_exceptions), len(inds_Na)*len(inds_Op)))
logger.info('Example new exception: {}'.format( fnb.getExceptionParameters(new_exceptions[0]) ))
```

and an example output from the above:
```
INFO:__main__:=== Modifying Na-oP LJ interactions ===
INFO:__main__:... Detected original Na LJ parameters: [Quantity(value=1.0, unit=elementary charge), Quantity(value=0.21844836600000003, unit=nanometer), Quantity(value=0.7047424999999999, unit=kilojoule/mole)]
INFO:__main__:... Detected original oP LJ parameters: [Quantity(value=-0.6383, unit=elementary charge), Quantity(value=0.295992, unit=nanometer), Quantity(value=0.87864, unit=kilojoule/mole)]
INFO:__main__:... Detected 86 Na ions
[3612, 3613, 3614, 3615, 3616, 3617, 3618, 3619, 3620, 3621, 3622, 3623, 3624, 3625, 3626, 3627, 3628, 3629, 3630, 3631, 3632, 3633, 3634, 3635, 3636, 3637, 3638, 3639, 3640, 3641, 3642, 3643, 3644, 3645, 3646, 3647, 3648, 3649, 3650, 3651, 3652, 3653, 3654, 3655, 3656, 3657, 3658, 3659, 3660, 3661, 3662, 3663, 3664, 3665, 3666, 3667, 3668, 3669, 3670, 3671, 3672, 3673, 3674, 3675, 3676, 3677, 3678, 3679, 3680, 3681, 3682, 3683, 3684, 3685, 3686, 3687, 3688, 3689, 3690, 3691, 3692, 3693, 3694, 3695, 3696, 3697]
INFO:__main__:... Detected 258 Op oxygens
[1, 2, 3, 43, 44, 45, 85, 86, 87, 127, 128, 129, 169, 170, 171, 211, 212, 213, 253, 254, 255, 295, 296, 297, 337, 338, 339, 379, 380, 381, 421, 422, 423, 463, 464, 465, 505, 506, 507, 547, 548, 549, 589, 590, 591, 631, 632, 633, 673, 674, 675, 715, 716, 717, 757, 758, 759, 799, 800, 801, 841, 842, 843, 883, 884, 885, 925, 926, 927, 967, 968, 969, 1009, 1010, 1011, 1051, 1052, 1053, 1093, 1094, 1095, 1135, 1136, 1137, 1177, 1178, 1179, 1219, 1220, 1221, 1261, 1262, 1263, 1303, 1304, 1305, 1345, 1346, 1347, 1387, 1388, 1389, 1429, 1430, 1431, 1471, 1472, 1473, 1513, 1514, 1515, 1555, 1556, 1557, 1597, 1598, 1599, 1639, 1640, 1641, 1681, 1682, 1683, 1723, 1724, 1725, 1765, 1766, 1767, 1807, 1808, 1809, 1849, 1850, 1851, 1891, 1892, 1893, 1933, 1934, 1935, 1975, 1976, 1977, 2017, 2018, 2019, 2059, 2060, 2061, 2101, 2102, 2103, 2143, 2144, 2145, 2185, 2186, 2187, 2227, 2228, 2229, 2269, 2270, 2271, 2311, 2312, 2313, 2353, 2354, 2355, 2395, 2396, 2397, 2437, 2438, 2439, 2479, 2480, 2481, 2521, 2522, 2523, 2563, 2564, 2565, 2605, 2606, 2607, 2647, 2648, 2649, 2689, 2690, 2691, 2731, 2732, 2733, 2773, 2774, 2775, 2815, 2816, 2817, 2857, 2858, 2859, 2899, 2900, 2901, 2941, 2942, 2943, 2983, 2984, 2985, 3025, 3026, 3027, 3067, 3068, 3069, 3109, 3110, 3111, 3151, 3152, 3153, 3193, 3194, 3195, 3235, 3236, 3237, 3277, 3278, 3279, 3319, 3320, 3321, 3361, 3362, 3363, 3403, 3404, 3405, 3445, 3446, 3447, 3487, 3488, 3489, 3529, 3530, 3531, 3571, 3572, 3573]
INFO:__main__:... adding LJ exceptions
INFO:__main__:Added 22188 exceptions, expected 22188
INFO:__main__:Example new exception: [3612, 1, Quantity(value=-0.6383, unit=elementary charge**2), Quantity(value=0.257220183, unit=nanometer), Quantity(value=0.7869021223760931, unit=kilojoule/mole)]
```

And example box sizes, written out every 1000 steps (barostat frequency is 25 steps)
```
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
INFO:__main__:Box size: [Vec3(x=4.635374361917076, y=0.0, z=0.0), Vec3(x=0.0, y=4.635382317742831, z=0.0), Vec3(x=0.0, y=0.0, z=9.270748723834153)] nm
```

**Comment by peastman** [comment] 2020-04-28 21:29
It's hard to say exactly what's happening without a full test case I can use to reproduce the problem.  I can say, though, that adding nonbonded exceptions between atoms in different molecules isn't a good idea and can lead to unexpected behavior.  That's because exceptions are really bonded interactions.  They affect the interaction between two specific atoms, but not between each one and all the other periodic copies of the other.  For this sort of situation, the best approach is usually a CustomNonbondedForce that looks up interaction parameters in a Discrete2DFunction.

**Comment by z-gong** [comment] 2020-05-01 12:06
I think it comes from the method of position scaling in MC barostat. When MC barostat scales the box, it scales the positions of particles in groups of molecules. That is, the centers of the molecules are scaled, and all particles belong to the same molecule are shifted together towards the new center, so that the constraints are not violated.

OpenMM determines molecules through bonds and constraints. Since the NBException is actually bonded force, when you add a lot of intermolecular NBExceptions, MC barostat will treat all the particles in the system as a single molecule. Then the position scaling will fail. Imaging that MC barostat scale the box size by 1.1, it will introduece a gap at the boundary of the box, which will not be accepted certainly. Therefore, the box size stoping being updated.

So in your case, the solution is avoiding intermolecular NBException and use CustomNonbondedForce with Discrete2DFunction.

The method of MC barostat scaling positions in groups of molecules is efficient and robust for molecular liquids, but it indeed causes problems for some systems, like single-chain polymer, zeolite, covalent organic framework, etc. Probably it can be fixed by scaling positions in groups of constrained units instead of molecules.

**Comment by jchodera** [comment] 2020-05-04 01:57
>  Probably it can be fixed by scaling positions in groups of constrained units instead of molecules.

Excellent suggestion!

I wonder if this suggests an API extension to `MonteCarloBarostat` that allows the user to specify multiple modes:
* molecular scaling
* constraint group scaling
* atomic scaling

For example, we could have
```
from simtk.openmm import MonteCarloBarostat
barostat = MonteCarloBarostat(temperature, pressure, frequency)
# Use atomic scaling
barostat.setScalingMethod(MonteCarloBarostat.ATOMIC_SCALING)
# Use molecular scaling
barostat.setScalingMethod(MonteCarloBarostat.MOLECULAR_SCALING)
# Use constraint group scaling
barostat.setScalingMethod(MonteCarloBarostat.CONSTRAINT_GROUP_SCALING)
# Get scaling method
scaling_method = barostat.getScalingMethod()
```
The one other feature this may interact with is when atom masses are set to zero, they are not updated by the integrator. We may want to control how and whether these should be scaled as well.

**Comment by EqualAPriori** [comment] 2020-05-05 20:20
Thanks for the insights -- this makes a lot of sense, I'll use custom nonbonded forces instead. I hadn't realized that the exceptions are treated as bonded interactions for the purposes of the barostat.

**Closed** 2020-12-04 21:10 UTC
