### ISSUE TITLE
Problem adding membrane to system

### ISSUE THREAD

**Issue by H-EKE** [openmm/openmm#4023] opened 2023-04-05 10:15 UTC
Hi,

I am trying to build a membrane-protein system with openmm and minimize it. When I run this code:

```
from openmm.app import *
from openmm import *
from openmm.unit import *

# Load in the PDB strucure
pdb = PDBFile('ranked_0.pdb')

# Specifiy the forcefield 
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addMembrane(forcefield, lipidType='POPC', minimumPadding=1*nanometer)

# Combine the molecular topology and the forcefield
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

# Create the integrator to use for advacing the equations of motion.
# It specifies a Langevin integrator.
# The paramters set are temperature, friction coefficient, and timestep.
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)

# Combines the molecular topology, system, and integrator 
# to begin a new simulation.
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)

# Perform local energy minimization
print("Minimizing energy...")
simulation.minimizeEnergy(maxIterations=100)

# Write the trajectory to a file called "output.pdb"
simulation.reporters.append(PDBReporter('output.pdb', 1000))
```
I got this error mesagge:

CustomNonbondedForce must have exactly as many particles as the System it belongs to

Would you know what am i doing wrong?

Thanks!

**Comment by sef43** [comment] 2023-04-05 13:36
I think you need to change:
```python
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
```
to
```python
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
```

**Comment by H-EKE** [comment] 2023-04-05 14:36
Hi @sef43 ,

Thanks for your fast reply.

I modified the code and still getting the same erro:t

from openmm.app import *
from openmm import *
from openmm.unit import *

# Load in the PDB strucure
pdb = PDBFile('ranked_0.pdb')

# Specifiy the forcefield 
forcefield = ForceField('charmm36.xml', 'charmm36/water.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addHydrogens(forcefield)
modeller.addMembrane(forcefield, lipidType='POPC', minimumPadding=1*nanometer)

# Combine the molecular topology and the forcefield
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds)

# Create the integrator to use for advacing the equations of motion.
# It specifies a Langevin integrator.
# The paramters set are temperature, friction coefficient, and timestep.
integrator = LangevinMiddleIntegrator(300*kelvin, 1/picosecond, 0.004*picoseconds)

# Combines the molecular topology, system, and integrator 
# to begin a new simulation.
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)

# Perform local energy minimization
print("Minimizing energy...")
simulation.minimizeEnergy(maxIterations=100)

# Write the trajectory to a file called "output.pdb"
simulation.reporters.append(PDBReporter('output.pdb', 1000))




Error output

 File "/sequence/build.py", line 12, in <module>
    modeller.addMembrane(forcefield, lipidType='POPC', minimumPadding=1*nanometer)
  File "/.conda/envs/openmm/lib/python3.10/site-packages/openmm/app/modeller.py", line 1455, in addMembrane
    context = Context(system, integrator)
  File "/.conda/envs/openmm/lib/python3.10/site-packages/openmm/openmm.py", line 12378, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
openmm.OpenMMException: CustomNonbondedForce must have exactly as many particles as the System it belongs to.

**Comment by peastman** [comment] 2023-04-05 14:47
Could you post your input file so I can try to reproduce it?  Also, could you edit your posts and put lines containing \`\`\` just before and after the code?  That will make it display the code correctly rather than interpreting it as markup.

**Comment by peastman** [comment] 2023-04-06 17:17
`addMembrane()` doesn't work properly with CHARMM36.  To run the simulation for relaxing the membrane, it needs to modify the System.  It knows how to modify a NonbondedForce but not a CustomNonbondedForce, which CHARMM36 uses to represent LJ interactions.

The workaround is to pass a different force field to it:

```python
ff2 = ForceField('amber14-all.xml', 'amber14/tip3pfb.xml')
modeller.addMembrane(ff2, lipidType='POPC', minimumPadding=1*nanometer)
```

With that change the error goes away, but when it starts relaxing the membrane the simulation blows up and produces NaNs.  I believe that's because your protein isn't positioned correctly.  See the [comments about positioning](http://docs.openmm.org/latest/api-python/generated/openmm.app.modeller.Modeller.html#openmm.app.modeller.Modeller.addMembrane) in the documentation.  When I look at your PDB file along the z axis, it doesn't look anything like a transmembrane domain.

I'm going to mark this issue as a bug, because `addMembrane()` really ought to work with CHARMM36.  I think it should be easy to make it work.

**Comment by peastman** [comment] 2023-04-06 18:05
The fix is in #4025.

**Comment by H-EKE** [comment] 2023-04-07 14:52
Thank for your reply @peastman ! I am user of charm-gui web server, and I was trying to see which features I could use in openmm to develop an internal pipeline

**Closed** 2023-04-07 15:56 UTC
Labels: bug

**Comment by peastman** [comment] 2023-04-07 15:57
I merged the fix.  It should work correctly with CHARMM in the next release.

In the mean time, it's still fine to use CHARMM36 for your simulation.  You just need to pass a different force field to `addMembrane()`.
