### ISSUE TITLE
Segfault on osx with certain GPUs when requesting mixed or double precision

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#2407] opened 2019-09-28 08:59 UTC
I think I've been able to replicate a segfault on `osx` similar to what we've been seeing on travis with `openmmtools` (and potentially `openmm` travis tests).
On my MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) with an Intel Iris Plus Graphics 650 (1536 MB), I've found that attempting to use `mixed` or `double` precision on the OpenCL platform leads to a segfault:
```bash
(base) lski2414:example choderaj$ python osx-segfault.py
python(79335,0x7fffc383b3c0) malloc: *** error for object 0x7f8185b06408: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
I've attached a ZIP file containing a very simple script to reproduce this and the associated files.

I suspect this will only segfault on certain GPUs, however, so I am happy to do some debugging on my local machine if you can't find a machine that shows this behavior. I'd just need some pointers on what to do.

If GPUs that cause a segfault do not support any double-precision operations, it would be great if we could at least make sure the code throws an exception instead of segfaulting, since we can catch exceptions (but not segfaults).

I'm using an  OpenMM 7.5.0 nightly dev build (`7.4.0.dev-a9ea2b9`).

[osx-segfault.zip](https://github.com/openmm/openmm/files/3665252/osx-segfault.zip)

**Comment by peastman** [comment] 2019-09-28 15:05
This is a SWIG bug that I haven't found a solution for.  OpenMM is just throwing an exception saying that your GPU doesn't support double precision.  SWIG is supposed to translate C++ exceptions into Python exceptions.  But on Macs, it segfaults instead.

**Comment by peastman** [comment] 2024-12-03 01:00
I can't reproduce this problem anymore.  Perhaps it was fixed in SWIG at some point?  This is with OpenMM 8.2 on a Mac with M1 Pro:

```
>>> context = Context(sys, integ, Platform.getPlatform('OpenCL'), {'Precision':'mixed'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/peastman/miniconda3/envs/qcportal/lib/python3.11/site-packages/openmm/openmm.py", line 2488, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: No compatible OpenCL platform is available
```

I think that means we can close this.

**Closed by peastman** 2024-12-03 01:00 UTC
Labels: bug
