### ISSUE TITLE
Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)

### ISSUE THREAD

**Issue by nnnwyn** [openmm/openmm#3598] opened 2022-05-09 07:00 UTC
Hi, when i used openmm, i met the error below, could you give me some advice? Thanks so much.
 `Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)`.
OpenMM Version: openmm=7.5.1
Driver Version: 450.142.00
CUDA Version: 11.0 
<img width="2520" alt="WeChat4b79255cf6eb2d867dff6af5eba162b3" src="https://user-images.githubusercontent.com/25558295/167356834-7e0a2901-7560-485d-a1ce-d02680539c40.png">

**Comment by peastman** [comment] 2022-05-09 14:52
This generally means you're using a CUDA toolkit that is too recent for your driver to support.  Conda installs its own CUDA toolkit.  It's supposed to pick one that's compatible with your driver, but in practice it often picks wrong.  I suggest upgrading your NVIDIA driver.

**Comment by peastman** [comment] 2022-05-09 20:23
I'm closing this issue, since it's a duplicate of #3585.

**Closed by peastman** 2022-05-09 20:23 UTC
