### ISSUE TITLE
Question about applying force to slab of atoms

### ISSUE THREAD

**Issue by kong1-731** [openmm/openmm#3703] opened 2022-07-18 22:09 UTC
I was just wondering if the Force class allows for a subset of atoms to experience a force. For example, I am interested in applying a force to a slab of atoms along the positive x direction and then seeing how the impact of that force propagates through the rest of the material and deforms the material in that direction. However, when I was looking into the OpenMM documentation, it is unclear to me if it is possible to define that subset of atoms. This is somewhat similar to my earlier question about the shockwave simulation (#3684), but I am now thinking of trying something even more simple by just applying a force to one side of the simulation. Thank you for any insight on this.

**Comment by peastman** [comment] 2022-07-18 22:32
Sure, what kind of force do you want to apply?  If it's just a constant force applied to a subset of atoms, CustomExternalForce would be the simplest way.  Or do you want something more complicated?

**Comment by kong1-731** [comment] 2022-07-18 22:44
I would like to apply a time varying force ramp. Ideally if it is possible I would also have a spatial gradient of the force applied to the subset of atoms based on location from the center of the plane.

**Comment by peastman** [comment] 2022-07-18 23:36
That should all be fine.  You can use a global parameter to set the overall magnitude of the force, then periodically change its value by calling `setParameter()` on the Context.  And you can write the energy so the force magnitude depends on position in whatever way you want.

Here are a couple of examples that might be helpful.

https://openmm.github.io/openmm-cookbook/dev/notebooks/cookbook/Applying%20a%20Constant%20External%20Force.html
http://docs.openmm.org/latest/userguide/application/04_advanced_sim_examples.html#applying-an-external-force-to-particles-a-spherical-container

The first of those also discusses modifying per-particle parameters to make the force change with time, but using a global parameter will be much more efficient in your case.

**Comment by kong1-731** [comment] 2022-07-18 23:41
Thank you so much! I really appreciate the examples, especially the first one because I had not seen that before.

**Comment by peastman** [comment] 2022-08-01 23:07
Closing this since the question has been answered.

**Closed by peastman** 2022-08-01 23:07 UTC

**Comment by kong1-731** [comment] 2022-09-26 20:31
I have a question regarding the "Applying a Constant External Force" example. I want to check that for the line setParticleParameters(external.setParticleParameters(0, 0, (-20, 0, 0)*kilojoules_per_m, the first 0 refers to the Fx parameter and the second 0 refers to the 0th atom. I have been making small modifications to this example, and I find that when I change to (0, 32, (-20, 0, 0)*kilojoules_per_m to try to modify the force on the 32nd atom, I see the following error.

<img width="646" alt="Screen Shot 2022-09-26 at 4 30 56 PM" src="https://user-images.githubusercontent.com/70727844/192374130-914be722-d29c-4f5a-8321-8650391dc355.png">

<img width="351" alt="Screen Shot 2022-09-26 at 4 21 38 PM" src="https://user-images.githubusercontent.com/70727844/192372478-86c49461-bee5-438e-a127-6a61ecd23df4.png">
ole/nanometer)

**Comment by peastman** [comment] 2022-09-26 21:37
Suppose you want to apply forces to atoms 1, 12, and 15.  You'll call `addParticle()` three times.  On the three calls, the first argument will be 1, 12, and 15 respectively.  It returns the index of the "particle term" you just added: 0, 1, and 2 respectively.

When you call `setParticleParameters()`, you're modifying one of those three particle terms you just added.  The first argument is the index that was returned by `addParticle()`: 0, 1, or 2.  It specifies which of the three terms to modify.  The second argument is the index of the particle to apply the force to: 1, 12, or 15.  It should be the same as what you specified when you called `addParticle()`.  It's also possible to change a term to apply the force to a difference particle, but if you do you'll need to reinitialize the context.  `updateParametersInContext()` doesn't support making that change.

**Comment by kong1-731** [comment] 2022-09-27 17:20
Thank you! So I suppose the important part of addParticle() is to make sure that every atom that will undergo a force is added to the context before starting the simulation to make it easier. Is it possible to use inequalities with the `CustomExternalForce `such as `external = CustomExternalForce('-fx*x-fy*y-fz*z; if z<0.01')`?

**Comment by peastman** [comment] 2022-09-27 18:08
You can implement inequalities using either the `step()` or `select()` function.  ` step(x)` = `0` if `x` is less than `0`, `1` otherwise.  `select(x,y,z)` = `z` if `x` = `0`, `y` otherwise.  You could write the expression as `'step(0.01-z)*(-fx*x-fy*y-fz*z)'`.

`updateParametersInContext()` takes effect immediately.  The new parameters are used on the next step.  But it's a somewhat expensive operation, so if possible you probably don't want to call it every step.  That will slow your simulation down a lot.

**Comment by kong1-731** [comment] 2022-09-27 18:21
Thank you! If I wanted to implement a double-sided inequality, say if -0.01<z<0.01, how would I use the select/step functions? Also if I use global parameters instead of per particle parameters, is `external.updateParametersInContext(simulation.context) `necessary or will `external.setGlobalParameterDefaultValue(2,timev_force)` already update the parameter?

```
external = CustomExternalForce('step(0.01-z)*(-fx*x-fy*y-fz*z)')
system.addForce(external)

#Global parameter
external.addGlobalParameter('fx', 1)
external.addGlobalParameter('fy', 1)
external.addGlobalParameter('fz', 1)

for i in group_atomID: 
     external.addParticle(i, [])

nstep=10
for i in range(nstep):
    timev_force = (-5*i)*kilojoules_per_mole/nanometer
    external.setGlobalParameterDefaultValue(0,timev_force)
    external.setGlobalParameterDefaultValue(1,timev_force)
    external.setGlobalParameterDefaultValue(2,timev_force)
    external.updateParametersInContext(simulation.context)
    simulation.step(10)

```

**Comment by peastman** [comment] 2022-09-27 18:26
You can create a double sided inequality by multiplying by two step functions: `step(0.01-z)*step(0.01+z)`.  If you can use a global parameter instead of a per-particle one, that will be much faster.  Updating a global parameter every step is no problem at all.  You set its value by calling `setParameter()` on the Context.  `setGlobalParameterDefaultValue()` just sets what its initial value will be on newly created Contexts.

**Comment by peastman** [comment] 2022-09-27 18:56
> I am now trying to figure out how to implement a radial force (radial in XY plane) that acts along the Z axis

Which direction do you want it to point in?  Radially outward from the origin in the xy plane, or along the z axis?

**Comment by peastman** [comment] 2022-09-27 19:06
I don't think it's possible for a conservative force to have exactly that behavior.  The force needs to be the gradient of a scalar potential.  If the magnitude of the force varies with x and y, that indicates the potential must depend on them, and therefore its gradient will have a component in the xy plane.

**Comment by kong1-731** [comment] 2022-09-27 19:10
If I were to set fx and fy to 0, would I be able to get a different fz depending on where the atoms are in the XY plane? Would I be better off using the per particle parameters and using CustomExternalForce('-fx*x-fy*y-fz') with different values for fz based on individual particle locations then?

**Comment by kong1-731** [comment] 2022-09-27 19:11
Since I don't really care to set  the values of fx and fy, would it make more sense to just use external = `CustomExternalForce(step(0.01-z)*step(0.01+z)*('-fz*(r^2)*z; r=(x*x + y*y)'))`?

**Comment by peastman** [comment] 2022-09-27 20:13
Understand that you're defining a scalar potential function.  The force is the negative gradient of the potential.  If you define the potential as `-fz*(x^2+y^2)*z`, the force is `(2*fz*x*z, 2*fz*y*z, fz*(x^2+y^2))`.  That's how potential functions work: if it depends on a variable, there will necessarily be a force acting on that variable.

**Comment by kong1-731** [comment] 2022-09-27 20:20
Ah I forgot about that and see what you mean now. Does the per particle parameter definition make more sense then because the derivative will still just be whatever I set fx, fy, and fz to be for each particle?

**Comment by peastman** [comment] 2022-09-27 20:31
If you really are trying to create a non-conservative force, there are ways of doing it.  But are you really sure that's what you want?  That should only be done in unusual situations, and only if you're absolutely certain you know what you're doing!  Including a non-conservative force means you're throwing out thermodynamics, and any thermal sampling algorithm won't work correctly.

**Comment by kong1-731** [comment] 2022-09-27 20:33
I am trying to emulate a particular experience that creates a spatial force gradient across a membrane. What is the thermodynamic difference between applying a time-varying external force to a slab of atoms where the force is equal on every atom vs applying a time and spatially varying external force to a slab of atoms?

**Comment by peastman** [comment] 2022-10-03 19:15
Sorry for not replying sooner.  You're correct, a time varying force will of course not conserve energy.  That needs to be done carefully.  For example, it's common to gradually ramp up a force during equilibration, but only collect statistics over periods when it remains constant.  It also is possible to compute the work done by changing the force, which can then be included in the analysis to produce correct statistical results.

Can you describe the experiment you want to emulate, and what quantities you want to calculate?

**Comment by kong1-731** [comment] 2022-10-03 19:36
I am emulating experiments that are based off of the following paper, wherein an oscillating acoustic pressure is applied to a membrane (https://pubmed.ncbi.nlm.nih.gov/24194863/; I think the abstract of this paper describes what is going on well). I am modulating the power and frequency of the input acoustic wave. In the MD simulation, my system is a membrane patch solvated in water, and since I am using periodic boundary conditions, I am not expecting to see the membrane deformation that was measured in the paper. I instead would like to measure the stress and strain on the membrane over time from the acoustic input. 

Since this is a non-equilibrium simulation, I was also planning to repeat the simulations from different starting conditions sampled after the membrane has equilibrated to normal temperature and pressure conditions to see if the results are replicable and possibly get the average stress/strain trace over time. I ideally would also like to measure and record the 3D pressure field, but I have not had any luck getting an accurate readout of the pressure from OpenMM with this method (https://aip.scitation.org/doi/10.1063/1.2363381). 

I have already tried applying modulating pressure to the system (which is affected by the barostat), but I would like to investigate the effect of the radiation force as well by creating an oscillating force input in a slab of water to resemble what the radiation force would do to the membrane. If you happen to have in-person office hours, I will describe this better with reference to a diagram.

**Comment by kong1-731** [comment] 2022-10-04 22:33
Yes, the slab of water is parallel to the membrane. I see what you mean about the boundary conditions...Will I be able to see the evolution of that force across the membrane then? 

Do you suggest using non-periodic boundary conditions along the direction of the force (eg  non-periodic boundary conditions in say the z direction while XY remain periodic boundaries)? I noticed in the "5.2. Applying an External Force to Particles: a Spherical Container" example that nonperiodic boundary conditions were generated with this external force. Would it be valid to enforce nonperiodic boundary conditions with something akin to the following with the z upper and lower boundaries on the edge of the system?
` force = CustomExternalForce('100*step(z_upper_boundary-z)*step(z_lower_boundary+z))`

Thank you so much for your suggestions. I do plan to use a faster oscillation to avoid the microsecond timescale!

**Comment by peastman** [comment] 2022-10-05 19:48
I recommend varying the pressure as the first thing to try.  That should be the closest to reproducing what was done in the experiment.  If you use a MonteCarloAnisotropicBarostat, you can even vary just the pressure in the Z direction, while keeping the pressure in the XY plane fixed.  You should first measure how quickly the box volume changes in response to pressure changes, then make sure the oscillation is slow compared to that.

I don't think it's a good idea to simulate a membrane without periodic boundary conditions.  Unless you have a huge simulation box, you won't get realistic behavior.

**Comment by kong1-731** [comment] 2022-10-05 20:27
Is there a way to remove periodic boundary conditions along the water axis however? I am intending to keep periodic boundary conditions in XY but not in Z along the direction perpendicular to the membrane.

**Comment by peastman** [comment] 2022-10-06 17:13
Periodic boundary conditions are all or none, sorry.  The best you can do is make the box very large in the z direction and apply restraints so no atom ever gets anywhere close to the edge.
