### ISSUE TITLE
getParticleParameters cannot handle `numpy int64`s

### ISSUE THREAD

**Issue by zhang-ivy** [openmm/openmm#2885] opened 2020-10-14 20:27 UTC
As a part of the COVID moonshot effort, we are running free energy calcs with perses on Folding@home. We are [adding a feature to perses](https://github.com/choderalab/perses/pull/740), and we encountered the following error when generate the necessary input files for Folding@home:
```Traceback (most recent call last):
  File "/home/zhangi/miniconda3/envs/perses-sims/bin/perses-fah", line 11, in <module>
    load_entry_point('perses==0.8.2.dev0', 'console_scripts', 'perses-fah')()
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/app/fah_generator.py", line 478, in run
    run_neq_fah_setup(**setup_options)
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/app/fah_generator.py", line 359, in run_neq_fah_setup
    setup_dict = run_setup(setup_options, serialize_systems=False, build_samplers=False)
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/app/setup_relative_calculation.py", line 559, in run_setup
    interpolate_old_and_new_14s = setup_options['anneal_1,4s'])
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/annihilation/relative.py", line 300, in __init__
    self.handle_nonbonded()
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/annihilation/relative.py", line 1424, in handle_nonbonded
    self._handle_original_exceptions()
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/perses-0.8.2.dev0-py3.7.egg/perses/annihilation/relative.py", line 1713, in _handle_original_exceptions
    [charge1_old, sigma1_old, epsilon1_old] = old_system_nonbonded_force.getParticleParameters(index1_old)
  File "/home/zhangi/miniconda3/envs/perses-sims/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 19448, in getParticleParameters
    val = _openmm.NonbondedForce_getParticleParameters(self, index)
TypeError: in method 'NonbondedForce_getParticleParameters', argument 2 of type 'int'
```
After some debugging, we figured out that we are passing `numpy int64`s, not `int`s to `getParticleParameters`. We might want to consider letting the python wrapper handle `numpy int64s` in addition to `int`s.

To reproduce this error, run the following:
```
conda create -n perses-sims -c conda-forge -c omnia -c openeye openforcefield openeye-toolkits perses openmm
pip uninstall perses 
git clone https://github.com/choderalab/perses.git
cd perses/
git checkout prespecified_geometry
python setup.py install 
perses-fah test.yaml
```

where test.yaml is (note that github doesn't support upload of yaml files):
```
protein_pdb: receptor.pdb
ligand_file: ligands.sdf
old_ligand_index: 0
new_ligand_index: 1
forcefield_files:
    - amber/ff14SB.xml # ff14SB protein force field
    - amber/tip3p_standard.xml # TIP3P and recommended monovalent ion parameters
    - amber/tip3p_HFE_multivalent.xml # for divalent ions
    - amber/phosaa10.xml # HANDLES THE TPO
trajectory_directory: RUN0
atom_expression:
    - IntType
bond_expression:
    - DefaultBonds
small_molecule_forcefield: gaff-2.11
phase_project_ids:
    complex: 10000
    solvent: 10001
    vacuum: vacuum
use_given_geometries: True
map_strength: 'default'
remove_constraints: False
map_strategy: 'geometry'
```

CC'ing @jchodera

**Comment by peastman** [comment] 2020-10-14 20:44
This is a duplicate of #2831.  I'm closing this issue so we can keep all the discussion in one place.

**Closed by peastman** 2020-10-14 20:44 UTC
