### ISSUE TITLE
Error when using metadynamics biasDir feature and multiple HPC jobs

### ISSUE THREAD

**Issue by k2o0r** [openmm/openmm#3741] opened 2022-08-15 15:00 UTC
Hello, I have recently been testing out the OpenMM built in metadynamics and I really like how it works. I was especially interested in the biasDir feature which allows multiple HPC jobs to share biases but I run into this error: 

`Traceback (most recent call last):
  File "/rds/user/kor20/hpc-work/Q12/PAP_tests/metad_test/sim1/PAP_metad.py", line 161, in <module>
    meta.step(sim2, 15000000)
  File "/home/kor20/miniconda3/envs/openmm_metad/lib/python3.9/site-packages/openmm/app/metadynamics.py", line 179, in step
    self._syncWithDisk()
  File "/home/kor20/miniconda3/envs/openmm_metad/lib/python3.9/site-packages/openmm/app/metadynamics.py", line 255, in _syncWithDisk
    data = np.load(os.path.join(self.biasDir, filename))
  File "/home/kor20/miniconda3/envs/openmm_metad/lib/python3.9/site-packages/numpy/lib/npyio.py", line 418, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
~                                                                                `

When one job is running everything is fine, but when a second job is added this error occurs in whichever job was started last after running for quite a few steps, just over 2m. It seems to be related to second job loading the bias file, but it can successful do that for a bit before failing.

It's not really necessary to use 2 GPUs at present because it's a fairly small test system, but I am definitely interested to use this feature in the future so any ideas on how to get it working is greatly appreciated, thanks!

**Comment by peastman** [comment] 2022-08-15 15:32
Strange, the biases ought to just be numbers, nothing that requires pickling.  I'll take a look.

**Comment by peastman** [comment] 2022-08-15 17:19
I can't reproduce this.  When I run it, the biases have dtype `float64` and there's no trouble reading the file.  Could you try loading in the file and see what it contains?

```python
data = np.load(filename, allow_pickle=True)
print(data.dtype)
print(data)
```

Could you also post the output of `conda list`?  That will show your versions of Python, Numpy, OpenMM, etc.

**Comment by k2o0r** [comment] 2022-08-15 21:40
>>> data = np.load('bias_1919998988_217.npy', allow_pickle=True)
>>> print(data.dtype)
float64
>>> print(data)
[[9.61563464e-09 9.64362028e-09 9.31268291e-09 ... 3.88265784e-54
  2.15981861e-55 1.15361877e-56]
 [3.16391082e-08 3.17743468e-08 3.07317995e-08 ... 1.39704753e-53
  7.77217898e-55 4.15173548e-56]
 [1.00031052e-07 1.00602259e-07 9.74606735e-08 ... 4.82597592e-53
  2.68509461e-54 1.43445761e-55]
 ...
 [1.01612560e+00 1.09659028e+00 1.14703736e+00 ... 3.91190259e-45
  2.18156889e-46 1.16806148e-47]
 [9.80043742e-01 1.06081567e+00 1.11302836e+00 ... 3.97573524e-45
  2.21730834e-46 1.18727015e-47]
 [9.08614805e-01 9.86431021e-01 1.03813793e+00 ... 3.87911373e-45
  2.16355774e-46 1.15855928e-47]]



This all looks as expected to me, here is the output from conda list:

# packages in environment at /home/kor20/miniconda3/envs/openmm_metad:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
bottleneck                1.3.5            py39h7deecbd_0  
ca-certificates           2022.07.19           h06a4308_0  
certifi                   2022.6.15        py39h06a4308_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
intel-openmp              2021.4.0          h06a4308_3561  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
ncurses                   6.3                  h5eee18b_3  
numexpr                   2.8.3            py39h807cd23_0  
numpy                     1.23.1           py39h6c91a56_0  
numpy-base                1.23.1           py39ha15fc14_0  
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openmm                    7.7.0            py39h15fbce5_1    conda-forge
openssl                   1.1.1q               h7f8727e_0  
packaging                 21.3               pyhd3eb1b0_0  
pandas                    1.4.3            py39h6a678d5_0  
pip                       22.1.2           py39h06a4308_0  
pyparsing                 3.0.4              pyhd3eb1b0_0  
python                    3.9.12               h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1           py39h06a4308_0  
readline                  8.1.2                h7f8727e_1  
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.39.2               h5082296_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022a                hda174b7_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7f8727e_1  
zlib                      1.2.12               h7f8727e_2  
`

**Comment by peastman** [comment] 2022-08-15 21:44
As a sanity check, what happens if you leave off the `allow_pickle=True` argument?  `float64` shouldn't require pickle.

**Comment by k2o0r** [comment] 2022-08-15 22:15
Nothing changes, it is very strange.  Clearly the second job is able to access the bias values in the correct datatype to start the simulation and run for  2 million steps so it is odd that it suddenly throws this error.

Could it be that the bias file is somehow 'in use' by the other job and that prevents it from being accessed by the second job? Doesn't seem very likely to me but it's the only thing I can think of.

**Comment by peastman** [comment] 2022-08-15 22:40
There should never be any problem with two processes reading the same file at the same time.  And it should never try to read a file that's only partly written.  It first saves to a file whose name begins with `temp_`, then renames it to `bias_` once the save is complete, and it only loads files whose names begin with `bias_`.

Is the problem reproducible?  If so, does it always happens after approximately the same number of steps?

**Comment by k2o0r** [comment] 2022-08-15 22:44
Hm ok, thanks for the explanation.

I think it is somewhat reproducible in that it happened 3 times earlier, it's a bit late here in the UK but I'll try the whole thing from scratch tomorrow and update the thread the with outputs if the error still throws. 

Thanks!

**Comment by peastman** [comment] 2022-08-15 23:08
Thanks.  And if you're able to create a complete test case I can use to reproduce it, even better!

**Comment by k2o0r** [comment] 2022-08-17 17:19
It turns out there were a few problems with my set up, so took some time to get those fixed and repeat things. So far the problem has not returned despite 3 GPUs now all running for >2m steps sharing biases. 

In terms of what was going wrong before, I think there were some problems with the definition of one of the CVs, could that be related to the problem? I think in this case the actual value of the CV was much larger than the max value in the BiasVariable.

**Comment by peastman** [comment] 2022-08-17 19:04
I don't think that should matter.  It only tabulates the bias over the range you specify.  If the actual value of the CV is far outside the range, that just means it has minimal impact on the tabulated bias values.

If the problem can't be reproduced, we may just have to attribute it to a cosmic ray!  Sometimes computers just fail in strange, unreproducible ways.

**Comment by k2o0r** [comment] 2022-08-18 07:09
I guess so! Thanks a lot for the help as always!

I did have one more question, if you don't mind. I want to implement an asphericity CV using equations like this.
<img width="242" alt="Screenshot 2022-08-18 at 08 03 35" src="https://user-images.githubusercontent.com/67603864/185327632-99092112-36c4-4896-8bb5-70a4d6a6dcc3.png">
Where T is the inertia tensor
<img width="215" alt="Screenshot 2022-08-18 at 08 03 48" src="https://user-images.githubusercontent.com/67603864/185327652-eb84ecee-e1f8-4408-9c7e-453c087e01dc.png">
And Delta is the asphericity parameter

I can see how it might be doable using a CustomBondForce if you can access x,y,z components of the particle positions but I'm not sure if you can. Any advice or alternative approaches for this would be very useful, thanks!

**Comment by peastman** [comment] 2022-08-18 15:48
You can use CustomCompoundBondForce.  It's a more general force that can reproduce many of the other custom bonded forces, while also providing extra features like access to the particle coordinates.

**Comment by k2o0r** [comment] 2022-08-18 16:42
Thanks!

**Comment by k2o0r** [comment] 2022-08-23 10:30
Hello, so I got round to doing this and I think I implemented it correctly but it runs rather slowly. My implementation goes something like this: 

(Get components of **T**)
T_xx = CustomCompoundBondForce(2, '(1/28)*(x1-x2)^2')
T_xy = CustomCompoundBondForce(2, '(1/28)*(x1-x2)*(y1-y2)')
T_xz = CustomCompoundBondForce(2, '(1/28)*(x1-x2)*(z1-z2)')
T_yy = CustomCompoundBondForce(2, '(1/28)*(y1-y2)^2')
T_yz = CustomCompoundBondForce(2, '(1/28)*(y1-y2)*(z1-z2)')
T_zz = CustomCompoundBondForce(2, '(1/28)*(z1-z2)^2') 

(Diagonalize **T** and return the asphericity)
`asph = CustomCVForce("N_asph*((eig_a-q)^2+(eig_b-q)^2+(eig_c-q)^2);\
    N_asph = 3/(2*Tr^2);\
    eig_b = 3*q-eig_a-eig_c;\
    eig_c = q+2*p*cos(phi);\
    eig_a = q+2*p*cos(phi+(2*3.14159/3));\
    phi = acos(r)/3;\
    r = det_B/2;\
    det_B = B_xx*(B_yy*B_zz-B_yz*B_zy)+B_xy*(B_yz*B_zx-B_yx*B_zz)+B_xz*(B_yx*B_zy-B_yy*B_zx);\
    B_xx = f*(T_xx-q);\
    B_xy = f*T_xy;\
    B_xz = f*T_xz;\
    B_yx = f*T_xy;\
    B_yy = f*(T_yy-q);\
    B_yz = f*T_yz;\
    B_zx = f*T_xz;\
    B_zy = f*T_yz;\
    B_zz = f*(T_zz-q);\
    f  = 1/p;\
    p  = sqrt(p2/6);\
    p2 = (T_xx-q)^2+(T_yy-q)^2+(T_zz-q)^2+2*p1;\
    p1 = T_xy^2+T_xz^2+T_yz^2;\
    q = Tr/3;\
    Tr = T_xx+T_yy+T_zz;")

asph.addCollectiveVariable('T_xx', T_xx)
asph.addCollectiveVariable('T_xy', T_xy)
asph.addCollectiveVariable('T_xz', T_xz)
asph.addCollectiveVariable('T_yy', T_yy)
asph.addCollectiveVariable('T_yz', T_yz)
asph.addCollectiveVariable('T_zz', T_zz)`


Now, adding these forces into the system slows it down by a factor of ~10 which is pretty bad. Do you think my code implementation is reasonable and this calculation will always be slow in OpenMM or do you think there's a better way of doing things?

For example, if CustomCompoundBondForce could somehow return more than one value all components of **T** could be calculated in a single force object rather than the 6 used here. Also the matrix diagonalisation could possibly be sped up using built in algorithms if that is possible.

Thanks!

**Comment by peastman** [comment] 2022-08-27 03:03
CustomCVForce does add overhead, and there's extra overhead for every CV.  How many bonds are there in each CustomCompoundBondForce?

**Comment by k2o0r** [comment] 2022-08-27 12:34
I was defining a bond between the central Ca of each coarse-grained peptide in the system, so there ends up being quite a few e.g. 2080 in a 64 chain system. I don't think this amount could be reduced for a useful CV.

Somehow adding a CV which represented **T** with components accessible in the CustomCVForce, rather than having each component as a separate CV seems like it could be efficient in theory but not sure if that is currently possible or would require modifying/extending the source code.

**Comment by peastman** [comment] 2022-08-29 20:00
I don't have any good suggestions for how to make it faster.  Evaluating each CV is equivalent to performing a force/energy evaluation, and involves a communication round trip between the CPU and GPU.  With six of them, that adds up to a lot of overhead.

If you can put together a self-contained test case, I could profile it and see if there's any obvious code changes that might help.

**Comment by jchodera** [comment] 2022-08-29 22:48
Could a multiple timestep method, with the CustomCVForce grouped into a force evaluated less frequently, be useful here? If the CVs are slowly varying, this may not introduce too much error.

> Evaluating each CV is equivalent to performing a force/energy evaluation, and involves a communication round trip between the CPU and GPU. With six of them, that adds up to a lot of overhead.

@peastman: Can you provide any more insight into the implementation details here? I wasn't aware this was moving information back and forth between CPU/GPU for each CustomCVForce

**Comment by peastman** [comment] 2022-08-29 22:58
Internally, CustomCVForce creates a System, adds the Forces defining the CVs to it (each in a different force group), and creates a Context for it.  Each CV evaluation is literally an energy evaluation with the internal Context.

**Comment by peastman** [comment] 2022-10-25 20:30
Closing this, since I believe the question has been answered.  Feel free to reopen it if I missed something.

**Closed by peastman** 2022-10-25 20:30 UTC
