### ISSUE TITLE
initial energy too high?

### ISSUE THREAD

**Issue by phisanti** [openmm/openmm#3015] opened 2021-02-09 14:05 UTC
Hi,

I have build a protein-membrane system. Something simple just to test. Then, I got to run the simulation, but the system seems to get stuck into the energy minimization step. 

Here is the code:

```python
# Build the system....

# Minimize:

for i in range(10):

    print(simulation.context.getState(getEnergy=True).getPotentialEnergy())
    simulation.minimizeEnergy(tolerance=5000*kilojoule/mole, maxIterations=1)

```
Here is the output:

```
2.7158684873909724e+18 kJ/mol
2.787598976719637e+18 kJ/mol
2.787598976719637e+18 kJ/mol
2.787598976719637e+18 kJ/mol
```

Looks like the energy is too high? If so, is there something I can do to minimize faster?

**Comment by swails** [comment] 2021-02-09 14:10
You can improve the starting configuration or use more than one minimization iteration.

**Comment by phisanti** [comment] 2021-02-09 14:12
Mmm, if I just leave it "minimising" for 10000000 steps or so, could I export the "minimized" crd/psf files?

**Comment by swails** [comment] 2021-02-09 14:27
The psf won't change. I don't think OpenMM has a function to write a charmm card file but you can always write a state xml to use in a later OpenMM step. 

If you want to go back to charmm you can always use ParmEd to write a charmm card file.

**Comment by phisanti** [comment] 2021-02-09 15:10
Okay, sounds like a good idea. Thanks for the advice. Does something like this would do the job?

```python
    # Output as PDB
    output_rst = os.path.join(input_exp, "structure_min.rst")
    output_state = os.path.join(input_exp, "structure_min.pdb")
    state = simulation.context.getState( getPositions=True, getVelocities=True )
    with open(output_rst, 'w') as f:
        f.write(XmlSerializer.serialize(state))
    crd = simulation.context.getState(getPositions=True).getPositions()
    PDBFile.writeFile(psf.topology, crd, open(output_state, 'w'))
```

**Comment by peastman** [comment] 2021-02-09 18:18
Try minimizing with

```python
simulation.minimizeEnergy(maxIterations=100)
```

If it's going to work, you should see a large decrease in energy in 100 iterations.  But I wouldn't be surprised if it doesn't work.  Your initial energy is really crazy high.  That suggests something is badly messed up, like large pieces of molecules directly on top of each other.  If so, that's more than the minimizer can fix.  You should look at the system and figure out where the problem is coming from.

**Comment by phisanti** [comment] 2021-02-09 18:34
I run the minimization for ~5000 steps and energy decrease to <0 (-5000 kj/mol or so). Then, I write the files as:

```python
    # Write minimized structure
    output_rst = os.path.join(input_exp, "structure_min.rst")
    print("writing minimized structure {}".format(output_rst))
    state = simulation.context.getState( getPositions=True, getVelocities=True )
    with open(output_rst, 'w') as f:
        f.write(XmlSerializer.serialize(state))

    # Write minimized topology
    output_topology = os.path.join(input_exp, "structure_min.pdb")
    crd = simulation.context.getState(getPositions=True).getPositions()
    PDBFile.writeFile(psf.topology, crd, open(output_topology, 'w'))
    print("\n...\n...\n...")

```
If I go and load the pdb, should it work I guess?? Thanks for the help to. The molecules were placed using the htmd package so maybe there is so bug on the process.

**Comment by peastman** [comment] 2021-02-09 19:16
Ok, great.  I'm going to close this issue, since I think everything has been answered.  Feel free to reopen it if I missed something.

**Closed by peastman** 2021-02-09 19:16 UTC
