### ISSUE TITLE
Error launching CUDA compiler: 256

### ISSUE THREAD

**Issue by dixonth1** [openmm/openmm#2779] opened 2020-07-13 20:40 UTC
Hi all,

I've been trying to start an MD simulation using the CUDA platform. When I try to make the simulation object I get the following error:

  File "python_scripts/straight_forward_sim.py", line 164, in <module>
    main(n_steps, save_interval)
  File "python_scripts/straight_forward_sim.py", line 125, in main
    simulation = omma.Simulation(psf.topology, system, integrator, platform)
  File "/home/dixonth1/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 103, in __init__
    self.context = mm.Context(self.system, self.integrator, platform)
  File "/home/dixonth1/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55ccf079a980_843167.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x55ccf079a980_843167.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x55ccf079a980_843167.cu".

When I run the same script using the CPU platform it works fine but I'd like the speed up the GPUs provide.
Thanks in advance!

**Comment by peastman** [comment] 2020-07-14 16:32
This is fixed in #2694.  What version of OpenMM are you using?  So far as I know, this error only occurred in development code, not in any released version.

**Comment by dixonth1** [comment] 2020-07-14 17:04
I am using OpenMM version 7.4.2 I installed from the omnia channel on Anaconda.

**Comment by aizvorski** [comment] 2020-09-08 01:55
I can second this.  OpenMM 7.4.2, installed from omnia channel, CUDA 10.0, using a script from CHARMM-GUI; Ubuntu 18.04 on AWS

```
Traceback (most recent call last):                                                                                                                                                                                  
  File "openmm_run.py", line 74, in <module>
    simulation = Simulation(psf.topology, system, integrator, platform, prop)                                                                                                                                         File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__                                                                                                   
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__                                                                                                             this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x5581783265b0_3738.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
                                                                                                                                                                                                                    /tmp/openmmTempKernel0x5581783265b0_3738.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-cons
texpr' can be used to allow this.                                                                                                                                                                                   
                                                                                                                                                                                                                    
2 errors detected in the compilation of "/tmp/tmpxft_00000eb6_00000000-6_openmmTempKernel0x5581783265b0_3738.cpp1.ii".                                                                                              

```

**Comment by peastman** [comment] 2020-09-08 18:08
Can you try the beta of 7.5 and see whether you still get the error?  It should be fixed.

https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12332&p=0&start=0&view=&sid=344a5e6c4235a3445abd9d04746f447a

**Comment by aizvorski** [comment] 2020-10-31 19:15
@peastman I can confirm that openmm 7.5.0b1 cc3c4b5_py38_cuda102_0 from omnia-dev/label/beta does not have the error (everything else being the same). 

It seems to be present with openmm 7.4.2 and any CUDA 10.x, confirmed with 10.0 and 10.2 on a variety of different installs.  Would it make sense to do a bugfix release for openmm 7.4.x?  Or make the conda packages require 9.x?

I can help test as this is easy to reproduce, just let me know.

> Can you try the beta of 7.5 and see whether you still get the error? It should be fixed.
> 
> https://simtk.org/plugins/phpBB/viewtopicPhpbb.php?f=161&t=12332&p=0&start=0&view=&sid=344a5e6c4235a3445abd9d04746f447a

**Comment by jchodera** [comment] 2020-10-31 19:37
@aizvorski : Can you post a test script that reproduces this?

**Comment by aizvorski** [comment] 2020-10-31 21:41
@jchodera Here is a set of inputs: https://drive.google.com/file/d/1YPICCkJjIPZ-Hpwsdl2Ct9nPBFi2x3O4/view?usp=sharing

Command line:

```
~$ tar xzf charmm-gui-0417764341.tgz
~$ cd charmm-gui-0417764341/openmm
charmm-gui-0417764341/openmm$ python -u openmm_run.py -i step4_equilibration.inp -t toppar.str -p step3_charmm2omm.psf -c step3_charmm2omm.crd -b step3_charmm2omm.str -orst step4_equilibration.rst -odcd step4_equilibration.dcd > step4_equilibration.out
...
Traceback (most recent call last):
  File "openmm_run.py", line 74, in <module>
    simulation = Simulation(psf.topology, system, integrator, platform, prop)
  File "/home/genesis/downloads/miniconda/envs/omm/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/genesis/downloads/miniconda/envs/omm/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55de6cb15b80_16242.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

```

This comes from CHARMM-GUI Solution Builder using 2RJY as the input structure, and all default settings, no manual changes.

Thanks!


> @aizvorski : Can you post a test script and input files that reproduces this?

**Comment by jchodera** [comment] 2020-10-31 22:27
@aizvorski : I cannot reproduce this on `linux` with CUDA 10.1 on a GTX 1080 using the omnia openmm 7.4.2 for CUDA 10.1 (`py37_cuda101_rc_1`)
```
(perses) [chodera@lilac:openmm]$ python -c "from simtk import openmm ; print(openmm.version.version)"
7.4.2.dev-dc9d188
```
The script executes to completion, and aside from some warnings
```
/home/chodera/miniconda/envs/perses/lib/python3.7/site-packages/simtk/openmm/app/charmmparameterset.py:373: UserWarning: Replacing dihedral <DihedralType: k=0.5; phase=0.0; per=3> with <DihedralType: k=0.0; phase=180.0; per=3>
```
seems to be totally fine.

Can you provide more details of your setup?

**Comment by aizvorski** [comment] 2020-10-31 22:55
Hmm, interesting!

My setup is a VM with a P4 GPU on Google Cloud Platform; Ubuntu 18.04.4 LTS; CUDA installed from NVIDIA's repo, cuda-10-2 10.2.89-1; and miniconda. 

I've also tried the same on T4 and V100 instances on AWS, using a few different versions of the [AWS Deep Learning AMI](https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5) which has CUDA preinstalled.  In every case `python -m simtk.testInstallation` works totally fine, but the example (or anything else from CHARMM-GUI) fails in the same way.

Here's the environment.yml from conda env export:

```
name: omm
channels:
  - omnia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - arpack=3.7.0=hc6cf775_2
  - blas=1.0=mkl
  - boost-cpp=1.74.0=h9359b55_0
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - curl=7.71.1=he644dc0_8
  - cycler=0.10.0=py_2
  - cython=0.29.21=py37he6710b0_0
  - fftw=3.3.8=nompi_h7f3a6c3_1112
  - fftw3f=3.3.4=2
  - freetype=2.10.4=he06d7ca_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.6=nompi_h54c07f9_1110
  - icu=67.1=he1b5a44_0
  - intel-openmp=2020.2=254
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py37h99015e2_1
  - krb5=1.17.1=hfafb76e_3
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=1_h6e990d7_netlib
  - libcblas=3.9.0=2_h6e990d7_netlib
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libgomp=9.3.0=h5dbcf3e_17
  - liblapack=3.9.0=2_h6e990d7_netlib
  - libnetcdf=4.7.4=nompi_hefab0ff_106
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libpng=1.6.37=hed695b0_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib-base=3.3.2=py37hc9afd2a_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - netcdf-fortran=4.5.3=nompi_hfef6a68_101
  - numpy=1.19.1=py37hbc911f0_0
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openmm=7.4.2=py37_cuda101_rc_1
  - openssl=1.1.1h=h516909a_0
  - perl=5.30.3=h516909a_1
  - pillow=8.0.0=py37h718be6c_0
  - pip=20.2.4=py37_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=h7b6447c_0
  - scipy=1.5.2=py37hb14ef9d_2
  - setuptools=50.3.0=py37hb0f4dca_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.0.4=py37h8f50634_2
  - wheel=0.35.1=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - amberlite==16.0
    - ambertools==20.9
    - mmpbsa-py==16.0
    - packmol-memgen==1.1.0rc0
    - parmed==at20RC5+54.g5702a232fe.dirty
    - pdb-tools==2.2.1
    - pdb4amber==1.7.dev0
    - pytraj==2.0.5
    - sander==16.0
```

```
$ nvidia-smi 
Sat Oct 31 22:47:54 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   85C    P0    66W /  75W |    187MiB /  7611MiB |     66%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by peastman** [comment] 2020-11-01 21:07
We're hoping to get out the release candidate of 7.5 "any day now".  The code is basically done.  But we've switched to a completely different infrastructure for building packages, and that's taken a lot longer than we hoped.

**Comment by peastman** [comment] 2020-12-05 00:12
Closing since this is fixed in 7.5.  The release candidate was posted earlier this week.

**Closed by peastman** 2020-12-05 00:12 UTC

**Comment by RaulPPelaez** [comment] 2023-05-16 08:00
I have not encountered this error before, but just a couple of guesses:
1. Have you tried pointing OpenMM to nvcc manually?: OPENMM_CUDA_COMPILER=/<path_to_custom_cuda_dir>/nvcc
2. I could see something like this happening if the /tmp/ folder gets filled. Maybe try to run by using a different TMPDIR?
    ```shell
    $ mkdir tmp
    $ TMPDIR=$(pwd)/tmp make test
    ```
I agree the path you get is strange looking. Could you share the specific line you use for cmake?

**Comment by balazsfabian** [comment] 2023-05-16 09:17
1. I have already tried to point OpenMM to nvcc manually, because when I compiled 130124a3f9277b0 on a cluster, the test `TestCudaAnderesenThermostatSingle` was failing. Based on your suggestion, I ran explicit tests:
```
$ ./TestCudaAndersenThermostat
exception: Error launching CUDA compiler: 32512
sh: /usr/local/cuda/bin/nvcc: No such file or directory

$./TestCudaCompiler 
Done
```
The above error is similiar to #1352. Then, I export the path:
```
$ export OPENMM_CUDA_COMPILER=$(which nvcc)

$ ./TestCudaAndersenThermostat
Done

$ ./TestCudaCompiler 
sh: this does not exist/openmmTempKernel0x2066b80_95480.log: No such file or directory
```

From this, it seems like I pass either `TestCudaAndersenThermostat` or `TestCudaCompiler`, but not both.

2. Using a different TMPDIR also does not solve it:
```
TMPDIR=$(pwd)/tmp;  ./TestCudaCompiler
sh: this does not exist/openmmTempKernel0x733b80_98188.log: No such file or directory
exception: Error launching CUDA compiler: 256
```

**Comment by RaulPPelaez** [comment] 2023-05-16 09:44
Thanks!
Do you happen to have more than one CUDA version installed?
I understood the strange path you see:
https://github.com/openmm/openmm/blob/2ae50f9d4f171e84e0564adf6b0ba8e94c53ed1f/plugins/cudacompiler/tests/TestCudaCompiler.cpp#L91

**Comment by balazsfabian** [comment] 2023-05-16 10:14
I use environment modules, and I did not load two cuda versions at the same time.
Also, the `nvcc` that I point at is the the one that gets loaded.

**Comment by RaulPPelaez** [comment] 2023-05-16 10:15
Also this error:
``` sh : /usr/local/cuda/bin/nvcc: No such file or directory```
Comes from the fact that the CUDA platform assumes nvcc is located there by default. What I do not understand is why the CudaCompiler test passes when you dont specify where nvcc lives. I am guessing it is not trying to actually compile anything in that case and uses cached kernels.

I bet this works:
```shell
$ export OPENMM_CUDA_COMPILER=$(which nvcc)
$ export OPENMM_CACHE_DIR=/tmp/
$ ./TestCudaCompiler
```
Because of these lines:
https://github.com/openmm/openmm/blob/2ae50f9d4f171e84e0564adf6b0ba8e94c53ed1f/platforms/cuda/src/CudaContext.cpp#L157-L158
Following the CudaTempDir property down the rabbit hole it does not seem to me like the directory is created if it does not exist.
There is this variable here that checks if the tempDir exists:
https://github.com/openmm/openmm/blob/2ae50f9d4f171e84e0564adf6b0ba8e94c53ed1f/platforms/cuda/src/CudaContext.cpp#L133-L134
That is not used anywhere else AFAIK.
@peastman Could this be the some leftover from an old functionality that got removed?

**Comment by balazsfabian** [comment] 2023-05-16 10:35
Unfortunately, the above suggestion still does not solve the issue.
```
$ ./TestCudaAndersenThermostat
Done

$ ./TestCudaCompiler
sh: this does not exist/openmmTempKernel0x105db80_16002.log: No such file or directory
exception: Error launching CUDA compiler: 256

$ export OPENMM_CUDA_COMPILER=$(which nvcc)
$ export OPENMM_CACHE_DIR=/tmp/

$ ./TestCudaCompiler
sh: this does not exist/openmmTempKernel0x19ddb80_16129.log: No such file or directory
```
I tried using a `$(pwd)/tmp` for tmp, but still no.
