### ISSUE TITLE
Run is crashing during Umbrella Sampling

### ISSUE THREAD

**Issue by praban07** [openmm/openmm#4398] opened 2024-01-17 10:55 UTC
I am running Umbrella sampling with openMM. I see that in many cases (but not in all) the system is crashing without any clear message. This usually happens after several nanonseconds of a run. There is a possibility that my force constant used to define the umbrella potential is not large enough. However, even for larger force constant it happens.  One error message is

*** Error in 'Python': free( ): invalid pointer

I have attached my code, coordinate the topology file along with an output of a run that crashed. Can anyone suggest any solution?
thanks.

[failed_US.tar.gz](https://github.com/openmm/openmm/files/13962124/failed_US.tar.gz)

**Comment by peastman** [comment] 2024-01-17 16:38
That looks like a low level error of some sort that's crashing the Python interpreter.  Is it possible you have a memory leak somewhere and it eventually runs out of memory?  Trying monitoring it with `top` and see if the memory use is gradually increasing.

How consistent is the crash?  Does it always happen after about the same amount of time?  Or does it seem to be random?

**Comment by praban07** [comment] 2024-01-23 08:22
I could run 2 umbrella sampling long jobs. However, in the 3rd one it has crashed twice. The error message is given below.  Is it a python issue or an openMM issue? Don't see any solutions. Any help will be highly appreciated.

-------------------------------------

*** Error in `python': free(): invalid pointer: 0x00007efed6360cf0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7eff74ebb329]
python(+0x1cc7d7)[0x55b2142407d7]
python(_PyEval_EvalFrameDefault+0x4c1e)[0x55b214265c5e]
python(+0x2a5326)[0x55b214319326]
python(PyEval_EvalCode+0x9f)[0x55b2143189df]
python(+0x2c336a)[0x55b21433736a]
python(+0x2bf773)[0x55b214333773]
python(+0x2d4710)[0x55b214348710]
python(_PyRun_SimpleFileObject+0x1ae)[0x55b21434808e]
python(_PyRun_AnyFileObject+0x44)[0x55b214347e74]
python(Py_RunMain+0x2df)[0x55b21434201f]
python(Py_BytesMain+0x37)[0x55b2143074b7]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7eff74e5c555]
python(+0x29335d)[0x55b21430735d]
======= Memory map: ========
200000000-300200000 ---p 00000000 00:00 0
400000000-400200000 ---p 00000000 00:00 0
400200000-400400000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl
400400000-400600000 rw-s 00000000 00:05 23459                            /dev/nv                                                                                                             idia0
400600000-403600000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl
403600000-404000000 ---p 00000000 00:00 0
404000000-404200000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl
404200000-404400000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl
404400000-404600000 rw-s 404400000 00:05 34499                           /dev/nv                                                                                                             idia-uvm
404600000-404800000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl
404800000-404a00000 ---p 00000000 00:00 0
404a00000-404c00000 rw-s 00000000 00:05 19314                            /dev/nv                                                                                                             idiactl

**Comment by peastman** [comment] 2024-01-24 19:56
It's a very low level crash inside the Python interpreter.  The stack trace for where it happened doesn't include any OpenMM code, though it's hard to draw firm conclusions from that about what the root cause is.

Did you try monitoring the memory use like I suggested?

**Comment by praban07** [comment] 2024-02-12 14:52
Apologies for the long delay in replying. It is the problem of the machine. On another computer, it runs fine.

**Comment by peastman** [comment] 2024-02-12 16:52
Very strange!  Do you plan to investigate it further, or should we close this issue?

**Comment by praban07** [comment] 2024-02-12 17:20
Please close it. Talking to the vendor who supplied that machine to check
it.

**Closed** 2024-02-12 17:31 UTC
