### ISSUE TITLE
Disulfate bond patch is needed in CHARMM XML force fields 

### ISSUE THREAD

**Issue by WangXinyan940** [openmm/openmm#3801] opened 2022-10-11 10:18 UTC
Hi all, I found that the disulfate bond patch has not been added in the charmm36.xml and charmm_polar_2013/2019.xml force field files, which makes these files hard to be used in real-world projects since disulfate bonds occur in lots of proteins. 
I know these XML files were converted from CHARMM parameter files using scripts. In these XML files, the atom types and parameters for disulfate bonds are already there, but the patch itself is not. Is it possible to be fixed?

Many thanks!

**Comment by peastman** [comment] 2022-10-11 16:29
I assume you mean disulfide, not disulfate?  What makes you think the patch is missing?  I just checked charmm36.xml and it contains the following.

```xml
    <Patch name="DISU" residues="2">
      <RemoveAtom name="1:HG1"/>
      <RemoveAtom name="2:HG1"/>
      <ChangeAtom charge="-0.1" name="1:CB" type="CT2"/>
      <ChangeAtom charge="-0.1" name="2:CB" type="CT2"/>
      <ChangeAtom charge="-0.08" name="1:SG" type="SM"/>
      <ChangeAtom charge="-0.08" name="2:SG" type="SM"/>
      <AddBond atomName1="1:SG" atomName2="2:SG"/>
      <ApplyToResidue name="1:CYS"/>
      <ApplyToResidue name="2:CYS"/>
    </Patch>
```

**Comment by WangXinyan940** [comment] 2022-10-12 04:02
Oh yes, it's disulfide. Sorry for the typo. 

After further testing, charmm36.xml can work well with disulfide bonds. But in charmm_polar_2019.xml, this DISU patch really does not exist.

You can also test disulfide bond building using the following PDB & script. I am trying to use app.Modeller to add Drude particles to proteins. For proteins without disulfide bonds, things work well. But for proteins with disulfide bonds, the residue templates for now cannot solve them correctly.

```
import openmm as mm
import openmm.app as app
import openmm.unit as unit

charmmff = app.ForceField("charmm36.xml")
drudeff = app.ForceField("charmm_polar_2019.xml")

# Drude force field can be used in protein without disu- bond
pdb = app.PDBFile("no_disu.pdb")
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addExtraParticles(drudeff)

# Charmm 36 force field can be used in protein with disu- bond
pdb = app.PDBFile("disu.pdb")
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addExtraParticles(charmmff)

# Drude force field cannot be used in protein with disu- bond
pdb = app.PDBFile("disu.pdb")
modeller = app.Modeller(pdb.topology, pdb.positions)
modeller.addExtraParticles(drudeff)
```

[disu.zip](https://github.com/openmm/openmm/files/9761394/disu.zip)

**Comment by peastman** [comment] 2022-10-12 17:33
Thanks for the clarification.  It looks like this is a duplicate of #2848.  Addressing it will take some significant code changes as discussed there.

If it's ok with you, I'm going to close this issue as a duplicate.  That way the discussion won't get split between two different places.

**Closed by peastman** 2022-10-12 17:33 UTC
