### ISSUE TITLE
Error invoking kernel: CUDA error (700)

### ISSUE THREAD

**Issue by xzengae** [openmm/openmm#2431] opened 2019-10-18 21:17 UTC
Hi, 
I've installed Tinker-OpenMM (https://github.com/TinkerTools/Tinker-OpenMM) on our GPU clusters. But when I submit a bunch of jobs to run the simulations, some jobs could run successfully, some just throws an error after running several minutes or nearly 1 hour, even in the same node (seems that the job only runs in cpu because the simulation is super slow compared to running on GPU):

terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what(): Error invoking kernel: CUDA error (700)

The system is CentOS release 6.9,
GPU cards: Tesla K20m (some nodes are Tesla K20Xm).
CUDA version: 10.1 (I've also tried to compiled the source code by using 9.1, still doesn't work).

Any one have any thoughts about this? Thanks!

**Comment by peastman** [comment] 2019-10-18 21:34
Tinker-OpenMM is a forked version of OpenMM that has diverged quite far from the standard OpenMM.  I can't help with it.  If you're able to reproduce this with standard OpenMM I'll be happy to take a look.

**Comment by peastman** [comment] 2019-10-28 16:53
I'm closing this, since it doesn't apply to standard OpenMM.

**Closed by peastman** 2019-10-28 16:53 UTC
