### ISSUE TITLE
SystemError: <built-in function Context_getState> returned NULL without setting an error

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#3247] opened 2021-09-14 16:00 UTC
I've run into an error I haven't seen before:
```
  File "waterhop2.py", line 187, in compute_energy_and_forces
    state = context.getState(getEnergy=True, getForces=True)
  File "/Users/choderaj/miniconda/envs/perses-dev/lib/python3.8/site-packages/simtk/openmm/openmm.py", line 2618, in getState
    state = _openmm.Context_getState(self, types, enforcePeriodicBox, groups_mask)
SystemError: <built-in function Context_getState> returned NULL without setting an error
```
What circumstances might cause `Context::getState()` to return `NULL`? Shouldn't this be an OpenMM exception instead of triggering a (presumably via Swig) Python `SystemError`?

**Comment by peastman** [comment] 2021-09-14 16:46
Duplicate of #3098.  That means you're using 7.5.1.  It works correctly in 7.6.

**Closed** 2021-09-28 19:44 UTC
