### ISSUE TITLE
No template found for ASN

### ISSUE THREAD

**Issue by RamiManaf** [openmm/openmm#2751] opened 2020-06-21 07:09 UTC
Hi. I want to import a PDB file and simulate it using amber. The PDB file is fixed using PDBFixer. This is the code for the fixing:

```python
from pdbfixer.pdbfixer import PDBFixer
from simtk.openmm.app import PDBFile
fixer = PDBFixer(filename='6vxx.pdb')
print("finding nonstandard residues...")
fixer.findNonstandardResidues()
print("find missing residues...")
fixer.findMissingResidues()
print("find missing atoms...")
fixer.findMissingAtoms()
print("replace nonstandard residues...")
fixer.replaceNonstandardResidues()
print("add missing atoms...")#nearly need 4 hours
fixer.addMissingAtoms()
print("add missing hydrogens...")
fixer.addMissingHydrogens(7.0)
print("writing...")
PDBFile.writeFile(fixer.topology, fixer.positions, open('6vxx-fixed.pdb', 'w'))
```
You can see the pdb file [here](https://mega.nz/file/rkU3xIJR#egYPiIsy5rDVpSBfobYRdpleWpe6xdNov0TdzJBBGes).
I was running the following simulation code:
```python
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from simtk.openmm.app.modeller import *
from sys import stdout

pdb = PDBFile('6vxx-fixed.pdb')
modeller = Modeller(pdb.topology, pdb.positions)
forcefield = ForceField('amber14-all.xml', 'tip3p.xml')
#modeller.addHydrogens(forcefield)
print("creating system...")
system = forcefield.createSystem(modeller.topology, nonbondedMethod=PME,
        nonbondedCutoff=1*nanometer, constraints=HBonds, ignoreExternalBonds=False)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True,
        potentialEnergy=True, temperature=True))
print("run")
simulation.step(10000)
```
The following error raise and telling that there is no template found for the residue ASN 80.
```
Traceback (most recent call last):
  File "C:/Users/LENOVO PC/PycharmProjects/OpenMM/Simulation.py", line 13, in <module>
    nonbondedCutoff=1*nanometer, constraints=HBonds, ignoreExternalBonds=False)
  File "C:\ProgramData\Miniconda3\lib\site-packages\simtk\openmm\app\forcefield.py", line 1174, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 80 (ASN).  The set of atoms matches ASN, but the bonds are different.
```

Even Though openmm found a template for the residue ASN 36. After long time of debugging I found that in the forcefield.py the variable `unmatchedResidues` contains many of the ASN residues other than the 80.
I tried to put `ignoreExternalBonds=True` and I know that this will not solve the problem directly and I got an error about a CYS 150 residue that matched two templates but now OpenMM found a template for the ASN 80 which means that the problem is just about matching the external bonds. I searched about any wrong bond in the topology and forcefield variables but didn't find anything interesting. Actually I wanted to debug the matching implementation but it occurs the file `simtk\openmm\app\internal\compiled.py` which is compiled.
Thanks in advance.

**Comment by peastman** [comment] 2020-06-21 15:20
Take a look at https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template.  It describes the common causes of this error and what to do about them.  If none of those fixes the problem, let me know and I'll see if I can reproduce the problem.

**Comment by RamiManaf** [comment] 2020-06-22 05:32
Thanks but I that didn't fix the problem.

**Comment by tristanic** [comment] 2020-06-22 20:10
I suspect the problem here is that many of the asparagine residues in 6vxx are glycosylated, and glycans aren't covered by the standard AMBER forcefield. The GLYCAM forcefield is what you'll need for that, but it doesn't currently work with OpenMM's automatic template matching (it has multiple residues with the same bond topology but different chirality). 
I have some code in ISOLDE to assign most common glycans to the right GLYCAM template - it's at https://github.com/tristanic/isolde/blob/master/isolde/src/openmm/amberff/glycam.py.
There's a further wrinkle, though: GLYCAM uses a different 1-4 scaling to the rest of the AMBER forcefield, and (unless something's changed since the last time I checked) OpenMM doesn't currently support mixed scaling. All in all, you're going to have a bit of an uphill battle to get this particular model running in OpenMM.

**Comment by peastman** [comment] 2020-06-22 20:13
What about using AmberTools to create a prmtop and then loading that into OpenMM?

**Comment by tristanic** [comment] 2020-06-22 20:20
That I don't know about - I don't personally work with AmberTools.

**Comment by peastman** [comment] 2020-06-22 20:33
I think it ought to work.  It loads the parameters for 1-4 interactions from the prmtop file, so it won't have any problem if the scale factors are different.

**Comment by peastman** [comment] 2020-08-12 23:06
I think everything on this issue has been addressed?  I'm going to go ahead and close it.  If there is anything still unresolved, feel free to reopen it.

**Closed by peastman** 2020-08-12 23:06 UTC
