### ISSUE TITLE
Incorrect behavior of context.reinitialize(preserveState=True)

### ISSUE THREAD

**Issue by z-gong** [openmm/openmm#3767] opened 2022-09-07 14:32 UTC
I have one state `state` loaded from `state.xml` and two systems `system0` and `system1` loaded from `system-0.xml` and `system-1.xml` respectively. These two systems have different bond, angle and customNB forces.

I try to create two identical contexts. The first context is created directly from `state` and `system1`. The second one is created in four steps: 1) create the context from `state` and `system0`; 2) remove all the forces in `system0`; 3) copy all the forces from `system1` to `system0`; 4) reinitialize the context with preserved state.

The description above may be quite confusing, so I put a test code below.

I expect the two contexts give identical energies. However, it's not the case. 

```python
from copy import deepcopy
from openmm import openmm as mm


def test_new_context(str_platform='CUDA'):
    with open('system-1.xml') as f:
        system1 = mm.XmlSerializer.deserialize(f.read())
    with open('state.xml') as f:
        state = mm.XmlSerializer.deserialize(f.read())
    integrator = mm.VerletIntegrator(0.001)
    platform = mm.Platform.getPlatformByName(str_platform)
    context = mm.Context(system1, integrator, platform)
    context.setState(state)
    print(str_platform, 'Energy of new context:', context.getState(getEnergy=True).getPotentialEnergy())


def test_reinitialize_preserve_state(str_platform='CUDA'):
    with open('system-0.xml') as f:
        system0 = mm.XmlSerializer.deserialize(f.read())
    with open('state.xml') as f:
        state = mm.XmlSerializer.deserialize(f.read())
    integrator = mm.VerletIntegrator(0.001)
    platform = mm.Platform.getPlatformByName(str_platform)
    context = mm.Context(system0, integrator, platform)
    context.setState(state)

    with open('system-1.xml') as f:
        system1 = mm.XmlSerializer.deserialize(f.read())
    while system0.getNumForces() > 0:
        system0.removeForce(0)
    for force in system1.getForces():
        system0.addForce(deepcopy(force))
    context.reinitialize(preserveState=True)

    print(str_platform, 'Energy of reinitialized context with preserved state:',
          context.getState(getEnergy=True).getPotentialEnergy())


if __name__ == '__main__':
    test_new_context('CUDA')
    test_reinitialize_preserve_state('CUDA')

    test_new_context('CPU')
    test_reinitialize_preserve_state('CPU')

```
For the CUDA platform, calling `context.reinitialize(preserveState=True)` behaves incorrectly, giving different energy. With the CPU platform, the energy is correct.
```
CUDA Energy of new context: 12679.09765625 kJ/mol
CUDA Energy of reinitialized context with preserved state: 5024033.0 kJ/mol
CPU Energy of new context: 12679.096679226157 kJ/mol
CPU Energy of reinitialized context with preserved state: 12679.096679226146 kJ/mol
```

The files to reproduce this bug is attached:
[bug-context-reinitialize.zip](https://github.com/openmm/openmm/files/9507071/bug-context-reinitialize.zip)

**Comment by z-gong** [comment] 2022-09-07 14:51
After more debugging, I suspect it has something to do with the atom index in CUDA platform.
I try to perform energy minimization on the two contexts I created. In `system1`, there is a strong bond between atom 804 and 120 `<Bond d=".28" k="400000" p1="804" p2="120"/>`. Therefore, a successful minimization should cause the distance between 804 and 120 to be 0.28 nm.

However, for the second context, the result shows that the distance is 1.43nm, whereas the distance between 804 and 88 is 0.28 nm. Strangely, there is no such a bond between 804 and 88.

```python
import math
import numpy as np
from copy import deepcopy
from openmm import openmm as mm


def periodic_distance(pos1, pos2, box):
    delta = pos1 - pos2
    delta[0] -= math.ceil(delta[0] / box[0] - 0.5) * box[0]
    delta[1] -= math.ceil(delta[1] / box[1] - 0.5) * box[1]
    delta[2] -= math.ceil(delta[2] / box[2] - 0.5) * box[2]
    return math.sqrt(np.dot(delta, delta))


def check_distance(state):
    positions = state.getPositions(asNumpy=True)._value
    box = np.diag(state.getPeriodicBoxVectors(asNumpy=True)._value)
    pos804, pos120, pos88 = positions[[804, 120, 88], :]
    distance_804_120 = periodic_distance(pos804, pos120, box)
    distance_804_88 = periodic_distance(pos804, pos88, box)
    print('Distance(804-120):', distance_804_120)
    print('Distance(804-88):', distance_804_88)


def test_new_context(str_platform='CUDA'):
    with open('system-1.xml') as f:
        system1 = mm.XmlSerializer.deserialize(f.read())
    with open('state.xml') as f:
        state = mm.XmlSerializer.deserialize(f.read())
    integrator = mm.VerletIntegrator(0.001)
    platform = mm.Platform.getPlatformByName(str_platform)
    context = mm.Context(system1, integrator, platform)
    context.setState(state)
    mm.LocalEnergyMinimizer.minimize(context, tolerance=100)
    state = context.getState(getPositions=True)
    print(str_platform, 'New context')
    check_distance(state)


def test_reinitialize_preserve_state(str_platform='CUDA'):
    with open('system-0.xml') as f:
        system0 = mm.XmlSerializer.deserialize(f.read())
    with open('state.xml') as f:
        state = mm.XmlSerializer.deserialize(f.read())
    integrator = mm.VerletIntegrator(0.001)
    platform = mm.Platform.getPlatformByName(str_platform)
    context = mm.Context(system0, integrator, platform)
    context.setState(state)

    with open('system-1.xml') as f:
        system1 = mm.XmlSerializer.deserialize(f.read())
    while system0.getNumForces() > 0:
        system0.removeForce(0)
    for force in system1.getForces():
        system0.addForce(deepcopy(force))
    context.reinitialize(preserveState=True)

    mm.LocalEnergyMinimizer.minimize(context, tolerance=100)
    state = context.getState(getPositions=True)
    print(str_platform, 'Context reinitialized with preserved state')
    check_distance(state)


if __name__ == '__main__':
    test_new_context('CUDA')
    test_reinitialize_preserve_state('CUDA')
    test_new_context('CPU')
    test_reinitialize_preserve_state('CPU')
```

Output
```
CUDA New context
Distance(804-120): 0.28009455603064987
Distance(804-88): 2.1602218733269125
CUDA Context reinitialized with preserved state
Distance(804-120): 1.4330486393569943
Distance(804-88): 0.2802104489658481
```

**Comment by peastman** [comment] 2022-09-08 19:23
You're correct, it's from the atom ordering.  The CUDA and OpenCL platforms internally reorder atoms for efficiency.  That has to be done in a way that doesn't affect any forces.  `reinitialize(preserveState=True)` works by creating a checkpoint, reinitializing the Context, and loading the checkpoint.  That fully restores the internal state of the Context, including the atom order.  The problem is that the atom order is no longer valid for the new set of forces.

Let me think about the best way to fix it.

**Comment by peastman** [comment] 2022-09-08 20:53
The fix is in #3771.

**Comment by z-gong** [comment] 2022-09-09 03:00
Thank you for the clarification. The update works correctly on my test cases.

I have another question about the atom reordering. If somehow (very long Morse bond present in the system, or use CustomNBForce to represent a bond), the reordering is not performed perfectly, e.g. some particles far apart from each other have close indexes, or some particles belong to the same molecules have very different indexes, would it affect the correctness of the calculation, or it only causes performance degradation?

**Closed** 2022-09-12 18:11 UTC

**Comment by peastman** [comment] 2022-09-12 18:13
It just affects performance.  The results will still be correct.  And as long as it's just a few of them, the effect should be small.
